apache-superset/superset-ui

README.md, packages/superset-ui-core/package.json, packages/superset-ui-translation/package.json
Update `package.json` to include `publishConfig`
> Note: to publish scoped packages, you need to add the following to each package.json:
```
"publishConfig": {
"access": "public"
}
```
from https://github.com/lerna/lerna/tree/master/commands/publish#readme
=>  update package.json to include publishConfig

packages/superset-ui-color/package.json, packages/superset-ui-color/src/SequentialScheme.js, packages/superset-ui-color/src/index.js, packages/superset-ui-color/test/SequentialScheme.test.js, packages/superset-ui-color/test/index.test.js
🏆 Enhancements
- Add BRAND_COLOR constant
- Add functionality to `SequentialScheme` to replace `colorScalerFactory` in `colors.js`
=> Update color module

README.md
Since it's 100% it seems worthwhile to add the codecov badge  ;)
=> [readme] add codecov badge

packages/superset-ui-chart/package.json, packages/superset-ui-demo/package.json
🐛 Bug Fix
- Also updating the version of the color package in the demo package to be the latest
=> Make connection and color packages peer dependencies

packages/superset-ui-chart/src/query/Metric.ts, packages/superset-ui-chart/test/query/Metric.test.ts, packages/superset-ui-chart/test/query/buildQueryObject.test.ts
Reverts apache-superset/superset-ui#63
=> Revert "[Chart]Unify Metric format"

packages/generator-superset/generators/app/index.js, packages/generator-superset/generators/legacy-plugin-chart-demo/index.js, packages/generator-superset/generators/legacy-plugin-chart-demo/templates/Stories.jsx, packages/generator-superset/generators/legacy-plugin-chart-demo/templates/index.js, packages/generator-superset/generators/legacy-plugin-chart/index.js, packages/generator-superset/generators/legacy-plugin-chart/templates/README.md, packages/generator-superset/generators/legacy-plugin-chart/templates/_package.json, packages/generator-superset/package.json, packages/generator-superset/test/app.test.js, packages/generator-superset/test/legacy-plugin-chart-demo.test.js, packages/generator-superset/test/legacy-plugin-chart.test.js
🏆 Enhancements
- Add more subgenerators to create package and demo in superset-ui-legacy
- Make the default generator show choices to select subgenerator
=> Add more subgenerators to create package and demo in superset-ui-legacy

packages/generator-superset/generators/legacy-plugin-chart-demo/index.js, packages/generator-superset/generators/legacy-plugin-chart-demo/templates/Stories.jsx, packages/generator-superset/generators/legacy-plugin-chart/index.js, packages/generator-superset/generators/legacy-plugin-chart/templates/_package.json, packages/generator-superset/generators/package/index.js
✨ Feature
- Allow user to choose language between `typescript` and `javascript` (only for package in `superset-ui` monorepo).
🔧 Refine
- Update generator to point to `latest` version.
- Change default demo frame size 
🐛 Bug Fix
- Correct letter case
=> Minor updates for generators

packages/generator-superset/generators/package/index.js, packages/generator-superset/test/app.test.js, packages/generator-superset/test/package.test.js
🏠 Internal
- Add unit tests when user select different `language` (`typescript`, `javascript`).
=> Add unit test for generator

package.json
🏠 Internal
- Bump `@data-ui/config` version
=> update @data-ui/config to fix build

CHANGELOG.md, packages/superset-ui-chart/package.json
- Add change log for `0.9.4`
🐛 Bug Fix
- Update `peerDependencies` requirement for `@superset-ui/chart`
=> update change log and dependency

package.json
* Update build config version (unpin `eslint` from `5.13.0` and let it resolves to `^5.14.1`)
* Fix #102
=> Fix: Update build config version

packages/superset-ui-chart/src/registries/ChartBuildQueryRegistrySingleton.ts, packages/superset-ui-chart/src/registries/ChartComponentRegistrySingleton.ts, packages/superset-ui-chart/src/registries/ChartMetadataRegistrySingleton.ts, packages/superset-ui-chart/src/registries/ChartTransformPropsRegistrySingleton.ts, packages/superset-ui-color/src/ColorSchemeRegistry.ts, packages/superset-ui-number-format/src/NumberFormatterRegistry.ts, packages/superset-ui-time-format/src/TimeFormatterRegistry.ts
🏆 Enhancements
- Enable warnings when values are overwritten in registries
=> Feat: Enable warnings when values are overwritten in registries

packages/superset-ui-chart/package.json, packages/superset-ui-color/package.json, packages/superset-ui-number-format/package.json, packages/superset-ui-time-format/package.json
BREAKING CHANGE: @superset-ui/core becomes peer dependency
=> refactor: make @superset-ui/core peer dependency

packages/superset-ui-dimension/src/index.ts, packages/superset-ui-dimension/src/mergeMargin.ts, packages/superset-ui-dimension/src/types.ts, packages/superset-ui-dimension/test/mergeMargin.test.ts
🏆 Enhancements
* Add `mergeMargin()` function for combining two margins.
=> feat: add mergeMargin() function

packages/superset-ui-dimension/src/index.ts
🏆 Enhancements
* export type `Margin` and `TextStyle`
=> feat: re-export types from @superset-ui/dimension

packages/superset-ui-dimension/src/computeMaxFontSize.ts, packages/superset-ui-dimension/src/getTextDimension.ts, packages/superset-ui-dimension/src/types.ts
🏆 Enhancements
Add `Dimension` type
=> feat: add dimension type

packages/superset-ui-color/src/colorSchemes/categorical/airbnb.ts, packages/superset-ui-color/src/colorSchemes/categorical/d3.ts, packages/superset-ui-color/src/colorSchemes/categorical/google.ts, packages/superset-ui-color/src/colorSchemes/categorical/lyft.ts
🏆 Enhancements
There was an ask to add tooltips for color schemes so users can remember which is which. I added labels to the color schemes to make tooltips more reader friendly.
=> feat: add labels to color scheme

CHANGELOG.md, package.json
* Update changelog for `0.10.10` and `0.11.0`
🏠 Internal
* Bump `build-config` version and introduce `commit-config`
* Close #127
=> docs: update changelog

.github/issue_label_bot.yaml
🏠 Internal
@kristw 
This addresses https://github.com/hamelsmu/MLapp/issues/25
=> chore: create issue_label_bot.yaml

package.json, packages/superset-ui-connection/test/SupersetClientClass.test.ts
🏠 Internal
* Bump build config to use `typescript` `3.5`.
* Replace `eslint-plugin-typescript` with `@typescript-eslint/eslint-plugin`
=> build: bump build-config

packages/superset-ui-chart/test/components/MockChartPlugins.tsx, packages/superset-ui-chart/test/components/SuperChart.test.tsx
🏠 Internal
* extract mock plugins into separate file
=> test: extract mock plugins into separate file

packages/superset-ui-core/src/index.ts, packages/superset-ui-core/src/utils/promiseTimeout.ts, packages/superset-ui-core/test/utils/promiseTimeout.test.ts
🏆 Enhancements
Add `promiseTimeout`, a `setTimeout` function that returns a promise.
=> feat: add setTimeout function that returns a promise.

packages/superset-ui-demo/package.json
🏠 Internal
Fix issue with `storybook` typings. #226
=> build: fix storybook type

packages/superset-ui-chart/src/components/SuperChart.tsx, packages/superset-ui-chart/src/components/SuperChartCore.tsx, packages/superset-ui-demo/storybook/stories/superset-ui-number-format/Stories.jsx, packages/superset-ui-demo/storybook/stories/superset-ui-time-format/Stories.jsx
🏠 Internal
* Fix lint errors due to changes in build tools.
=> build: fix lint errors

package.json, packages/superset-ui-core/package.json
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> build: remove babel transform runtime

docs/debugging.md
Frontend code has been moved by https://github.com/apache/incubator-superset/commit/a005e4568f14f32be23c317dc484b904ddc71dd9
=> Update frontend assets path in debugging doc

packages/superset-ui-superset-ui/package.json, packages/superset-ui-superset-ui/src/index.ts, packages/superset-ui-superset-ui/test/index.test.ts
🏆 Enhancements
Add `@superset-ui/validator` as part of the umbrella bundle.
=> feat: add validator to umbrella package

.github/workflows/ci.yml
🏠 Internal
Try using github actions for ci
=> build: add github workflow for build and test

packages/superset-ui-superset-ui/package.json, packages/superset-ui-superset-ui/src/index.ts, packages/superset-ui-superset-ui/test/index.test.ts
🏆 Enhancements
Add `@superset-ui/style` as part of the umbrella package `@superset-ui/superset-ui` for convenience.
=> feat: add style to umbrella package

packages/superset-ui-query/src/buildQueryObject.ts, packages/superset-ui-query/src/types/QueryFormData.ts, packages/superset-ui-query/test/buildQueryContext.test.ts, packages/superset-ui-query/test/buildQueryObject.test.ts
🏆 Enhancements
Add unit tests for #387, increase test coverage for core packages back to 100%.
cc @etr2460 @williaster @kristw @villebro
=> fix(superset-ui-query): add unit tests for #387

packages/superset-ui-superset-ui/package.json, packages/superset-ui-superset-ui/src/index.ts, packages/superset-ui-superset-ui/test/index.test.ts
🏆 Enhancements
Add `@superset-ui/control-utils` as part of the umbrella package `@superset-ui/superset-ui`
=> feat(superset-ui): include control utils in the umbrella package

packages/superset-ui-chart/src/models/ChartPlugin.ts, packages/superset-ui-chart/test/components/ChartDataProvider.test.tsx, packages/superset-ui-chart/test/components/MockChartPlugins.tsx, packages/superset-ui-chart/test/components/createLoadableRenderer.test.tsx, packages/superset-ui-connection/src/callApi/callApi.ts, packages/superset-ui-connection/src/types.ts, packages/superset-ui-connection/test/SupersetClient.test.ts, packages/superset-ui-connection/test/SupersetClientClass.test.ts, packages/superset-ui-connection/test/callApi/callApi.test.ts, packages/superset-ui-connection/test/callApi/callApiAndParseWithTimeout.test.ts, packages/superset-ui-connection/test/callApi/parseResponse.test.ts, packages/superset-ui-translation/src/Translator.ts, packages/superset-ui-translation/src/TranslatorSingleton.ts, plugins/legacy-plugin-chart-table/src/ReactDataTable.tsx, plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js, plugins/preset-chart-xy/src/BoxPlot/legacy/transformProps.ts, plugins/preset-chart-xy/src/BoxPlot/transformProps.ts, plugins/preset-chart-xy/src/ScatterPlot/legacy/transformProps.ts, plugins/preset-chart-xy/src/components/BoxPlot/BoxPlot.tsx, plugins/preset-chart-xy/src/components/Line/Line.tsx, plugins/preset-chart-xy/src/components/ScatterPlot/ScatterPlot.tsx
🏠 Internal
Fix another hundred or so of lint warnings. Down from 199 warnings to < 10.
=> fix: lint again

plugins/plugin-chart-word-cloud/package.json, plugins/plugin-chart-word-cloud/src/plugin/controlPanel.ts, plugins/plugin-chart-word-cloud/src/plugin/index.ts, yarn.lock
🏆 Enhancements
Word Cloud now has its own control panel.
I also picked up some automatic yarn.lock changes.
=> feat(plugin-chart-word-cloud): add control panel

plugins/legacy-plugin-chart-world-map/package.json, plugins/legacy-plugin-chart-world-map/src/controlPanel.js, plugins/legacy-plugin-chart-world-map/src/index.js
=> feat(plugin-chart-world-map): add control panel

plugins/legacy-plugin-chart-treemap/package.json, plugins/legacy-plugin-chart-treemap/src/controlPanel.js, plugins/legacy-plugin-chart-treemap/src/index.js
=> feat(plugin-chart-treemap): add control panel

plugins/legacy-plugin-chart-sankey/src/controlPanel.js
=> feat(plugin-chart-sankey): add control panel

plugins/legacy-plugin-chart-pivot-table/package.json, plugins/legacy-plugin-chart-pivot-table/src/controlPanel.js, plugins/legacy-plugin-chart-pivot-table/src/index.js
🏆 Enhancements
Adds the pivot table's control panel
=> feat(plugin-chart-pivot-table): add control panel

plugins/legacy-plugin-chart-rose/package.json, plugins/legacy-plugin-chart-rose/src/controlPanel.jsx, plugins/legacy-plugin-chart-rose/src/index.js
🏆 Enhancements
Adds control panel for the rose chart
=> feat(plugin-chart-rose): add rose chart controls

plugins/preset-chart-xy/package.json, plugins/preset-chart-xy/src/BoxPlot/controlPanel.ts, plugins/preset-chart-xy/src/BoxPlot/index.ts, plugins/preset-chart-xy/src/BoxPlot/legacy/index.ts
Updates controls for both the legacy boxplot and the updated one.
=> feat(plugin-chart-boxplot): add control panel

packages/superset-ui-style/src/index.ts
🏆 Enhancements
Adding a few styles to the superset theme object, just to fiddle around with in other packages
🐛 Bug Fix
🏠 Internal
=> feat(style): adding typographic variables to theme

lerna.json
🏆 Enhancements
🐛 Bug Fix
running `yarn ci:create-patch-version` would fail due to commitlint. This removes the scope, based on @kristw's suggestion 🍻. Once this is merged, I'll run it and find out for sure!
🏠 Internal
=> build: resolving lerna commitlint/scoping issue

plugins/legacy-plugin-chart-chord/package.json, plugins/legacy-plugin-chart-chord/src/controlPanel.js, plugins/legacy-plugin-chart-chord/src/index.js
=> feat(legacy-plugin-chart-chord): control panel

plugins/plugin-chart-word-cloud/src/legacyPlugin/transformProps.ts, plugins/plugin-chart-word-cloud/src/legacyPlugin/types.ts, plugins/plugin-chart-word-cloud/test/legacyPlugin/transformProps.test.ts
🏆 Enhancements
For backward compatibility
=> feat(plugin-chart-word-cloud): allow minimum size

plugins/legacy-plugin-chart-iframe/src/controlPanel.js
Little baby with unimaginable power. The Jack-Jack of control panels.
=> feat(legacy-plugin-chart-iframe): control panel

plugins/legacy-plugin-chart-horizon/package.json, plugins/legacy-plugin-chart-horizon/src/controlPanel.js, plugins/legacy-plugin-chart-horizon/src/index.js
=> feat(legacy-plugin-chart-horizon): control panel

plugins/legacy-plugin-chart-histogram/package.json, plugins/legacy-plugin-chart-histogram/src/controlPanel.js, plugins/legacy-plugin-chart-histogram/src/index.js
=> feat(legacy-plugin-chart-histogram): control panel

plugins/legacy-plugin-chart-force-directed/package.json, plugins/legacy-plugin-chart-force-directed/src/controlPanel.js, plugins/legacy-plugin-chart-force-directed/src/index.js
=> feat(legacy-plugin-chart-force-directed): control panel

plugins/legacy-plugin-chart-heatmap/package.json, plugins/legacy-plugin-chart-heatmap/src/controlPanel.js, plugins/legacy-plugin-chart-heatmap/src/index.js
heatmap control panel migrated
=> feat(legacy-plugin-chart-heatmap): control panel

temporary-plugins/hold-potentially-deprecate/superset-ui-legacy-plugin-chart-event-flow/package.json, temporary-plugins/hold-potentially-deprecate/superset-ui-legacy-plugin-chart-event-flow/src/controlPanel.jsx, temporary-plugins/hold-potentially-deprecate/superset-ui-legacy-plugin-chart-event-flow/src/index.js
Perhaps not the most important one, but, well, there it is.
=> feat(legacy-plugin-chart-event-flow): control panel

plugins/legacy-plugin-chart-table/package.json, plugins/legacy-plugin-chart-table/src/controlPanel.tsx, plugins/legacy-plugin-chart-table/src/index.ts
🏆 Enhancements
Add controls to superset ui for table
🐛 Bug Fix
🏠 Internal
=> chore: so 514 tablechart plugin controls migration

plugins/legacy-plugin-chart-parallel-coordinates/package.json, plugins/legacy-plugin-chart-parallel-coordinates/src/controlPanel.ts, plugins/legacy-plugin-chart-parallel-coordinates/src/index.js
🏆 Enhancements
Add control to parallel coordinates chart
🐛 Bug Fix
🏠 Internal
=> feat(legacy-plugin-chart-parallel-coordinates): add control panels

plugins/legacy-preset-chart-big-number/src/BigNumber/BigNumber.tsx
🏆 Enhancements
🐛 Bug Fix
Somehow a missing bracket slipped through the cracks. This fixes that and cleans up some other linty business. I'll try to open a PR soon to catch more of these kind of things reliably.
🏠 Internal
=> fix: missing bracket, little linty things

plugins/legacy-plugin-chart-paired-t-test/package.json, plugins/legacy-plugin-chart-paired-t-test/src/controlPanel.ts, plugins/legacy-plugin-chart-paired-t-test/src/index.js
🏆 Enhancements
Add paired t test controls to chart.
🐛 Bug Fix
🏠 Internal
=> chore: paired t test chart plugin control migration

plugins/legacy-plugin-chart-paired-t-test/src/index.js
🏆 Enhancements
🐛 Bug Fix
remove ts from import as it cause error on superset
🏠 Internal
=> fix(legacy-plugin-chart-paired-t-test): remove ts from import

plugins/legacy-plugin-chart-country-map/package.json, plugins/legacy-plugin-chart-country-map/src/controlPanel.ts, plugins/legacy-plugin-chart-country-map/src/index.js
🏆 Enhancements
Add controls to chart
=> chore(legacy-plugin-chart-country-map): add controls to chart

plugins/plugin-chart-choropleth-map/package.json, plugins/plugin-chart-choropleth-map/src/chart/ChoroplethMap.tsx, plugins/plugin-chart-choropleth-map/src/chart/components.ts, yarn.lock
**NOTE: This is merging into a feature branch, not `master`, and will have subsequent PRs into the feature branch until completion.**
* Create `plugin-chart-choropleth-map` to replace the `country-map` and `world-map` charts.
* Allow zooming and panning with mini-map
* Encoding
* Tooltip
=> feat(plugin-chart-choropleth-map): add zooming

packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-choropleth-map/Stories.tsx, plugins/plugin-chart-choropleth-map/package.json, plugins/plugin-chart-choropleth-map/src/chart/ChoroplethMap.tsx, plugins/plugin-chart-choropleth-map/src/chart/Encoder.ts, plugins/plugin-chart-choropleth-map/src/chart/MapMetadata.ts, plugins/plugin-chart-choropleth-map/src/chart/MapTooltip.tsx, yarn.lock
**NOTE: This is merging into a feature branch, not `master`, and will have subsequent PRs into the feature branch until completion.**
* Create `plugin-chart-choropleth-map` to replace the `country-map` and `world-map` charts.
Support tooltip
=> feat(plugin-chart-choropleth-map): add tooltip

packages/superset-ui-chart/src/clients/ChartClient.ts, packages/superset-ui-chart/test/clients/ChartClient.test.ts
🐛 Bug Fix
Update according to the new endpoints.
=> feat(chart): adjust chartclient to point to new endpoints

packages/superset-ui-demo/.storybook/storybook.css, packages/superset-ui-demo/package.json, packages/superset-ui-demo/storybook/shared/components/ResizableChartDemo.tsx, packages/superset-ui-demo/storybook/shared/components/ResizablePanel.tsx, packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-table/TableStories.tsx, packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-word-cloud/Stories.tsx, packages/superset-ui-demo/storybook/stories/superset-ui-chart/SuperChartStories.tsx, yarn.lock
🏆 Enhancements
Make chart demos resizable
[Test URL](https://superset-ui-git-fork-ktmud-resizable-demo.superset.now.sh/?path=/story/core-packages-superset-ui-chart--resizable)
=> feat(demo): add helpers for resizable chart demo

packages/superset-ui-query/src/api/legacy/fetchExploreJson.ts, packages/superset-ui-query/src/api/legacy/getDatasourceMetadata.ts, packages/superset-ui-query/src/api/legacy/getFormData.ts, packages/superset-ui-query/src/api/legacy/index.ts, packages/superset-ui-query/src/api/types.ts, packages/superset-ui-query/src/api/v1/index.ts, packages/superset-ui-query/src/api/v1/postChartData.ts, packages/superset-ui-query/src/index.ts, packages/superset-ui-query/test/api/fixtures/constants.ts, packages/superset-ui-query/test/api/legacy/fetchExploreJson.test.ts, packages/superset-ui-query/test/api/legacy/getDatasourceMetadata.test.ts, packages/superset-ui-query/test/api/legacy/getFormData.test.ts, packages/superset-ui-query/test/api/setupClientForTest.ts, packages/superset-ui-query/test/api/v1/postChartData.test.ts
🏆 Enhancements
* Add `getFormData()` and `getDatasourceMetadata()` functions.
* Export the API calls wrapped in objects `ApiLegacy.XXX` and `ApiV1.XXX`
* Refactor tests
=> feat(query): add more query wrappers

package.json, packages/superset-ui-chart/test/models/ChartPlugin.test.tsx, packages/superset-ui-query/src/buildQueryContext.ts, packages/superset-ui-query/src/buildQueryObject.ts, packages/superset-ui-query/src/types/Query.ts, packages/superset-ui-query/src/types/QueryFormData.ts, packages/superset-ui-query/test/buildQueryContext.test.ts, packages/superset-ui-query/test/buildQueryObject.test.ts, packages/superset-ui-query/test/processGroupby.test.ts
🏆 Enhancements
Add new result and offset fields to `QueryContext` and `QueryObject`.
=> feat(query): add new fields to QueryContext and QueryObject

packages/superset-ui-control-utils/package.json, packages/superset-ui-control-utils/src/MetricOption.tsx, packages/superset-ui-control-utils/src/index.ts, packages/superset-ui-control-utils/test/components/ColumnOption.test.tsx, packages/superset-ui-control-utils/test/components/ColumnTypeLabel.test.tsx, packages/superset-ui-control-utils/test/components/InfoTooltipWithTrigger.test.tsx, packages/superset-ui-control-utils/test/components/MetricOption.test.tsx
🏆 Enhancements
Add MetricOptions to control-utils
🐛 Bug Fix
🏠 Internal
=> chore(superset-ui-control-uitils): add MetricOption and dependencies to control utils

packages/superset-ui-control-utils/package.json, packages/superset-ui-control-utils/src/ColumnOption.tsx, packages/superset-ui-control-utils/src/index.ts, packages/superset-ui-control-utils/src/shared-controls.tsx, packages/superset-ui-control-utils/src/types.ts, plugins/legacy-plugin-chart-table/src/controlPanel.tsx, plugins/legacy-preset-chart-big-number/src/BigNumber/controlPanel.tsx, plugins/legacy-preset-chart-big-number/src/sharedControls.ts
🏆 Enhancements
Refactor typing in `control-utils` to be more specific.
Will also add typing for control sections config.
cc @rusackas @pkdotson @suddjian
=> feat(control-utils): better typing for control configs

packages/superset-ui-chart-composition/package.json, packages/superset-ui-chart/package.json, plugins/legacy-plugin-chart-table/package.json, plugins/plugin-chart-word-cloud/package.json, temporary-plugins/package.json, temporary-plugins/superset-ui-plugins-demo/package.json, yarn.lock
=> chore: upgrade @types/react

packages/superset-ui-style/src/index.ts
=> feat(style): add opacity and zIndex variables to theme

plugins/legacy-plugin-chart-heatmap/src/controlPanel.js, plugins/legacy-preset-chart-nvd3/src/LineMulti/controlPanel.ts
🏆 Enhancements
Just cleaning up a couple of controlOverrides that looked out of place. 
🐛 Bug Fix
🏠 Internal
=> chore: Cleaning up control overrides

packages/superset-ui-chart-composition/package.json, packages/superset-ui-chart/package.json, packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/testData.ts, plugins/legacy-plugin-chart-time-table/package.json, plugins/plugin-chart-choropleth-map/package.json, plugins/plugin-chart-table/package.json, plugins/plugin-chart-table/src/TableChart.tsx, plugins/plugin-chart-table/test/TableChart.test.tsx, plugins/plugin-chart-table/test/testData.ts, plugins/plugin-chart-word-cloud/package.json, scripts/build.js, temporary-plugins/package.json, temporary-plugins/superset-ui-plugins-demo/package.json, yarn.lock
=> fix(plugin-chart-table): value undefined when table name has dot

packages/superset-ui-core/src/query/api/legacy/fetchExploreJson.ts, packages/superset-ui-core/test/query/api/legacy/fetchExploreJson.test.ts
🏠 Internal
Make GET request work for fetchExploreJson, closes #668
Also updated the unit test.
cc @slicejacob
=> feat: make GET request work for fetchExploreJson, closes #668

plugins/legacy-preset-chart-nvd3/src/LineMulti/LineMulti.jsx
🏆 Enhancements
🐛 Bug Fix
see https://github.com/apache/incubator-superset/issues/10641
🏠 Internal
=> fix: update lineMulti when queryData changes

plugins/legacy-plugin-chart-partition/src/controlPanel.jsx, plugins/legacy-plugin-chart-rose/src/controlPanel.jsx, plugins/legacy-preset-chart-nvd3/src/NVD3Controls.tsx
🏆 Enhancements
Seems like there are a bunch of files with the same controls as https://github.com/apache/incubator-superset/pull/11294, so i'm making the changes there throughout superset-ui
to: @pkdotson @ktmud @kristw
=> feat: update time_compare description and choices

packages/superset-ui-core/src/query/types/AnnotationLayer.ts, plugins/plugin-chart-echarts/package.json, plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx, plugins/plugin-chart-echarts/src/Timeseries/index.ts, plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts, plugins/plugin-chart-echarts/src/utils/annotation.ts, plugins/plugin-chart-echarts/test/Timeseries/transformProps.test.ts, plugins/plugin-chart-echarts/test/utils/annotation.test.ts, yarn.lock
🏆 Enhancements
Add initial support for annotation layers to ECharts time-series chart by implementing the formula annotation layer. This has feature parity with the current NVD3 formula annotation layer. Event, interval and time-series annotations to follow later.
=> feat(plugin-chart-echarts): add support for formula annotations

yarn.lock
Run `yarn install` to bump packages.
=> chore: bump yarn.lock

packages/superset-ui-chart-controls/src/components/InfoTooltipWithTrigger.tsx, packages/superset-ui-chart-controls/src/shared-controls/index.tsx, packages/superset-ui-chart-controls/src/types.ts, yarn.lock
After [recent changes](https://github.com/apache/incubator-superset/pull/11435) to chart controls in Superset, some typing
has become obsolete. Let's clean it up.
🏠 Internal
=> chore(chart-controls): clean up typing

packages/superset-ui-core/package.json, packages/superset-ui-core/src/query/api/v1/makeApi.ts, packages/superset-ui-core/test/query/api/v1/makeApi.test.ts
🏆 Enhancements
Adds `rison` type to makeApi util
🐛 Bug Fix
🏠 Internal
=> feat: add rison request type to makeApi

packages/superset-ui-chart-controls/src/sections.tsx, packages/superset-ui-chart-controls/src/types.ts, packages/superset-ui-core/src/color/CategoricalColorScale.ts, packages/superset-ui-core/src/color/SequentialScheme.ts, plugins/legacy-plugin-chart-calendar/src/controlPanel.js, plugins/legacy-plugin-chart-country-map/src/controlPanel.ts, plugins/legacy-plugin-chart-event-flow/src/controlPanel.tsx, plugins/legacy-plugin-chart-force-directed/src/controlPanel.js, plugins/legacy-plugin-chart-heatmap/src/controlPanel.js, plugins/legacy-plugin-chart-histogram/src/controlPanel.js, plugins/legacy-plugin-chart-paired-t-test/src/controlPanel.ts, plugins/legacy-plugin-chart-partition/src/controlPanel.jsx, plugins/legacy-plugin-chart-treemap/src/controlPanel.js, plugins/legacy-preset-chart-nvd3/src/Area/controlPanel.ts, plugins/legacy-preset-chart-nvd3/src/Bubble/controlPanel.ts, plugins/legacy-preset-chart-nvd3/src/LineMulti/controlPanel.ts
🏆 Enhancements
Takes advantage of tweaks to `tabOverride` in control layouts from https://github.com/apache/incubator-superset/pull/11708
I'll post screenshots inline with code comments below, so it's not quite so overwhelming in the description.
🐛 Bug Fix
🏠 Internal
=> refactor: Relocating/renaming various chart controls

packages/superset-ui-demo/package.json, packages/superset-ui-demo/storybook/stories/plugins/plugin-filter-antd/Select/Stories.tsx, plugins/plugin-filter-antd/src/Select/AntdSelectFilter.tsx, plugins/plugin-filter-antd/src/Select/transformProps.ts
🐛 Bug Fix
Add AntD CSS import to storybook:
🏆 Enhancements
Add boolean knobs for multiple and inverse selection props and implement action hook to show selected values.
Knobs:
Actions:
=> fix(demo): add antd css and implement action hook on select filter story

.github/workflows/chromatic.yml, package.json, packages/superset-ui-demo/package.json, yarn.lock
🏆 Enhancements
Add chromatic CI step to capture storybook screenshots for review.
=> ci: add chromatic visual testing step

plugins/legacy-plugin-chart-histogram/src/Histogram.jsx, plugins/legacy-plugin-chart-histogram/src/WithLegend.jsx
🐛 Bug Fix
Fixes superset-frontend issue: 11543
Before:
After:
=> fix(legacy-plugin-chart-histogram): fixes legend overflow

packages/superset-ui-core/package.json, packages/superset-ui-core/src/utils/index.ts, packages/superset-ui-core/src/utils/random.ts, packages/superset-ui-core/test/utils/random.test.ts, packages/superset-ui-demo/package.json, packages/superset-ui-demo/storybook/stories/plugins/legacy-preset-chart-nvd3/DistBar/stories/manyBars.tsx, packages/superset-ui-demo/storybook/stories/plugins/preset-chart-xy/Line/stories/missing.tsx, plugins/plugin-chart-word-cloud/src/chart/WordCloud.tsx, temporary-plugins/hold-potentially-deprecate/superset-ui-legacy-plugin-chart-word-cloud/src/WordCloud.js, yarn.lock
🏆 Enhancements
🏠 Internal
Thanks to Chromatic added by @nytai , we now have screenshot testing for free. Some tests uses randomly generated data which are unstable in each run. Let's make the tests deterministic by using seeded random numbers.
=> test: use stable random for stories

packages/superset-ui-demo/storybook/shared/components/createQueryStory.tsx, packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-choropleth-map/Stories.tsx, packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/birthNames.json, packages/superset-ui-demo/storybook/stories/superset-ui-connection/ConnectionStories.tsx
🏠 Internal
Follow up with #861 
Enable stable tests for more stories.
=> test: disable Chromatic for VerifyCORS

packages/superset-ui-core/src/query/processExtraFormData.ts, packages/superset-ui-core/test/query/processExtraFormData.test.ts
🐛 Bug Fix
Fixes https://github.com/apache/incubator-superset/issues/12266
CC: @villebro @rusackas
=> fix(core): handle missing where in appendExtraFormData

.github/workflows/chromatic.yml, .github/workflows/ci.yml
🏆 Enhancements
Reading up on how `pull_request_target` works, https://securitylab.github.com/research/github-actions-preventing-pwn-requests, this is the correct way to run things.
🐛 Bug Fix
🏠 Internal
=> ci: switch chromatic action to workflow_run

plugins/legacy-preset-chart-nvd3/src/NVD3Controls.tsx
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> chore: update layout control for rolling window

plugins/legacy-plugin-chart-partition/src/controlPanel.tsx, plugins/legacy-plugin-chart-rose/src/controlPanel.tsx, plugins/legacy-preset-chart-big-number/src/BigNumber/controlPanel.tsx, plugins/legacy-preset-chart-nvd3/src/NVD3Controls.tsx
🏆 Enhancements
More control panels needed to be updated for rolling window. 
🐛 Bug Fix
🏠 Internal
=> chore: Update controls for rolling window

plugins/legacy-preset-chart-big-number/src/BigNumber/controlPanel.tsx
🏆 Enhancements
update big number control options.
🐛 Bug Fix
🏠 Internal
=> chore: Update big number control options

plugins/legacy-preset-chart-nvd3/src/ReactNVD3.jsx
BEFORE
AFTER
Fix: https://github.com/apache/superset/issues/11859
=> fix: subject Add width auto and enable scroll for big charts

.eslintrc.js, packages/superset-ui-chart-controls/src/index.ts, packages/superset-ui-chart-controls/src/shared-controls/index.tsx, packages/superset-ui-chart-controls/src/types.ts, plugins/plugin-chart-echarts/package.json, plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx, plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts, plugins/plugin-chart-echarts/src/Timeseries/types.ts
Add xAxis label format && showMin and showMax labels for timeseries chart
=> feat(plugin-chart-echarts): Add xAxis label format && showMin and showMax labels

plugins/legacy-plugin-chart-heatmap/src/controlPanel.ts, plugins/legacy-plugin-chart-histogram/src/Histogram.jsx, plugins/legacy-plugin-chart-histogram/src/controlPanel.ts, plugins/legacy-plugin-chart-histogram/src/transformProps.js
Add legend option
related to: https://github.com/apache-superset/superset-roadmap/issues/92
=> feat(legacy-plugin-chart-histogram): subject Add legend option to histogram chart

plugins/plugin-chart-word-cloud/src/plugin/buildQuery.ts, plugins/plugin-chart-word-cloud/src/plugin/controlPanel.ts
Add order by desc on metric for plugin-chart-word-cloud
https://user-images.githubusercontent.com/8277264/107015679-b2164200-67a5-11eb-8132-ed5cd10bf017.mp4
https://user-images.githubusercontent.com/8277264/107020860-0c1a0600-67ac-11eb-8d60-38d3f503ed8b.mp4
=> feat(plugin-chart-word-cloud): subject Add order by desc on metric

plugins/plugin-chart-echarts/src/Pie/buildQuery.ts, plugins/plugin-chart-echarts/src/Pie/controlPanel.tsx
https://user-images.githubusercontent.com/8277264/107389461-75c54780-6aff-11eb-8ca3-4fdd03837b37.mp4
=> feat(plugin-chart-echarts): subject add sort by metric for Pie Chart

packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx, packages/superset-ui-chart-controls/src/shared-controls/index.tsx, packages/superset-ui-chart-controls/src/types.ts
🏆 Enhancements
Based on https://github.com/apache-superset/superset-ui/pull/967 by @zhaoyongjie 
CC: @villebro @junlincc
=> feat: implement drag and drop filters controls

packages/superset-ui-core/src/utils/featureFlags.ts
=> fix: incorporating ScheduleQueries into featureFlags

.github/workflows/ci.yml, .github/workflows/codecov.sh
In light of recent issues with the remote codecov bash script, this PR downloads the script locally and migrates CI actions to utilize the local script instead.
=> fix: Adding codecov script locally

plugins/plugin-chart-echarts/src/Gauge/controlPanel.tsx
🏆 Enhancements
Add time section for gauge chart.
=> chore(plugin-chart-echarts): add time section for gauge chart

plugins/plugin-chart-table/src/buildQuery.ts
🏆 Enhancements
Required: https://github.com/apache/superset/pull/14217
Add group by filter for table
https://user-images.githubusercontent.com/56388545/115140017-c98f6800-a03d-11eb-9fe7-c96f1edc96f9.mov
=> feat(table): groupby filter

docs/debugging.md
Remove references to incubator-superset
to: @ktmud
=> chore: update documentation

packages/superset-ui-core/src/style/index.ts
🏆 Enhancements
🐛 Bug Fix
Follows up on https://github.com/apache-superset/superset-ui/pull/1073
Slightly different means of importing/exporting Emotion modules, in hopes of fixing this annoyance:
🏠 Internal
=> fix: further dialing-in of Emotion imports/exports

plugins/plugin-chart-echarts/src/Funnel/controlPanel.tsx, plugins/plugin-chart-echarts/src/Graph/controlPanel.tsx, plugins/plugin-chart-echarts/src/MixedTimeseries/controlPanel.tsx, plugins/plugin-chart-echarts/src/Pie/controlPanel.tsx, plugins/plugin-chart-echarts/src/Radar/controlPanel.tsx, plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx, plugins/plugin-chart-echarts/src/controls.tsx
🏆 Enhancements
Show/hide controls if they are dependent on a parent control.
https://user-images.githubusercontent.com/33317356/117416895-7fa1ef80-af22-11eb-9435-16dd209894d0.mp4
https://user-images.githubusercontent.com/33317356/117416970-90eafc00-af22-11eb-8e4f-09c21ad3d480.mp4
=> feat(plugin-chart-echarts): hide/show dependent controls

packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
🐛 Bug Fix
Fixes https://github.com/apache/superset/issues/14654.
@villebro @rusackas
=> fix: fixes metric control when changing viz type to tree chart

plugins/plugin-chart-echarts/src/Treemap/buildQuery.ts, plugins/plugin-chart-echarts/src/Treemap/controlPanel.tsx, plugins/plugin-chart-echarts/src/Treemap/transformProps.ts, plugins/plugin-chart-echarts/src/Treemap/types.ts, plugins/plugin-chart-echarts/test/Treemap/transformProps.test.ts
🏆 Enhancements
- contribution mode show % of parent in the tooltip
- change upper label color to white
- remove label position control
- support only one metric
=> feat(plugin-chart-echarts): Treemap improvements

packages/superset-ui-core/src/chart/models/ChartMetadata.ts
🏆 Enhancements
Supports new metadata fields to be used for the chart gallery. I was gonna try to build some kind of mechanism for a new json metadata file, but decided that wasn't really necessary for now.
🐛 Bug Fix
🏠 Internal
=> chore(core): add new fields to metadata class

plugins/plugin-chart-echarts/src/Treemap/constants.ts, plugins/plugin-chart-echarts/src/Treemap/transformProps.ts
🐛 Bug Fix
related PR: https://github.com/apache/superset/issues/14962#issue-910074072
=> fix(plugin-chart-echarts): [treemap v2] fix the section color and disabling the zoom on the explore

plugins/plugin-chart-echarts/src/Radar/controlPanel.tsx
🐛 Bug Fix
fix https://github.com/apache/superset/issues/15266
=> fix(plugin-chart-echarts): radar legend control is duplicated

packages/superset-ui-core/src/chart/components/NoResultsComponent.tsx, packages/superset-ui-core/test/chart/components/NoResultsComponent.test.tsx
🏆 Enhancements
Fix missing translation on NoResultsComponent.
=> fix(core): missing translation

plugins/plugin-chart-echarts/src/Tree/transformProps.ts
🏆 Enhancements
change treegraph node seperater "." to triangle.
link to https://github.com/apache/superset/projects/13#card-61096602
=> fix(plugin-chart-echarts): tree graph tooltip polish

plugins/plugin-chart-table/src/i18n.ts
🐛 Bug Fix
Fix wrong translation.
=> fix(plugin-chart-table): chinesee translation improve

plugins/legacy-preset-chart-big-number/src/BigNumber/index.ts, plugins/legacy-preset-chart-nvd3/src/TimePivot/index.js
🏆 Enhancements
🐛 Bug Fix
couple small fixes needed after pulling recent changes into superset
🏠 Internal
=> chore: tweaking plugin metadata again

plugins/legacy-plugin-chart-pivot-table/src/index.js, plugins/legacy-plugin-chart-time-table/src/index.ts, plugins/legacy-preset-chart-nvd3/src/Compare/index.js, plugins/legacy-preset-chart-nvd3/src/LineMulti/index.js, plugins/plugin-chart-echarts/src/Radar/index.ts, plugins/plugin-chart-echarts/src/Timeseries/index.ts
🏆 Enhancements
better descriptions
🐛 Bug Fix
🏠 Internal
=> chore: add/edit plugin descriptions

plugins/plugin-chart-echarts/src/Radar/EchartsRadar.tsx, plugins/plugin-chart-echarts/src/Radar/transformProps.ts, plugins/plugin-chart-echarts/src/Treemap/constants.ts, plugins/plugin-chart-echarts/src/Treemap/transformProps.ts, plugins/plugin-chart-echarts/src/constants.ts
🏆 Enhancements
single select by default and improve UI when applying x-filtering.
https://user-images.githubusercontent.com/11830681/124386101-4233c580-dd0b-11eb-8916-7c69316bf83e.mov
https://user-images.githubusercontent.com/11830681/124386045-e9642d00-dd0a-11eb-9783-6eaed55088f1.mov
=> feat(plugin-chart-echarts): x-filtering improvement in radar chart

plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx
same as the pull-request title.
=> fix: remove console.log from timeseries chart

plugins/plugin-chart-echarts/src/Gauge/EchartsGauge.tsx, plugins/plugin-chart-echarts/src/Gauge/constants.ts, plugins/plugin-chart-echarts/src/Gauge/controlPanel.tsx, plugins/plugin-chart-echarts/src/Gauge/index.ts, plugins/plugin-chart-echarts/src/Gauge/transformProps.ts, plugins/plugin-chart-echarts/src/Gauge/types.ts, plugins/plugin-chart-echarts/src/types.ts
🏆 Enhancements
https://user-images.githubusercontent.com/11830681/124379511-1eac5300-dcea-11eb-8c1e-970719cd38e9.mov
=> feat(plugin-chart-echarts): add  x-filtering in gauge chart

plugins/plugin-chart-echarts/src/BoxPlot/EchartsBoxPlot.tsx, plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
🏆 Enhancements
https://user-images.githubusercontent.com/11830681/125181604-0633bf80-e239-11eb-8901-86052d3a358f.mov
https://user-images.githubusercontent.com/11830681/125181606-0b910a00-e239-11eb-83ab-923a31c66893.mov
=> fix(plugin-chart-echarts): single select in boxPlot x-filtering

packages/superset-ui-chart-controls/src/types.ts, packages/superset-ui-chart-controls/src/utils/getColorFormatters.ts, packages/superset-ui-chart-controls/src/utils/index.ts, packages/superset-ui-chart-controls/test/utils/getColorFormatters.test.ts
This PR implements utils functions and types necessary for adding conditional formatting to Pivot Table v2 and Table charts.
See https://github.com/apache/superset/pull/15651 for final result
=> feat(chart-controls): implement color formatters utils

plugins/plugin-chart-table/src/TableChart.tsx, plugins/plugin-chart-table/src/transformProps.ts
🐛 Bug Fix
This PR fixes the problem with table clearing x-filtering highlighting.
https://user-images.githubusercontent.com/11830681/125651817-6ca0280d-2bef-4d2a-915c-a9b150939ab3.mov
https://user-images.githubusercontent.com/11830681/125651829-f159ae27-399f-4d38-9de8-249d75c9d750.mov
=> fix(plugin-chart-table): table clear x-filtering highlighting

plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
🏆 Enhancements
https://user-images.githubusercontent.com/11830681/125649358-bb3b95e6-f9c0-4a0d-8f84-0fdcadf4eade.mov
https://user-images.githubusercontent.com/11830681/125649377-0c44cfbe-6212-487a-90ff-03d2b16e4d36.mov
=> feat(plugin-chart-pivot-table): pivot table x-filtering supports single select

plugins/legacy-plugin-chart-heatmap/src/index.js, plugins/plugin-chart-word-cloud/src/plugin/index.ts
🏆 Enhancements
changed `popularity` to `Highly-used` in heatmap and wordcloud viz
=> chore: change Popularity to Highly-used

plugins/plugin-chart-table/src/TableChart.tsx
🏆 Enhancements
https://user-images.githubusercontent.com/11830681/125647071-0b284574-5ae9-4821-a586-561001d2d8e3.mov
https://user-images.githubusercontent.com/11830681/125647045-c8c3a122-de96-43d2-8336-2b1dbc3fdb07.mov
=> feat(plugin-chart-table): table x-filtering supports single select

packages/superset-ui-core/src/utils/featureFlags.ts
Add UX_BETA feature flag for various UX improvements. Prerequisite for https://github.com/apache/superset/pull/15798
=> chore(core): add UX_BETA feature flag

plugins/plugin-chart-pivot-table/package.json, plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx, plugins/plugin-chart-pivot-table/src/plugin/controlPanel.ts, plugins/plugin-chart-pivot-table/src/types.ts
List of changes:
1. Header and totals row are sticky
2. Added aggregation function name to "Total" label
3. Changed labels from "Totals" to "Total"
4. Moved "Show total" checkboxes to Data tab
5. "Show total" checkboxes are unchecked by default
https://user-images.githubusercontent.com/15073128/126642403-c2f4bc96-77e9-49e4-8a2c-fa033df06ff6.mov
CC: @junlincc @rusackas
=> feat(plugin-chart-pivot-table): multiple improvements

plugins/legacy-plugin-chart-heatmap/src/index.js, plugins/legacy-plugin-chart-map-box/src/index.js, plugins/plugin-chart-word-cloud/src/plugin/index.ts
🏆 Enhancements
related： https://github.com/apache/superset/issues/15720
=> chore: three charts to the correct tags

packages/superset-ui-chart-controls/src/sections.tsx, packages/superset-ui-chart-controls/src/utils/D3Formatting.ts, plugins/legacy-plugin-chart-country-map/src/controlPanel.ts, plugins/legacy-plugin-chart-paired-t-test/src/index.js, plugins/legacy-plugin-chart-parallel-coordinates/src/index.js, plugins/plugin-chart-echarts/src/Gauge/controlPanel.tsx, plugins/plugin-chart-echarts/src/MixedTimeseries/controlPanel.tsx, plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
=> chore: add translation for description

plugins/legacy-plugin-chart-sankey/src/index.js, plugins/legacy-plugin-chart-treemap/src/index.js, plugins/legacy-preset-chart-nvd3/src/DistBar/index.js
🏆 Enhancements
Distribution is a category and a tag,  we just keep the category.
=> chore: only keey Distribution category

packages/superset-ui-core/src/utils/featureFlags.ts
🏠 Internal
Adds a new feature flag to the feature flag list
=> chore: add feature flag

plugins/plugin-chart-pivot-table/src/plugin/buildQuery.ts
Adds "Sort by" metric's values to south data table (below the chart).
CC @junlincc
=> feat(plugin-chart-pivot-table): add sort by result to data pane

plugins/legacy-plugin-chart-pivot-table/src/index.js, plugins/legacy-plugin-chart-treemap/src/index.js, plugins/plugin-chart-echarts/src/Treemap/index.ts, plugins/plugin-chart-pivot-table/src/plugin/index.ts
=> chore: remove V2 and add Deprecated

plugins/plugin-chart-echarts/src/Pie/index.ts, plugins/plugin-chart-echarts/src/Radar/index.ts
=> chore: add echarts tag for pie and radar

CONTRIBUTING.md
Update the release instructions to be more in line with regular usage.
=> docs: update publishing instructions

packages/superset-ui-chart-controls/src/shared-controls/components/ColumnConfigControl/ColumnConfigControl.tsx, packages/superset-ui-chart-controls/src/shared-controls/components/ColumnConfigControl/constants.tsx, plugins/plugin-chart-table/src/TableChart.tsx, plugins/plugin-chart-table/src/controlPanel.tsx
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> feat(plugin-chart-table): added emit target name

plugins/plugin-chart-echarts/src/Timeseries/Area/controlPanel.tsx, plugins/plugin-chart-echarts/src/Timeseries/Area/index.ts, plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/index.ts, plugins/plugin-chart-echarts/src/Timeseries/Regular/Line/index.ts, plugins/plugin-chart-echarts/src/Timeseries/Regular/SmoothLine/index.ts, plugins/plugin-chart-echarts/src/Timeseries/Regular/controlPanel.tsx, plugins/plugin-chart-echarts/src/Timeseries/Step/controlPanel.tsx, plugins/plugin-chart-echarts/src/Timeseries/Step/index.ts, plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx, plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts, plugins/plugin-chart-echarts/src/Timeseries/transformers.ts, plugins/plugin-chart-echarts/src/Timeseries/types.ts, plugins/plugin-chart-echarts/src/controls.tsx
🏆 Enhancements
related to https://github.com/apache/superset/issues/16063
- Add a new control call `Show Value`. 
- Support show series values to all echarts timeseries chart.
Unstacked bars:
Stacked bars:
Unstacked area:
Stacked area:
=> feat(plugin-chart-echarts): Add support for series values to ECharts timeseries charts

plugins/legacy-plugin-chart-histogram/src/controlPanel.ts
🏆 Enhancements
Stacks and sorts Histogram controls to a better UI/UX. The proposed change targets a more uniform display of the information for the user and gives the controls more space to present the UI elements. The idea is also to avoid, as much as we can, the expansion of the controls section, preserving the available space for displaying the charts.
Before:
https://user-images.githubusercontent.com/70410625/128227414-724f4952-7953-477f-92bd-43e1f287a677.mov
After:
https://user-images.githubusercontent.com/70410625/128227492-a202cbdd-b088-47a5-8594-c6e739cd58ad.mov
=> chore: stacks and sorts Histogram controls

plugins/legacy-preset-chart-big-number/src/BigNumber/BigNumber.tsx, plugins/legacy-preset-chart-big-number/src/BigNumber/controlPanel.tsx, plugins/legacy-preset-chart-big-number/src/BigNumber/transformProps.ts, plugins/legacy-preset-chart-big-number/test/transformProps.test.ts
💔 Breaking Changes: No
🏆 Enhancements: add timestamp above the number in BigNumber chart(s)
📜 Documentation: NA
🐛 Bug Fix: NA
🏠 Internal: NA
=> feat(legacy-preset-chart-big-number): add timestamp above number

plugins/plugin-chart-table/src/index.ts
🏆 Enhancements
One plugin was missed in https://github.com/apache-superset/superset-ui/pull/1285
This PR catches that Tag and updates it. 
🐛 Bug Fix
🏠 Internal
=> chore: updating one metadata field

packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> chore: change ghost button text for dndcontrols

plugins/plugin-chart-echarts/src/MixedTimeseries/EchartsMixedTimeseries.tsx, plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts, plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx, plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts, plugins/plugin-chart-echarts/src/utils/prophet.ts, plugins/plugin-chart-echarts/src/utils/series.ts
🐛 Bug Fix
https://github.com/apache/superset/issues/16177
- Address all time series chart and mixd-timeseries chart
- Hovering on specific series will get highlighted.
https://user-images.githubusercontent.com/11830681/129236128-b7c8966d-0645-45f1-8c65-fa24da9c502f.mov
=> feat(plugin-chart-echarts): rich tooltip in ts chart supports scroll and highlighted

plugins/plugin-chart-pivot-table/README.md, plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
🏠 Internal
We reproduce the logic of the pivot table viz in Python to produce nice reports. I added a note that if the logic of the plugin changes we need to update the Python logic.
=> chore: add a note to the pivot plugin

plugins/plugin-chart-echarts/src/Timeseries/Regular/Scatter/controlPanel.tsx, plugins/plugin-chart-echarts/src/Timeseries/Regular/Scatter/index.ts
🏆 Enhancements
refer to https://github.com/apache/superset/issues/16342#issuecomment-902418851
=> fix(plugin-chart-echarts): [scatter-plot] remove contribution mode

packages/superset-ui-chart-controls/package.json, packages/superset-ui-core/package.json, packages/superset-ui-demo/package.json, yarn.lock
🏠 Internal
Move `@emotion/styled` to peer dependency to fix version conflict on `apache/superset`. Also bump other `@emotion` deps to match those in https://github.com/apache/superset/pull/16559
=> chore(core): move @emotion/styled to peer dependency

plugins/legacy-plugin-chart-pivot-table/package.json, plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
Reverts apache-superset/superset-ui#1339
Caused an error. Reverting while I investigate said error.
=> chore: Revert "chore: isolate the one actual jquery dependency"

plugins/plugin-chart-echarts/src/MixedTimeseries/buildQuery.ts
🏆 Enhancements
clean up codebase, no functional changes
=> chore: clean up mixed-timeseries chart

.github/dependabot.yml
🏆 Enhancements
do prettier for yaml file
=> chore: do prettier for yaml file

plugins/legacy-plugin-chart-map-box/package.json, plugins/legacy-plugin-chart-map-box/src/MapBox.jsx, plugins/legacy-plugin-chart-map-box/src/ScatterPlotGlowOverlay.jsx, yarn.lock
We barely use `immutable` in superset so let's remove it.
I have no clue how to test this. I'm hoping it's in the storybook
to: @ktmud @graceguo-supercat @nytai
=> chore: Remove immutable.js from map-box

plugins/legacy-preset-chart-nvd3/src/Bubble/controlPanel.ts
This pr add the y-axis bounds controls to the bubble chart. 
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> feat: add y-axis control to bubble chart

packages/superset-ui-core/test/query/buildQueryObject.test.ts, packages/superset-ui-core/test/query/extractTimegrain.test.ts, packages/superset-ui-core/test/query/types/AnnotationLayer.test.ts, packages/superset-ui-core/test/time-format/formatters/smartDateDetailed.test.ts, plugins/plugin-chart-echarts/src/index.ts, plugins/plugin-chart-echarts/src/types.ts, plugins/plugin-chart-echarts/test/utils/series.test.ts
🏠 Internal
tweak unittest to prepare monorepo
1. import from source code instead `lib`
2. fix flaky test
3. export variable used by Superset
=> chore: tweak unittest
