- .gitignore
- .travis.yml
- package.json
- packages/superset-ui-core/package.json
This is same as #2 but for master
@john-bodley @kristw
> [monorepo] add travis + codecov ✅

- packages/superset-ui-core/package.json
🐛 Bug Fix
- when using `@superset-ui/core` in a separate repo it fails due to the missing [`babel-runtime` dep](https://babeljs.io/docs/en/next/babel-runtime.html), which is simply a modular version of babel runtime helpers and is meant to reduce bundle size by pulling them out as a dep
@kristw @conglei
> [core] add missing babel-runtime dep

- .gitignore
- package.json
- packages/superset-ui-core/package.json
- packages/superset-ui-core/src/SupersetClient.js
- packages/superset-ui-core/src/callApi/callApi.js
- packages/superset-ui-core/src/callApi/callApiAndParseWithTimeout.js
- packages/superset-ui-core/src/callApi/parseResponse.js
- packages/superset-ui-core/test/SupersetClient.test.js
- packages/superset-ui-core/test/callApi/callApi.test.js
- packages/superset-ui-core/test/callApi/callApiAndParseWithTimeout.test.js
- packages/superset-ui-core/test/callApi/parseResponse.test.js
- packages/superset-ui-core/test/utils/throwIfCalled.js
🏆 Enhancements
- This adds a `parseMethod` argument to `parseResponse` in order to support both `json` (default) and `text` responses. This is needed to enable custom response parsing in some cases, for example `BigInt`s which was [added to Sqllab recently](https://github.com/apache/incubator-superset/pull/5829).
- Exposes this `parseMethod` as an optional argument to `SupersetClient.get()` and `.post()` calls.
🏠 Internal
- Bumps `@data-ui/build-config` to `0.0.14` which has a stricter `no-unused-args` eslint rule
- adds `.npmrc` to `.gitignore` for local publishing credentials
@kristw @conglei @mistercrunch
> [core] add `parseMethod`

- packages/superset-ui-core/package.json
- packages/superset-ui-core/src/SupersetClient.js
- packages/superset-ui-core/src/callApi/callApi.js
- packages/superset-ui-core/src/callApi/parseResponse.js
- packages/superset-ui-core/test/SupersetClient.test.js
- packages/superset-ui-core/test/callApi/callApi.test.js
- packages/superset-ui-core/test/callApi/parseResponse.test.js
🏆 Enhancements
- This PR adds support for `csrf_token=''` to `SupersetClient`, to support the case when the Superset Flask app sets `WTF_CSRF_ENABLED = False`. This is valid configuration and is used in e.g., cypress tests, and when this is set to `False`, the `superset/csrf_token` endpoint returns a `200` with an empty string. Without this support, Cypress tests fail when integrating `SupersetClient`.
🏠 Internal
- removes unneeded polyfill (used previously as another method for encoding `POST` payload form data)
- adds a test to ensure that `parseResponse` rejects when `response.ok=false`
@kristw @michellethomas @graceguo-supercat @conglei
> [core] support empty `CSRF` token

- packages/superset-ui-core/src/SupersetClient.js
🐛 Bug Fix
When configuring `host` and `protocol` in `SupersetClient`, it's convenient to use values from `window.location`. 
This PR updates the `config` for `protocol` from expecting values like e.g., `http` and `https` to mirror the format of `window.location.protocol`, which includes a colon: `http:` or `https:`
@kristw @conglei @mistercrunch
> [core][client] mirror `window.location.protocol` format in config

- .gitignore
- packages/superset-ui-core/README.md
- packages/superset-ui-core/package.json
- packages/superset-ui-core/src/SupersetClient.js
- packages/superset-ui-core/test/SupersetClient.test.js
🏆 Enhancements
Adds the ability to pass a `csrf` token at configuration time: 
`SupersetClient.configure({ csrfToken: 'my_token', ... })`
By enabling the user to pass a `csrfToken` at configuration time (which is possible within the Superset application where CSRF token is embedded within the HTML), we can remove an unnecessary auth request. This may be causing slight delays in requests in the Superset app and contributing to integration test flakiness.
@kristw @michellethomas @mistercrunch
> [SupersetClient] allow csrf token to be passed as configuration

- package.json
- packages/superset-ui-core/src/SupersetClient.js
🤦‍♂️ Bug Fix
Forgot to include `csrfToken`s passed in configuration in the headers sent with requests.
This time I actually linked the package and tested in the `Superset` app.
@kristw
> [SupersetClient] include csrfToken passed in configuration in headers

- .gitignore
- .npmrc
- .travis.yml
- package.json
- packages/superset-ui-core/.eslintrc
- packages/superset-ui-core/package.json
- packages/superset-ui-translation/package.json
🏠 Internal
With more packages coming, this PR 
- moves the build-config to the monorepo root `package.json` so that package creators don't have to deal with the boilerplate. This will help keep things consistent across packages, too. Note that currently this build config does _not_ support webpack or TS, but we can easily add support for that with `@beemo`. I tested locally with another test package and everything seems to work okay.
- adds a pre-commit hook to run prettier on any staged files ✨ 
- adds a `test:watch` script to support `jest --watch` mode. this isn't easy out of the box with `beemo` because `jest` runs in a subprocess so output is not piped to the command line, but the script provides a workaround
@kristw @xtinec
> [build-config] move to monorepo root

- packages/superset-ui-translation/README.md
- packages/superset-ui-translation/package.json
- packages/superset-ui-translation/src/Translator.js
- packages/superset-ui-translation/src/TranslatorSingleton.js
- packages/superset-ui-translation/src/index.js
- packages/superset-ui-translation/test/Translator.test.js
- packages/superset-ui-translation/test/TranslatorSingleton.test.js
- packages/superset-ui-translation/test/index.test.js
- packages/superset-ui-translation/test/languagePacks/zh.json
🏆 Enhancements
- Add `tn` (`translateWithNumber`) to `translation` module
- Remove `sprintf-js` because `jed` already comes with `sprintf`.
> Add tn / translateWithNumber

- packages/superset-ui-core/README.md
- packages/superset-ui-core/package.json
- packages/superset-ui-core/src/index.js
- packages/superset-ui-core/src/models/Plugin.js
- packages/superset-ui-core/src/models/Preset.js
- packages/superset-ui-core/src/models/Registry.js
- packages/superset-ui-core/src/utils/convertKeysToCamelCase.js
- packages/superset-ui-core/src/utils/isDefined.js
- packages/superset-ui-core/src/utils/isRequired.js
- packages/superset-ui-core/src/utils/makeSingleton.js
- packages/superset-ui-core/test/index.test.js
- packages/superset-ui-core/test/models/Plugin.test.js
- packages/superset-ui-core/test/models/Preset.test.js
- packages/superset-ui-core/test/models/Registry.test.js
- packages/superset-ui-core/test/utils/convertKeysToCamelCase.test.js
- packages/superset-ui-core/test/utils/isDefined.test.js
- packages/superset-ui-core/test/utils/isRequired.test.js
- packages/superset-ui-core/test/utils/makeSingleton.test.js
🏆 Enhancements
- Add several classes/utils migrated from `incubator-superset`
🏠 Internal
- Previous `@superset-ui/core` was renamed to `@superset-ui/connection`. The new `@superset-ui/core` will resume the version number. 
p.s. new package scaffolded with [generator-superset](https://github.com/apache-superset/generator-superset)
> Add new core modules from incubator-superset

- README.md
- packages/superset-ui-chart/README.md
- packages/superset-ui-chart/package.json
- packages/superset-ui-chart/src/index.js
- packages/superset-ui-chart/src/models/ChartMetadata.js
- packages/superset-ui-chart/src/models/ChartPlugin.js
- packages/superset-ui-chart/src/models/ChartProps.js
- packages/superset-ui-chart/src/registries/ChartBuildQueryRegistrySingleton.js
- packages/superset-ui-chart/src/registries/ChartComponentRegistrySingleton.js
- packages/superset-ui-chart/src/registries/ChartMetadataRegistrySingleton.js
- packages/superset-ui-chart/src/registries/ChartTransformPropsRegistrySingleton.js
- packages/superset-ui-chart/test/index.test.js
- packages/superset-ui-chart/test/models/ChartMetadata.test.js
- packages/superset-ui-chart/test/models/ChartPlugin.test.js
- packages/superset-ui-chart/test/models/ChartProps.test.js
🏆 Enhancements
- Migrate Chart registries and data structures from `incubator-superset`. 
- No new features. Only add unit tests to ensure 100% code coverage!
Note: Haven't moved `SuperChart` here yet. Will do that in a separate review.
> Add @superset-ui/chart with extract modules and additional unit tests

- packages/superset-ui-color/src/SequentialScheme.js
🐛 Bug Fix
The current code is using `Array(n).keys()` which requires `iterator` polyfill. Switch to plain old js for simplicity.
> Use simple js code to create range

- .travis.yml
- babel-transformer.js
- package.json
- packages/generator-superset/.gitattributes
- packages/generator-superset/README.md
- packages/generator-superset/generators/app/index.js
- packages/generator-superset/generators/package/index.js
- packages/generator-superset/generators/package/templates/README.md
- packages/generator-superset/generators/package/templates/package.json
- packages/generator-superset/generators/package/templates/src/index.js
- packages/generator-superset/generators/package/templates/test/index.js
- packages/generator-superset/package.json
- packages/generator-superset/test/app.test.js
- packages/generator-superset/test/package.test.js
🏆 Enhancements
- Add `generator-superset` package for scaffolding.
- This package will be published as `@superset-ui/generator-superset`.
- Update build script to skip `babel` tasks for `generator-superset`, as it is a `node` application.
- Use `jest` project configuration to separate `generator-superset` from others and run in `testEnvironment: "node"`. (Although that was not the real issue that demolished CI in the early attempts.)
The key thing to add to `yeoman` tests, which are not normally included even from official yeoman `generator-generator`, is to **change working directory back to original working directory after the test has completed.** `yeoman` tests switch to `tmp` directory and write files there. Usually this is fine for solo package. However, for a monorepo like this …
> Add generator-superset

- packages/superset-ui-core/src/index.js
- packages/superset-ui-core/src/models/ExtensibleFunction.js
- packages/superset-ui-core/test/index.test.js
- packages/superset-ui-core/test/models/ExtensibleFunction.test.js
🏆 Enhancements
Add `ExtensibleFunction` class, which was inspired by the need to have classes that are also functions. 
For example, `CategoricalColorScale` or `NumberFormatter` should be functions themselves. Currently `CategoricalColorScale` has an awkward `.toFunction()` that needs to be called to convert to function, and also error-prone if developer forgets to call `.toFunction()`. Current usage in Superset is similar to the example code below.
```js
const colorScale = new CategoricalColorScale(...).toFunction();
colorScale(someValue); // 'green'
```
Would be cleaner if we can call 
```js
const colorScale = new CategoricalColorScale(...);
colorScale(someValue); // 'green'
const format = new NumberFormatter('.2f');
format(100); // 100.00
```
I still want to keep …
> Add ExtensibleFunction class

- packages/superset-ui-color/src/CategoricalColorNamespace.js
- packages/superset-ui-color/src/ColorScheme.js
- packages/superset-ui-color/src/colorSchemes/categorical/airbnb.js
- packages/superset-ui-color/src/colorSchemes/categorical/d3.js
- packages/superset-ui-color/src/colorSchemes/categorical/google.js
- packages/superset-ui-color/src/colorSchemes/categorical/lyft.js
- packages/superset-ui-color/src/colorSchemes/sequential/common.js
- packages/superset-ui-color/src/colorSchemes/sequential/d3.js
- packages/superset-ui-color/test/CategoricalColorNameSpace.test.js
- packages/superset-ui-color/test/ColorScheme.test.js
- packages/superset-ui-color/test/SequentialScheme.test.js
- packages/superset-ui-demo/storybook/stories/superset-ui-color/RenderPalettes.jsx
BREAKING CHANGE: Rename ColorScheme field 'name' to 'id'
```js
// from
new CategoricalColorScheme({ name: 'rgb', label: 'rgb colors', colors: ['red', 'green', 'blue']});
// to
new CategoricalColorScheme({ id: 'rgb', label: 'rgb colors', colors: ['red', 'green', 'blue']});
```
This was inspired by recent discussion in `number-format` PR #31 that it is confusing to have both `name` and `label` and the field name should indicate a bit more uniqueness.
> Rename ColorScheme field 'name' to 'id'

- packages/superset-ui-number-format/src/NumberFormatterRegistry.js
- packages/superset-ui-number-format/src/formatters/D3NumberFormatter.js
- packages/superset-ui-number-format/test/formatters/D3NumberFormatter.test.js
fix: Rename `D3Formatter` to `D3NumberFormatter` to avoid ambiguity and naming collision with `D3TimeFormatter`. 
Not really breaking change because `@superset-ui/number-format` has not been published yet.
> Rename `D3Formatter` to `D3NumberFormatter`

- packages/superset-ui-chart/src/registries/ChartBuildQueryRegistrySingleton.js
- packages/superset-ui-chart/src/registries/ChartComponentRegistrySingleton.js
- packages/superset-ui-chart/src/registries/ChartMetadataRegistrySingleton.js
- packages/superset-ui-chart/src/registries/ChartTransformPropsRegistrySingleton.js
- packages/superset-ui-core/package.json
- packages/superset-ui-core/src/models/Registry.js
- packages/superset-ui-core/src/models/RegistryWithDefaultKey.js
- packages/superset-ui-core/test/models/Registry.test.js
- packages/superset-ui-core/test/models/RegistryWithDefaultKey.test.js
BREAKING CHANGE: Change `Registry` constructor API to take object instead of single string `name`. 
This constructor has not been called anywhere in `incubator-superset`. It is only used in other packages in `@superset-ui`, which are also updated in this PR.
🏆 Enhancements
feat: Add `overwritePolicy` for `Registry` so developer can customize whether overwriting is `ALLOW`, `WARN` or `PROHIBIT`. 
🏠 Internal
fix: Change variable name `options` to `config` for consistency.
> Add overwritePolicy for Registry

- packages/superset-ui-chart/src/models/ChartPlugin.js
- packages/superset-ui-chart/test/models/ChartPlugin.test.js
None
🏆 Enhancements
During the transition of adding `buildQuery` to each chart, we need to have a flag to indicate if `buildQuery` is implemented.  
This PR is to change the default value of `buildQuery` to None, so that it can be used as the flag. 
🐛 Bug Fix
🏠 Internal
> Changed the default value for buildQuery to null

- packages/superset-ui-number-format/src/NumberFormatterRegistry.js
- packages/superset-ui-number-format/test/NumberFormatterRegistry.test.js
- packages/superset-ui-time-format/src/TimeFormatterRegistry.js
- packages/superset-ui-time-format/test/TimeFormatterRegistry.test.js
🏆 Enhancements
Remove leading and trailing space when looking up formatter.
- `getNumberFormatter(format)` works the same for `".2f"` and `" .2f "`
- `getTimeFormatter(format)` works the same for `"%Y"` and `" %Y "`
> Remove leading and trailing space when looking up formatter

- packages/superset-ui-number-format/test/factories/createD3NumberFormatter.test.js
- packages/superset-ui-number-format/test/factories/createSiAtMostNDigitFormatter.test.js
- packages/superset-ui-time-format/test/factories/createMultiFormatter.test.js
🏠 Internal
- Remove unnecessary nesting of `describe` block and update `describe` description to reflect the code.
> Fix typo in unit test description

- packages/superset-ui-connection/src/callApi/callApiAndParseWithTimeout.ts
- packages/superset-ui-connection/src/callApi/rejectAfterTimeout.ts
- packages/superset-ui-connection/test/callApi/callApiAndParseWithTimeout.test.ts
🏆 Enhancements
- type rejectAfterTimeout with generics.
- fixing an import typo in tests.
> Type promises

- package.json
- packages/superset-ui-chart/src/query/Column.ts
- packages/superset-ui-chart/src/query/DatasourceKey.ts
- packages/superset-ui-chart/src/query/FormData.ts
- packages/superset-ui-chart/src/query/Metric.ts
- packages/superset-ui-chart/src/query/buildQueryContext.ts
- packages/superset-ui-chart/src/query/buildQueryObject.ts
- packages/superset-ui-chart/src/query/index.ts
- packages/superset-ui-chart/test/query/DatasourceKey.test.ts
- packages/superset-ui-chart/test/query/Metric.test.ts
- packages/superset-ui-chart/test/query/buildQueryContext.test.ts
- packages/superset-ui-chart/test/query/buildQueryObject.test.ts
🏆 Enhancements
This PR moves query object generation code from incubator-superset to superset-ui.
> Moving query module into superset-ui from incubator-superset

- packages/superset-ui-connection/src/SupersetClient.ts
🐛 Bug Fix
This fixes an error in `@superset-ui/connection@^0.7.0` where it will throw immediately from the rejected promise in the constructor. Even though this doesn't seem to fail in node tests, it looks like it throws in the browser 🙄 
@kristw @xtinec @conglei
> [bugfix][connection] fix client promise

- package.json
- packages/superset-ui-connection/src/SupersetClient.ts
- packages/superset-ui-connection/src/SupersetClientClass.ts
- packages/superset-ui-connection/src/index.ts
- packages/superset-ui-connection/test/SupersetClient.test.ts
- packages/superset-ui-connection/test/SupersetClientClass.test.ts
- packages/superset-ui-connection/test/callApi/parseResponse.test.js
- internal: Separate `SupersetClient` (formerly `PublicAPI`) and `SupersetClientClass` (formerly `SupersetClient`) into their own files, as well as unit tests.
- internal: Add new unit test for `parseResponse` and `SupersetClientClass` to improve test coverage to 💯 again.
- feat: Export `SupersetClientClass`
> Separate SupersetClient and SupersetClientClass

- packages/superset-ui-chart/src/query/FormData.ts
- packages/superset-ui-chart/src/query/Metric.ts
- packages/superset-ui-chart/test/query/Metric.test.ts
🏠 Internal
Metrics can take shape of an array of metrics in form data for a given metrics key. For example, `{ metrics: ['sum__num'] }`. This PR changes Metrics class to handle the array case.
> Allow metrics arrays in form data

- packages/superset-ui-chart/src/components/SuperChart.tsx
- packages/superset-ui-chart/src/index.ts
- packages/superset-ui-chart/src/models/ChartMetadata.ts
- packages/superset-ui-chart/src/models/ChartPlugin.ts
- packages/superset-ui-chart/src/models/ChartProps.ts
- packages/superset-ui-chart/test/components/SuperChart.test.jsx
- packages/superset-ui-chart/test/components/SuperChart.test.ts
- packages/superset-ui-chart/test/components/SuperChart.test.tsx
- packages/superset-ui-chart/test/models/ChartMetadata.test.ts
- packages/superset-ui-chart/test/models/ChartProps.test.ts
🏆 Enhancements
- Migrate `SuperChart` from `incubator-superset`, convert to TypeScript and add 100% unit tests.
- Add default values for `ChartProps`
🏠 Internal
- Change to `export default` for some modules.
> Add SuperChart

- lerna.json
- packages/generator-superset/package.json
- packages/superset-ui-chart/package.json
- packages/superset-ui-color/package.json
- packages/superset-ui-connection/package.json
- packages/superset-ui-core/package.json
- packages/superset-ui-demo/package.json
- packages/superset-ui-number-format/package.json
- packages/superset-ui-time-format/package.json
- packages/superset-ui-translation/package.json
🏠 Internal
Automatically generated during publish process.
to: @conglei @williaster @kristw
cc: @john-bodley
> Published version v0.8.0

- packages/superset-ui-chart/src/models/ChartMetadata.ts
🏆 Enhancements
- Add `useLegacyApi` field to `ChartMetadata`. This flag will help us determine whether to use the new `/api/v1/query` endpoint or the legacy one. 
- Reorder fields alphabetically.
> Add useLegacyApi field to ChartMetadata

- packages/superset-ui-translation/package.json
- packages/superset-ui-translation/src/index.ts
🏆 Enhancements
- Include and link TypeScript declaration for package `jed` with `@superset-ui/translation` distribution. 
**Rejected alternatives**
- Have every package that uses `@superset-ui/translation` and TypeScript write a Jed declaration. -- impractical.
- Create a complete declaration file for `jed` and publish to `@types/jed`. -- too much work for the use case at the moment.
> Include jed TS declaration with translation module

- packages/superset-ui-connection/src/SupersetClient.ts
- packages/superset-ui-connection/src/SupersetClientClass.ts
- packages/superset-ui-connection/src/types.ts
- packages/superset-ui-connection/test/SupersetClient.test.ts
- packages/superset-ui-connection/test/SupersetClientClass.test.ts
🏆 Enhancements
Trying to use METHOD = DELETE
> [SupersetClient] implement put and delete HTTP methods

- package.json
- scripts/buildAssets.js
🏠 Internal
- Add script to copy assets (`css`, `images`, `json`) to `esm` and `lib` folders
> Add script to copy assets to output folders

- packages/superset-ui-dimension/src/getTextDimension.ts
🐛 Bug Fix
- Make svg ignore pointer events in getTextDimension
> Make svg ignore pointer events in getTextDimension

- packages/superset-ui-chart/src/components/reactify.tsx
🐛 Bug Fix
`id` should have been optional. This leads to unnecessary error message in Superset console.
> Make id optional props for reactify

- CHANGELOG.md
- package.json
- Update `CHANGELOG`
🐛 Bug Fix
- Build fails because of `beemo` updates. I pin older version in case it will fix this.
> Update changelog and pin beemo version

- packages/superset-ui-color/src/CategoricalSchemeRegistrySingleton.ts
- packages/superset-ui-color/src/SequentialSchemeRegistrySingleton.ts
- packages/superset-ui-color/src/colorSchemes/sequential/d3.ts
- packages/superset-ui-color/test/CategoricalSchemeRegistrySingleton.test.ts
- packages/superset-ui-color/test/SequentialSchemeRegistrySingleton.test.ts
🏆 Enhancements
- At the moment, using `@superset-ui/color` has some friction because developers always need to add color schemes to it before using. Otherwise, it will crash. This PR registers one color scheme to each of the color (`Sequential`, `Categorical`) registries so the registries will always have at least one scheme to use and work out-of-the-box.
> Feat: Set default color scheme for the color registries

- packages/superset-ui-chart/src/models/ChartMetadata.ts
- packages/superset-ui-chart/test/models/ChartMetadata.test.ts
🏆 Enhancements
* add .clone() function to ChartMetadata
> feat: 🎸 add .clone() function to ChartMetadata

- packages/superset-ui-chart/src/query/Metrics.ts
- packages/superset-ui-chart/src/query/buildQueryObject.ts
- packages/superset-ui-chart/src/types/ChartFormData.ts
- packages/superset-ui-chart/src/types/Query.ts
- packages/superset-ui-chart/test/query/buildQueryObject.test.ts
🏆 Enhancements
The commit is to ensure the feature parity between frontend and backend `QueryOjbect`
> feat: 🎸 Improved QueryObject to handle more fields

- packages/superset-ui-chart/src/clients/ChartClient.ts
- packages/superset-ui-chart/src/components/SuperChart.tsx
- packages/superset-ui-chart/src/models/ChartMetadata.ts
- packages/superset-ui-chart/src/models/ChartPlugin.ts
- packages/superset-ui-chart/src/registries/ChartBuildQueryRegistrySingleton.ts
- packages/superset-ui-chart/src/registries/ChartComponentRegistrySingleton.ts
- packages/superset-ui-chart/src/registries/ChartMetadataRegistrySingleton.ts
- packages/superset-ui-chart/src/registries/ChartTransformPropsRegistrySingleton.ts
- packages/superset-ui-chart/src/types/Query.ts
- packages/superset-ui-chart/test/clients/ChartClient.test.ts
- packages/superset-ui-chart/test/components/SuperChart.test.tsx
- packages/superset-ui-chart/test/models/ChartPlugin.test.tsx
- packages/superset-ui-chart/types/external.d.ts
- packages/superset-ui-core/src/models/Registry.ts
- packages/superset-ui-demo/storybook/stories/superset-ui-chart/ChartDataProviderStories.tsx
🏠 Internal
This PR removes the faux `@superset-ui/core` TS declaration in `@superset-ui/chart` (introduced before `core` was re-written in TS). All of the changes are to clean up resulting TS errors from that removal. Some notes on specifics that were done:
- Refined and consolidated some `type`s that were duplicated across files like `ChartType`, `(Pre/Post)TransformProps`, etc.. Turns out the duplication wasn't always entirely consistent though at surface level it might not be obvious.
- Added the needed generics to all of the chart plugin `registry`s
- Updated the logic for supporting `Value | { default: Value }` generally across loaders. This is now confined to `ChartPlugin` in order to simplify types elsewhere, while still supporting dynamic loading of ES modules: `() => …
> chore(chart): remove faux @superset-ui/core TS declaration

- package.json
- packages/superset-ui-chart/src/components/ChartDataProvider.tsx
🐛 Bug Fix 🏠 Internal
This PR
- fixes an import in `@superset-ui/chart` that should be from a package, not the monorepo. this caused the build to include additional directories in `0.10.5` and `0.10.6`. I confirmed that these directories are no longer generated after the fix.
- adds a flag to the `build` `npm` scripts to delete the out directory, to ensure that deleted files and directories are not included in new releases.
>  fix(chart): import types from package, not monorepo

- packages/superset-ui-color/src/CategoricalColorScale.ts
- packages/superset-ui-color/test/CategoricalColorScale.test.ts
🏆 Enhancements
Exposed a getter function to return the color mapping between a data value and a color hex code. This is needed so we can save it as dashboard metadata for color consistency in dashboards (https://github.com/apache/incubator-superset/pull/7086).
> feat: getter function to return color mapping

- packages/superset-ui-chart/src/index.ts
- packages/superset-ui-chart/src/models/ChartPlugin.ts
- packages/superset-ui-chart/src/types/Query.ts
- packages/superset-ui-chart/test/components/SuperChart.test.tsx
This PR is to fix the type definiton for `transformProps` and `LoadData`.
For `TransformProps`, the input type should be `ChartProps` instead of `PlainObject`. 
For `LoadData`, before, the `ChartType` was `ComponentType | FunctionComponent`, which means the no props allowed for the component, which is not correct. 
🏆 Enhancements
Exported Metric definition. 
🐛 Bug Fix
In most of the cases, There will be no `PreTransformProps` defined. Thus, the input for `TransformProp
🏠 Internal
> fix: 🐛 Fixed type definition for chart plugin

- .github/semantic.yml
🏠 Internal
By default, the semantic pull request bot passes if either (1) PR title is conventional commit or (2) at least one commit message is conventional commit.
This PR will enforces that PR title must always be a valid message because this will be used when squash merge.
https://github.com/probot/semantic-pull-requests
> chore: enforce check on PR title to be conventional commit

- package.json
- packages/superset-ui-connection/README.md
- packages/superset-ui-connection/src/callApi/callApi.ts
- packages/superset-ui-connection/src/constants.ts
- packages/superset-ui-connection/test/callApi/callApi.test.ts
- test/setupTests.ts
🏆 Enhancements
This PR adds support for conditional `GET` requests, since they're not supported by the Fetch API. This is how it works:
1. If a `GET` request is successful (status `200 OK`) and it has an `ETag` header, a copy of the response is stored using the [Cache API](https://developers.google.com/web/fundamentals/instant-and-offline/web-storage/cache-api).
2. The next time a request for the same URL is made, the cache is checked.
3. If the cache has a cached request, its `ETag` is retrieved.
4. The client does a request with the header `If-None-Matches` with the stored `ETag`.
5. If the server returns a status `304 Not Modified`, the cached response is used instead.
6. Otherwise, if the response is a `200 OK` the previous cache is deleted and the new response is stored.
This will be …
> feat: add support for conditional requests

- packages/superset-ui-chart/src/components/reactify.tsx
- packages/superset-ui-chart/test/components/reactify.test.tsx
🏆 Enhancements
Add a second argument to the exported `reactify` method to allow wrapped component to pass in callback hooks for React lifecycle methods. This PR only exposes the willUnmount hook. Other hooks can be added in the future.
> feat: callback hooks for Reactified components

- packages/superset-ui-time-format/package.json
> fix: smartDateVerbose at seconds

- .github/config.yml
🏠 Internal
Enable bots that comments when PR has no title or description.
> chore: add config for request-info bot

- packages/superset-ui-chart/package.json
- packages/superset-ui-color/package.json
- packages/superset-ui-number-format/package.json
- packages/superset-ui-time-format/package.json
🐛 Bug Fix
* bump `peerDependencies` version, which are not bumped automatically by `lerna`.
> fix: bump peer dependencies

- packages/superset-ui-translation/src/TranslatorSingleton.ts
🐛 Bug Fix
* type of `singleton` can be `undefined` before the first `configure()` or `getInstance()` call.
> fix: make translation module type check correctly

- packages/superset-ui-connection/test/callApi/callApi.test.ts
🐛 Bug Fix
* Replace `response.body` direct access which returns stream data input with `response.text()` which converts the data stream into single string (but returns `Promise<string>`).
The main changes are 
* `firstResponse.body` => `firstResponse.text()`
* `secondResponse.body`=> `secondResponse.text()` 
* `response.body` => `secondResponse.text()`.
* Also change the code to `async`/`await` for readability as there are many `Promise` nesting.
> fix: broken build due to failing unit tests

- README.md
> Updated Readme with missing yarn build command.

- packages/superset-ui-chart/src/models/ChartProps.ts
🏆 Enhancements
* Add `hooks` field to contains non-serializable configuration and optional overrides such as `TooltipRenderer`, `LegendRenderer` that cannot go into `formData`.
> feat: add hooks field to ChartProps

- packages/superset-ui-dimension/src/mergeMargin.ts
- packages/superset-ui-dimension/test/mergeMargin.test.ts
🏆 Enhancements
Handle `NaN` and `null` better when merging.
> feat: improve margin merging with NaN and null

- packages/superset-ui-chart/src/models/ChartPlugin.ts
- packages/superset-ui-chart/test/models/ChartPlugin.test.tsx
- packages/superset-ui-core/src/models/Plugin.ts
- packages/superset-ui-core/test/models/Plugin.test.ts
🏆 Enhancements
* Add `.unregister()` function to `ChartPlugin`
🏠 Internal
* Improve unit tests
> feat: allow chart plugin to be unregistered

- packages/superset-ui-chart/src/components/SuperChart.tsx
- packages/superset-ui-chart/src/index.ts
- packages/superset-ui-chart/src/models/ChartPlugin.ts
- packages/superset-ui-chart/src/models/ChartProps.ts
- packages/superset-ui-chart/src/registries/ChartTransformPropsRegistrySingleton.ts
- packages/superset-ui-chart/src/types/Base.ts
- packages/superset-ui-chart/src/types/Query.ts
- packages/superset-ui-chart/src/types/TransformFunction.ts
🏠 Internal
* Move the types of transform functions from `types/Query.ts` to `types/TransformFunction.ts`
* Extract basic types `HandlerFunction` and `PlainObject` to `types/Base.ts`
> refactor: separate transform function types into a new file

- packages/superset-ui-dimension/src/index.ts
- packages/superset-ui-dimension/src/parseLength.ts
- packages/superset-ui-dimension/test/parseLength.test.ts
🏆 Enhancements
Add function `parseLength` to parse width or height 
* `'100%'` => `{ isDynamic: true, multiplier: 1 }`
* `'50%'` => `{ isDynamic: true, multiplier: 0.5 }`
* `100` => `{ isDynamic: false, value: 100 }`
* `'100'` => `{ isDynamic: false, value: 100 }`
* `100px` => `{ isDynamic: false, value: 100 }`
> feat: add parseLength function to @superset-ui/dimension

- package.json
- packages/superset-ui-chart/__mocks__/resize-observer-polyfill.js
- packages/superset-ui-chart/package.json
- packages/superset-ui-chart/src/components/FallbackComponent.tsx
- packages/superset-ui-chart/src/components/SuperChart.tsx
- packages/superset-ui-chart/src/components/SuperChartCore.tsx
- packages/superset-ui-chart/src/components/SuperChartKernel.tsx
- packages/superset-ui-chart/src/components/SuperChartShell.tsx
- packages/superset-ui-chart/src/index.ts
- packages/superset-ui-chart/src/models/ChartProps.ts
- packages/superset-ui-chart/test/components/FallbackComponent.test.tsx
- packages/superset-ui-chart/test/components/MockChartPlugins.tsx
- packages/superset-ui-chart/test/components/SuperChartCore.test.tsx
- packages/superset-ui-chart/test/components/SuperChartKernel.test.tsx
- packages/superset-ui-chart/test/components/SuperChartShell.test.tsx
- packages/superset-ui-chart/test/components/promiseTimeout.tsx
- packages/superset-ui-chart/types/@vx/responsive/index.d.ts
- packages/superset-ui-demo/.storybook/config.js
- packages/superset-ui-demo/.storybook/webpack.config.js
- packages/superset-ui-demo/storybook/stories/superset-ui-chart/SuperChartStories.tsx
- packages/superset-ui-demo/storybook/stories/superset-ui-chart/index.ts
* Rename former `SuperChart` class to `SuperChartCore`.
* Add `@vx/responsive` type declaration.
Create new class `SuperChart` that wraps `SuperChartCore`. 
Create another new class `SuperChartShell` to wrap `SuperChart` and provide backward-compatibility API. This can be removed in the upcoming breaking change.
`SuperChartShell` is exported as `SuperChart` and provide 100% backward-compatibility.
* Provide `ErrorBoundary`, which can be disabled if needed.
* Allow users to specify `width` `height` as `number` or dynamic value such as `100%`.
* Support spreading `chartProps` fields to top-level.
**Before**
This behavior is still supported, but less preferred.
```tsx
<SuperChart chartProps={new ChartProps({ width: 400, height: 400, formData: {a: 1} })} />
```
**Enhancement#1 Support plain …
> feat: add error boundary and responsiveness to SuperChart

- packages/superset-ui-chart/src/components/SuperChart.tsx
- packages/superset-ui-chart/src/components/SuperChartCore.tsx
- packages/superset-ui-chart/src/components/SuperChartShell.tsx
🏆 Enhancements
* feat: store reference to container
🏠 Internal
* Remove `constructor` and bindings and declare functions that are bound as class variables.
> feat: store reference to container and update bindings

- packages/superset-ui-chart/src/models/ChartProps.ts
* type of `filters` field is an object, not array. The name `filters` is misleading because it is actually the initial values of `filter_box` and `table`
> fix: wrong type for filters field

- packages/superset-ui-number-format/src/factories/createD3NumberFormatter.ts
- packages/superset-ui-number-format/test/factories/createD3NumberFormatter.test.ts
- packages/superset-ui-time-format/src/factories/createD3TimeFormatter.ts
- packages/superset-ui-time-format/test/factories/createD3TimeFormatter.test.js
- packages/superset-ui-time-format/test/factories/createD3TimeFormatter.test.ts
🏆 Enhancements
* Accept d3 `locale` configuration for both time and number formats to support custom currency, e.g. Euro, and day/month name in different languages.
* Add new tests and consolidate test files.
fix #181
> feat: support locale in number and time format

- packages/superset-ui-chart/test/components/reactify.test.tsx
🐛 Bug Fix
For some reason `yarn lint` was still failing with this rule, breaking the build. I've disabled the rule for the whole file, which should be fine since it's a test
> fix: move eslint disable comment in reactify test

- packages/superset-ui-connection/src/SupersetClientClass.ts
- packages/superset-ui-connection/test/SupersetClientClass.test.ts
- packages/superset-ui-connection/test/callApi/callApi.test.ts
- packages/superset-ui-connection/test/callApi/callApiAndParseWithTimeout.test.ts
- packages/superset-ui-connection/test/callApi/parseResponse.test.ts
🐛 Bug Fix
Fixes the build
Tested with `yarn lint` and `yarn test`
> fix: clean up unneeded Promise.resolves()

- packages/superset-ui-connection/src/callApi/callApi.ts
- packages/superset-ui-connection/test/callApi/callApi.test.ts
- test/setupTests.ts
When the page is served over an insecure connection, some browsers (Firefox) will disable the
CacheStorage API for security reasons and will throw an error when an attempt is made to use it.
Thus, do not even attempt to use CacheStorage on such connections in the first place.
🐛 Bug Fix
fix #193
🏠 Internal
Contrary to what I suggested in the bug, I had to put the test for the insecure connection into `callApi` itself to be able to test it.
> fix(connection): disable caching when on an insecure connection

- packages/superset-ui-chart-composition/src/tooltip/TooltipTable.tsx
- packages/superset-ui-chart/src/types/Column.ts
- packages/superset-ui-chart/src/types/Datasource.ts
- packages/superset-ui-chart/src/types/Metric.ts
- packages/superset-ui-chart/test/clients/ChartClient.test.ts
🐛 Bug Fix
Fix the following lint errors
```
/home/travis/build/apache-superset/superset-ui/packages/superset-ui-chart/src/types/Column.ts
3:1  error  Prefer default export  import/prefer-default-export
/home/travis/build/apache-superset/superset-ui/packages/superset-ui-chart/src/types/Datasource.ts
4:1  error  Prefer default export  import/prefer-default-export
/home/travis/build/apache-superset/superset-ui/packages/superset-ui-chart/src/types/Metric.ts
7:1  error  Prefer default export  import/prefer-default-export
/home/travis/build/apache-superset/superset-ui/packages/superset-ui-chart/test/clients/ChartClient.test.ts
173:7  error  Async assertions must be awaited or returned  jest/valid-expect
/home/travis/build/apache-superset/superset-ui/packages/superset-ui-chart-composition/src/too …
```
> fix: eslint issues

- packages/superset-ui-chart/src/components/reactify.tsx
This is needed so that the callbacks passed into this component can perform actions based on props/state on the react component
@xtinec @kristw @williaster
> feat: allow reactify callbacks to access props

- packages/superset-ui-dimension/src/getMultipleTextDimensions.ts
- packages/superset-ui-dimension/src/getTextDimension.ts
- packages/superset-ui-dimension/src/index.ts
- packages/superset-ui-dimension/src/svg/LazyFactory.ts
- packages/superset-ui-dimension/src/svg/constants.ts
- packages/superset-ui-dimension/src/svg/createHiddenSvgNode.ts
- packages/superset-ui-dimension/src/svg/createTextNode.ts
- packages/superset-ui-dimension/src/svg/factories.ts
- packages/superset-ui-dimension/src/svg/getBBoxCeil.ts
- packages/superset-ui-dimension/src/svg/updateTextNode.ts
- packages/superset-ui-dimension/test/computeMaxFontSize.test.ts
- packages/superset-ui-dimension/test/getBBoxDummyFill.ts
- packages/superset-ui-dimension/test/getMultipleTextDimensions.test.ts
- packages/superset-ui-dimension/test/getTextDimension.test.ts
- packages/superset-ui-dimension/test/svg/LazyFactory.test.ts
- packages/superset-ui-dimension/test/svg/getBBoxCeil.test.ts
- packages/superset-ui-dimension/test/svg/updateTextNode.test.ts
🏆 Enhancements
branching off from ideas in #173.
* Improve `getTextDimension` by lazy creation and deletion of the `svg` and `text` node to avoid creating multiple nodes and reusing existing one when applicable. 
* Add `getMultipleTextDimensions`  This function takes an array of text and compute dimensions in batch, reusing the text node and apply caching.
* The lazy creation and deletion is done via data structure `LazyFactory` that keeps counter of how many time a certain svg/text node is requested, hashed by container. Removal will decrease this counter and really remove the item when counter reaches 0.
* Both `getTextDimension` and `getMultipleTextDimensions` will leave the invisible nodes around for 500ms before removal to support reusability.
> feat: optimize functions for getting text dimension

- packages/superset-ui-chart/src/models/ChartProps.ts
- packages/superset-ui-chart/test/components/SuperChartCore.test.tsx
- packages/superset-ui-chart/test/models/ChartProps.test.ts
BREAKING CHANGE: ChartProps fields are removed and renamed.
The functions (`onAddFilter`, `onError`, `setControlValue`, `setTooltip`) are nested under `hooks` because these are used primarily in Superset app and has no use for other apps. 
|Before|After| Note |
|--|--|--|
| `annotationData` | `annotationData` |
| `datasource` | `datasource` |
| `filters` | *`initialValues` | `filters` was misleading because it is actually initial values of the `filter_box` and `table vis`. 
| `formData` | `formData` |
| `hooks` | `hooks` |
| `onAddFilter` | *`hooks.onAddFilter` | No longer provide an empty function as default value |
| `onError` | *`hooks.onError` | No longer provide an empty function as default value |
| `payload` | *`queryData` | `payload` is ambiguous
| …
> refactor(chart): remove and rename fields in ChartProps

- packages/superset-ui-encodeable/package.json
- packages/superset-ui-encodeable/src/parsers/createFormatterFromChannelDef.ts
- packages/superset-ui-encodeable/src/parsers/createFormatterFromFieldTypeAndFormat.ts
- packages/superset-ui-encodeable/src/parsers/createGetterFromChannelDef.ts
- packages/superset-ui-encodeable/src/parsers/fallbackFormatter.ts
- packages/superset-ui-encodeable/src/types/ChannelDef.ts
- packages/superset-ui-encodeable/test/parsers/createFormatterFromChannelDef.test.ts
- packages/superset-ui-encodeable/test/parsers/createFormatterFromFieldTypeAndFormat.test.ts
- packages/superset-ui-encodeable/test/parsers/createGetterFromChannelDef.test.ts
- packages/superset-ui-encodeable/test/parsers/fallbackFormatter.test.ts
🏆 Enhancements
* Add functions for parsing formatters from encoding
> feat: add functions for parsing formatters from encoding

- packages/superset-ui-chart/src/components/SuperChart.tsx
- packages/superset-ui-chart/test/components/SuperChart.test.tsx
- packages/superset-ui-chart/test/components/createLoadableRenderer.test.tsx
- packages/superset-ui-demo/storybook/stories/superset-ui-chart/SuperChartStories.tsx
When either `width` or `height` is already known, such as `width="100%" height={500}`.
Default `<ParentSize>` behavior will set the container style to `{width: '100%', height: '100%'}`, which may exceed the known `width` or `height` values, resulting in undesired blank space on the page. This PR add another `<div>` to wrap it (only when necessary). If both `width` and `height` are dynamic then no bounding box will be added. 
e.g. when want 100% width and 500px height.
```jsx
<div style={{width: '100%', height: 500}}>
<ParentSize>
{...}
</ParentSize>
</div>
```
Consider including these functionalities in the `@vx/responsive` rewrite.
Inspired by use case in `dataportal`. 
```jsx
// SuperChart with dynamic width/height
<SuperChart width="100%" height="400" chartType="line /> 
```
```jsx
// …
```
> feat: add Wrapper support and bounding box for dynamic width/height

- packages/superset-ui-connection/test/callApi/callApi.test.ts
🏠 Internal
* Add missing unit tests for `callApi` that cause the coverage to stuck at `99.99....%`. 
* This PR should bring coverage back to 100%.
> build: add missing unit test for callApi

- packages/superset-ui-chart/src/components/SuperChart.tsx
🐛 Bug Fix
Passing `width` and `height` to `React.Fragment` cause the console to print out warnings about unexpected props.
> fix: React.Fragment complaining about width/height

- packages/superset-ui-chart/test/components/SuperChart.test.tsx
🏠 Internal
Allow suppressing error boundary logs from intentionally thrown/caught errors.
These are caused by default behavior of `jsdom` and pollute the test report.
This PR adopts solution from this thread to clean up the test report.
https://github.com/facebook/react/issues/11098
> build: suppress logs from intentionally thrown/caught errors

- packages/superset-ui-color/package.json
- packages/superset-ui-encodable/package.json
- packages/superset-ui-encodable/src/encoders/ChannelEncoder.ts
- packages/superset-ui-encodable/src/fillers/completeChannelDef.ts
- packages/superset-ui-encodable/src/fillers/completeScaleConfig.ts
- packages/superset-ui-encodable/src/fillers/inferFieldType.ts
- packages/superset-ui-encodable/src/index.ts
- packages/superset-ui-encodable/src/parsers/createGetterFromChannelDef.ts
- packages/superset-ui-encodable/src/parsers/scale/createScaleFromScaleType.ts
- packages/superset-ui-encodable/src/types/Base.ts
- packages/superset-ui-encodable/src/types/Scale.ts
- packages/superset-ui-encodable/test/encoders/ChannelEncoder.test.ts
- packages/superset-ui-encodable/test/fillers/completeChannelDef.test.ts
- packages/superset-ui-encodable/test/fillers/inferFieldType.test.ts
- packages/superset-ui-encodable/test/parsers/createGetterFromChannelDef.test.ts
- packages/superset-ui-encodable/types/d3-scale/index.d.ts
🏆 Enhancements
* Add `ChannelEncoder` which takes user-defined channel definition, complete and parse into an object with set of utility functions useful for rendering that channel. 
The "rendering" mention here is framework-independent. Chart component developer is required to figure out how to implement the rendering themselves. `ChannelEncoder` acts as a middle layer to standardize chart component consumer API, then translate the configuration into actionable functions.
```ts
const encoder = new ChannelEncoder({
name: 'x',
channelType: 'X',
definition: {
type: 'quantitative',
field: 'speed',
title: 'Speed',
format: '.2f',
scale: {
type: 'linear',
domain: [0, 100],
range: [0, 1],
}
},
});
encoder.encodeValue(50); // 0.5
encoder.encodeDatum({ speed: 50 }); // 0.5
encoder.formatValue(10); …
```
> feat: Add channel encoder

- packages/superset-ui-encodable/src/encoders/ChannelEncoder.ts
- packages/superset-ui-encodable/src/encoders/Encoder.ts
- packages/superset-ui-encodable/src/encoders/createEncoderFactory.ts
- packages/superset-ui-encodable/src/fillers/completeChannelDef.ts
- packages/superset-ui-encodable/src/fillers/completeLegendConfig.ts
- packages/superset-ui-encodable/src/types/Encoding.ts
- packages/superset-ui-encodable/src/types/Legend.ts
- packages/superset-ui-encodable/src/utils/mergeEncoding.ts
- packages/superset-ui-encodable/test/encoders/ChannelEncoder.test.ts
- packages/superset-ui-encodable/test/encoders/Encoder.test.ts
- packages/superset-ui-encodable/test/encoders/createEncoderFactory.test.ts
- packages/superset-ui-encodable/test/fillers/completeChannelDef.test.ts
- packages/superset-ui-encodable/test/fillers/completeLegendConfig.test.ts
- packages/superset-ui-encodable/test/utils/mergeEncoding.test.ts
🏆 Enhancements
Add `Encoder` to `@superset-ui/encodable`. An `Encoder` is a utility class created once per chart type. 
* It consists of one or more `ChannelEncoder`
* It takes users' definitions of the channels (`vega-lite` syntax), then resolves ambiguity and produce complete definition and actionable utility functions. 
The component developer creates an encoder factory once.
```ts
type LineChartEncodingConfig = {
// channelName: [ChannelType, output type, support multiple fields or not]
x: ['X', number];
y: ['Y', number];
color: ['Color', string];
tooltip: ['Text', string, 'multiple'];
};
const lineChartEncoderFactory = createEncoderFactory<LineChartEncodingConfig>({
// This part is manual work to convert the `ChannelType` defined in `LineChartEncodingConfig` above
// from `type` to …
```
> feat: Add Encoder

- packages/superset-ui-encodable/src/encoders/ChannelEncoder.ts
- packages/superset-ui-encodable/src/encoders/Encoder.ts
- packages/superset-ui-encodable/src/types/Encoding.ts
- packages/superset-ui-encodable/test/encoders/Encoder.test.ts
🏆 Enhancements
Add `encoder.getLegendInformation(dataset)`, which generates metadata for rendering legend.
```ts
const legendInfo = factory
.create({
color: { 
type: 'nominal', 
field: 'brand', 
scale: { range: ['red', 'green', 'blue'] } 
},
radius: { value: 5 },
shape: { value: 'circle' },
})
.getLegendInformation([{ brand: 'Gucci' }, { brand: 'Prada' }]);
// [
//   // legend group information
//   {
//     field: 'brand',
//     type: 'nominal',
//     items: [
//       {
//         input: 'Gucci',
//         output: {
//           color: 'red',
//           radius: 5,
//           shape: 'circle',
//         },
//       },
//       {
//         input: 'Prada',
//         output: {
//           color: 'green',
//           radius: 5,
//           shape: 'circle',
//         },
// …
```
> feat: add function for getting legend information

- packages/superset-ui-chart/src/components/SuperChart.tsx
- packages/superset-ui-chart/src/index.ts
- packages/superset-ui-core/test/models/Registry.test.ts
- packages/superset-ui-encodable/src/encoders/createEncoderFactory.ts
- packages/superset-ui-encodable/src/fillers/completeAxisConfig.ts
- packages/superset-ui-number-format/src/index.ts
- packages/superset-ui-query/src/types/Query.ts
🏠 Internal
Fix new linting errors (after some build dependencies upgrade) via `yarn lint -- --fix`
> build: fix lint

- packages/superset-ui-time-format/package.json
🏆 Enhancements
Will allow us to use the `%q` directive for quarter of the year: https://github.com/d3/d3-time-format/releases/tag/v2.2.0
Tested with CI
@kristw @williaster @michellethomas
> feat(time-format): bump d3-time-format

- packages/superset-ui-encodable/src/encoders/ChannelEncoder.ts
- packages/superset-ui-encodable/src/encoders/Encoder.ts
- packages/superset-ui-encodable/test/encoders/ChannelEncoder.test.ts
🏠 Internal
* rename `.getDomain()` to `.getDomainFromDataset()` for clarity
> refactor: rename .getDomain() to .getDomainFromDataset()

- packages/superset-ui-core/package.json
🏠 Internal
* Add `@types/lodash` to dependencies to fix broken build.
> build: fix lodash type dependencies

- packages/superset-ui-encodable/src/parsers/scale/applyDomain.ts
- packages/superset-ui-encodable/src/typeGuards/Base.ts
- packages/superset-ui-encodable/src/typeGuards/Scale.ts
- packages/superset-ui-encodable/src/types/Scale.ts
- packages/superset-ui-encodable/test/parsers/scale/createScaleFromScaleConfig.test.ts
- packages/superset-ui-encodable/test/typeGuards/Base.test.ts
- packages/superset-ui-encodable/test/typeGuards/Scale.test.ts
🏆 Enhancements
The `domain` field in `scale` configuration should act like user-specified bounds for the `domain` obtained from dataset. The `applyDomain()` function is called when trying to create a `scale` from the configuration alone, without knowledge about the dataset yet.
* If both `[min, max]` are set, it makes sense to set that `domain` to the `scale` object on initialization immediately because the `domain` from dataset will be overridden by the user-specified `domain`. 
* However, if one or both of `[min, max]` is not set, e.g. `[0, null]`. This `null` value means that max bound should be obtained from dataset. Therefore, the `domain` of `scale` object cannot be set yet until the dataset is known.
> feat(encodable): only set scale domain if both bounds are defined

- packages/superset-ui-encodable/src/parsers/domain/parseContinuousDomain.ts
- packages/superset-ui-encodable/src/parsers/domain/parseDiscreteDomain.ts
- packages/superset-ui-encodable/src/parsers/parseDateTimeIfPossible.ts
- packages/superset-ui-encodable/src/parsers/scale/applyDomain.ts
- packages/superset-ui-encodable/src/typeGuards/Base.ts
- packages/superset-ui-encodable/src/types/Scale.ts
- packages/superset-ui-encodable/src/utils/combineCategories.ts
- packages/superset-ui-encodable/src/utils/combineContinuousDomains.ts
- packages/superset-ui-encodable/test/parsers/domain/parseContinuousDomain.test.ts
- packages/superset-ui-encodable/test/parsers/domain/parseDiscreteDomain.test.ts
- packages/superset-ui-encodable/test/parsers/scale/applyDomain.test.ts
- packages/superset-ui-encodable/test/utils/combineCategories.test.ts
- packages/superset-ui-encodable/test/utils/combineContinuousDomains.test.ts
🏆 Enhancements
`applyDomain()` was applying `domain` field specified in scale config to `scale`. However, in real use case the developer needs to update the domain with domain from dataset. 
**Flow**
(1) user specifies `scaleConfig` (`json` or `js` object)
(2) passes it to `createScaleFromConfig` which creates `d3` scale and try to set `domain` if possible at this point. 
(3) set `domain` from dataset with respect to `domain` in `scaleConfig`, which is used as bounds. Now we have ready-to-use d3 scale.
The work before this PR stops at step 2. This PR enable step 3.
> feat(encodable): make applyDomain() able to handle domain from dataset

- packages/superset-ui-encodable/src/parsers/scale/applyZero.ts
- packages/superset-ui-encodable/test/parsers/scale/applyZero.test.ts
- packages/superset-ui-encodable/test/parsers/scale/createScaleFromScaleConfig.test.ts
🏆 Enhancements
Previous code did not handle edge case when the domain is in descending order.
>  feat(encodable): handle edge cases when making domain includes zero

- package.json
- packages/superset-ui-chart/src/clients/ChartClient.ts
- packages/superset-ui-chart/src/components/ChartDataProvider.tsx
🐛 Bug Fix
After upgrading to `typescript@3.7`, several issues show up.
> fix: typing issues surfaced by typescript 3.7

- packages/superset-ui-dimension/src/svg/createHiddenSvgNode.ts
🐛 Bug Fix
This fixes an issue in `@superset-ui/dimensions` where the hidden `svg` used for text measurement has a non-zero `width/height`, and can result in the `svg` affecting layout even though it has `position: absolute`. In our case this actually causes an infinite measurement loop where 
1) the `svg` is added, resulting in a browser scroll bar
2) the `svg` is removed, making the scroll bar go away
3) the screen width change in `2)` from the scroll bar going away triggers the ResizeObserver of a parent component, updating the chart and goes back to `1)` 
I updated it to mirror what we have in `@vx/text` which was fixed [here](https://github.com/hshoff/vx/pull/358).
@kristw
> fix(dimension): set width=0, height=0 in `createHiddenSvgNode`

- packages/superset-ui-number-format/package.json
🏆 Enhancements
Bump `pretty-ms` to `5.1.0` to enable support for `colonNotation` option in `duration-formatter`: https://github.com/sindresorhus/pretty-ms/pull/37
> feat(number-format): bump pretty-ms to 5.1.0

- packages/superset-ui-number-format/README.md
Add example to `superset-ui-number-format` README about how to use `durationFormatter`.
> docs: add durationFormatter example to number-format README.md

- package.json
🏠 Internal
Rename `yarn type:dts` to `yarn type` for brevity
> build: rename yarn type:dts to yarn type

- packages/superset-ui-chart/src/components/NoResultsComponent.tsx
- packages/superset-ui-chart/src/components/SuperChart.tsx
- packages/superset-ui-chart/test/components/NoResultsComponent.test.tsx
- packages/superset-ui-chart/test/components/SuperChart.test.tsx
- packages/superset-ui-demo/storybook/stories/superset-ui-chart/SuperChartStories.tsx
🏆 Enhancements
Introduces new behavior for when no queryData is passed to a Superset Chart. Currently this never happens because Superset renders it's own error message, but this will be used in the future once we allow the backend to return empty query data as valid data.
Test plan:
Add new storybook examples and unit tests
Message on a small chart:
Message on a large chart:
> feat: add NoResultsComponent to charts

- packages/superset-ui-number-format/src/NumberFormatterRegistry.ts
- packages/superset-ui-number-format/test/NumberFormatterRegistry.test.ts
- packages/superset-ui-time-format/src/TimeFormatterRegistry.ts
- packages/superset-ui-time-format/test/TimeFormatterRegistry.test.ts
🏆 Enhancements
* Make `formatTime` and `formatNumber` handle `undefined` type. The logic is already there, but the argument type was still `string`
cc @ktmud
> feat: make formatTime and formatNumber accept undefined type

- packages/superset-ui-number-format/src/NumberFormatterRegistry.ts
- packages/superset-ui-number-format/src/NumberFormatterRegistrySingleton.ts
- packages/superset-ui-number-format/test/NumberFormatterRegistry.test.ts
- packages/superset-ui-number-format/test/NumberFormatterRegistrySingleton.test.ts
- packages/superset-ui-time-format/src/TimeFormatterRegistry.ts
- packages/superset-ui-time-format/src/TimeFormatterRegistrySingleton.ts
- packages/superset-ui-time-format/test/TimeFormatterRegistry.test.ts
- packages/superset-ui-time-format/test/TimeFormatterRegistrySingleton.test.ts
🏆 Enhancements
* Follow up from #307 , make `formatTime`, `getTimeFormatter`, `formatNumber`, `getNumberFormatter` handle `undefined` format.
* Bring back support for empty string as format. This was due to the recent change from `||` to `??`.
The code used to be `format || defaultFormat`, and it was changed by `eslint` auto-fix to `format ?? defaultFormat`.
```ts
'' || 'abc' = 'abc'
'' ?? 'abc' = ''
```
> feat: add more support for undefined format to number and time formatters

- packages/superset-ui-chart/src/components/NoResultsComponent.tsx
- packages/superset-ui-demo/storybook/stories/superset-ui-chart/SuperChartStories.tsx
🐛 Bug Fix
When testing this in superset, I realized it didn't render very well on small charts. This PR prevents the body from rendering on small charts and instead puts it in a tooltip. It also modifies the font sizes to better fit the font size hierarchy in dashboards
Before:
After:
to: @kristw @rusackas @ktmud
> fix: small rendering for no results message

- packages/superset-ui-validator/README.md
- packages/superset-ui-validator/package.json
- packages/superset-ui-validator/src/index.ts
- packages/superset-ui-validator/src/legacyValidateInteger.ts
- packages/superset-ui-validator/src/legacyValidateNumber.ts
- packages/superset-ui-validator/src/validateInteger.ts
- packages/superset-ui-validator/src/validateNonEmpty.ts
- packages/superset-ui-validator/src/validateNumber.ts
- packages/superset-ui-validator/test/legacyValidateInteger.test.ts
- packages/superset-ui-validator/test/legacyValidateNumber.test.ts
- packages/superset-ui-validator/test/validateInteger.test.ts
- packages/superset-ui-validator/test/validateNonEmpty.test.ts
- packages/superset-ui-validator/test/validateNumber.test.ts
- test/setup.ts
🏆 Enhancements
* Move validators from `incubator-superset` for usage in packages
```ts
import { legacyValidateInteger, legacyValidateNumber, validateNonEmpty } from '@superset-ui/validator';
```
There is a non-legacy `validateInteger` and `validateNumber` which has the logical behavior, but will break superset because it seems to expect the wrong output from the legacy functions at the moment.
@rusackas @villebro
> feat: add validator package

- codecov.yml
- plugins/table/src/ReactDataTable.tsx
- plugins/table/src/transformProps.ts
- plugins/table/test/ReactDataTable.test.tsx
- plugins/table/test/testData.ts
🐛 Bug Fix
Table chart displays time column incorrectly when "include time" is selected. This PR fixes it. It also fixes a bunch of linting issues surfaced by migrating the plugin packages to the `superset-ui` repo.
Added unit test.
> fix(legacy-plugin-chart-table): time column formatting

- package.json
- packages/superset-ui-demo/storybook/stories/plugins/table/TableStories.tsx
- packages/superset-ui-demo/tsconfig.json
- plugins/table/src/ReactDataTable.tsx
- plugins/table/src/transformProps.ts
- plugins/table/test/testData.ts
🏆 Enhancements
Fixes, in coordination with [this parallel PR](https://github.com/apache/incubator-superset/pull/9500), Superset issue #9499
> feat: allow toggling of table viz's bar chart backgrounds

- packages/superset-ui-color/src/CategoricalColorScale.ts
- packages/superset-ui-color/test/CategoricalColorScale.test.ts
🏆 Enhancements
`CategoricalScale` was originally written to provide similar functionality with `ScaleOrdinal` but allow color overrides (both at the scale itself and from its parent namespace).
However, due to its different class signature (function names, return types, etc.) from `ScaleOrdinal`, this caused some frictions when adopting it in place of `ScaleOrdinal`, both in Superset and other consumer apps. 
This PR add function `copy`, `domain`, `range` and `unknown` to `CategoricalScale` so it is fully compatible with `ScaleOrdinal` signature. 
```ts
// This is a valid statement in typescript. 
// Developer then can use scale similar to how they use D3's scaleOrdinal
const scale: ScaleOrdinal<{ toString(): string }, string> = new CategoricalColorScale([]);
```
This PR also expose new …
> feat: make CategoricalScale compatible with D3's ScaleOrdinal

- packages/superset-ui-core/test/models/ExtensibleFunction.test.ts
- packages/superset-ui-number-format/src/NumberFormatter.ts
- packages/superset-ui-time-format/src/TimeFormatter.ts
- packages/superset-ui-time-format/test/TimeFormatter.test.ts
✨ Enhancement
Add support for time formatter to handle `number`, it will treat the number as timestamp and convert to `Date`. This is consistent with how `d3-time-format` usually works.
🐛 Bug Fix
Fix this warning for `NumberFormatter` and `TimeFormatter` via type augmentation.
```
warning  Unsafe call of an any typed value  @typescript-eslint/no-unsafe-call
```
> feat: make time formatter handle number and fix formatters type warnings

- package.json
- yarn.lock
🏆 Enhancements
🏠 Internal
Disable commit lint in local development for smoother developer experience.
All changes must go through PR process and we already have [Semantic Pull Request](https://github.com/zeke/semantic-pull-requests) check. We almost always do squash merge, which means what developers committed locally doesn't really matter anyway.
> build: disable commit lint

- package.json
- packages/superset-ui-chart-composition/package.json
- packages/superset-ui-chart/package.json
- packages/superset-ui-chart/src/clients/ChartClient.ts
- packages/superset-ui-chart/src/components/ChartDataProvider.tsx
- packages/superset-ui-chart/src/index.ts
- packages/superset-ui-chart/src/models/ChartProps.ts
- packages/superset-ui-chart/src/types/QueryResponse.ts
- packages/superset-ui-chart/test/models/ChartProps.test.ts
- packages/superset-ui-demo/package.json
- packages/superset-ui-demo/storybook/stories/plugins/table/birthNames.json
- packages/superset-ui-query/src/types/Datasource.ts
- packages/superset-ui-query/src/types/Query.ts
- plugins/big-number/src/BigNumber/transformProps.ts
- plugins/big-number/src/tests/transformProps.test.ts
- plugins/big-number/src/utils/getTimeFormatterForGranularity.ts
- plugins/big-number/test/transformProps.test.ts
- plugins/table/package.json
- plugins/table/src/ReactDataTable.tsx
- plugins/table/src/Table.css
- plugins/table/src/transformProps.ts
- plugins/table/test/testData.ts
- scripts/build.js
- yarn.lock
🏆 Enhancements
🐛 Bug Fix
- Add back "emit filter" support to Table chart.
- Refactor typing for both Table and Big Number, make more strict or give more hints when possible.
> feat(table): enable table filter and better typing

- packages/superset-ui-connection/package.json
- packages/superset-ui-connection/src/SupersetClientClass.ts
- packages/superset-ui-connection/src/callApi/callApi.ts
- packages/superset-ui-connection/src/constants.ts
- packages/superset-ui-connection/src/types.ts
- packages/superset-ui-connection/test/callApi/callApi.test.ts
- yarn.lock
🏆 Enhancements
Adds the `fetch-retry` package to automatically retry any requests that fail due to network issues or 503 errors. This seems like a pretty safe approach to apply to all requests, but would appreciate feedback, especially if you think it's likely to break something.
Test Plan:
add/update unit tests
to: @kristw @williaster @ktmud @rusackas
> feat: add retry to callApi

- packages/superset-ui-query/src/buildQueryObject.ts
🐛 Bug Fix
Recently Superset was changed to not allow row_limit to be null, it can only be unset or a number. This fixes the library to match it
to: @williaster @ktmud @villebro @kristw
> fix: unset row_limit when it's not a number

- packages/superset-ui-query/src/types/Operator.ts
- packages/superset-ui-query/test/convertFilter.test.ts
- packages/superset-ui-query/test/types/Filter.test.ts
🐛 Bug Fix
Currently unary operators are uppercase, while binary and set operators are lowercase, which looks weird. As of [PR 9556](https://github.com/apache/incubator-superset/pull/9556) Superset now expects all filter operators to be uppercase (it does work with lowercase, but this support might be removed at some point).
> fix: make all filter operators uppercase

- packages/superset-ui-number-format/package.json
- packages/superset-ui-number-format/test/factories/createDurationFormatter.test.ts
🐛 Bug Fix
Bump `pretty-ms` dependency to fix rounding inconsistencies/errors in version 6: https://github.com/sindresorhus/pretty-ms/pull/49
> chore: bump pretty-ms

- packages/superset-ui-style/src/index.ts
- packages/superset-ui-style/test/index.test.ts
🏆 Enhancements
Export SupersetThemeProps interface so that it can be extended when using additional props in styled components.
> fix: export superset theme props

- packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-word-cloud/Stories.tsx
- plugins/plugin-chart-word-cloud/src/chart/WordCloud.tsx
- plugins/plugin-chart-word-cloud/src/plugin/index.ts
🐛 Bug Fix 1
* The WordCloud plugin was written with more flexible api than the original word cloud. (Basically, the `props` are different.) 
```ts
type OriginalProps = {
width: number,
height: number,
rotation: string,
data: { size: number, text: string } [];,
sizeRange: number[],
colorScheme: string,
}
```
example
```ts
{
colorScheme: 'd3Category10',
metric: 'sum__num',
rotation: 'square',
series: 'name',
sizeFrom: '10',
sizeTo: '70',
}
```
```ts
type NewProps = {
width: number;
height: number;
rotation?: RotationType;
data: { [key:string]: any; }[];
// support a vega-lite / grammar of graphic -style declaration
// to define encoding for different channels of the word cloud
// e.g. color, fontSize, fontFamily, fontWeight, text
encoding?: Partial<WordCloudEncoding>;
}
```
example
```ts
{ …
```
> fix(plugin-chart-word-cloud): make wordcloud take current formdata

- plugins/legacy-plugin-chart-calendar/package.json
- plugins/legacy-plugin-chart-calendar/src/controlPanel.js
- plugins/legacy-plugin-chart-calendar/src/index.js
🏆 Enhancements
Calendar manages its own control panel config
🐛 Bug Fix
🏠 Internal
> feat(calendar): add calendar control panel

- plugins/legacy-plugin-chart-world-map/src/index.js
🐛 Bug Fix
The World Map plugin is currently failing if the new chart data API is enabled in Superset due to `useLegacyApi` not being explicitly set to `true`.
@rusackas @kristw @suddjian @ktmud
> fix(legacy-plugin-world-map): set useLegacyApi to true by default

- packages/superset-ui-chart/test/models/ChartPlugin.test.tsx
- packages/superset-ui-query/src/buildQueryContext.ts
- packages/superset-ui-query/src/types/Query.ts
- packages/superset-ui-query/src/types/QueryFormData.ts
- packages/superset-ui-query/test/buildQueryContext.test.ts
🐛 Bug Fix
Currently the `force` parameter is missing from the `QueryContext` signature, making it impossible to force refresh charts. This PR adds `force` as an optional parameter in `QueryFormData` and defaults to `false` in `QueryContext` when undefined.
@rusackas @suddjian @ktmud @kristw
> fix: Add force to QueryContext

- plugins/legacy-preset-chart-nvd3/package.json
- plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
- plugins/legacy-preset-chart-nvd3/src/transformProps.js
- plugins/legacy-preset-chart-nvd3/src/utils/tokenize.js
- plugins/legacy-preset-chart-nvd3/src/utils/tokenize.ts
- plugins/legacy-preset-chart-nvd3/test/utils/isTruthy.test.js
- plugins/legacy-preset-chart-nvd3/test/utils/tokenize.test.js
🏠 Internal
This moves `BulletViz` range and marker parsing logic from the backend to the frontend. Once this PR is merged the relevant logic will be removed from `viz.py`: https://github.com/apache/incubator-superset/blob/5d167afb9499d7ce30c7ea763b19993af347dc23/superset/viz.py#L1094-L1124
Moving this will be necessary to deprecate `viz.py`, as non-datasource related data processing will not be supported in the new chart data API.
FYI @suddjian @rusackas
> chore(legacy-preset-chart-nvd3): move bullet chart option parsing from backend to frontend

- plugins/legacy-plugin-chart-sunburst/package.json
- plugins/legacy-plugin-chart-sunburst/src/controlPanel.ts
- plugins/legacy-plugin-chart-sunburst/src/index.js
🏆 Enhancements
This pulls in the controls from `incubator-superset`, and bumps the version number of the package. [Another PR](https://github.com/apache/incubator-superset/pull/9746) has been filed on `incubator-superset` to pull in this new package and remove the old controls and shims.
🐛 Bug Fix
🏠 Internal
> chore: pulling in Sunburst controls from incubator-superset

- plugins/legacy-preset-chart-nvd3/src/transformProps.js
- plugins/legacy-preset-chart-nvd3/test/utils/tokenize.test.js
🐛 Bug Fix
The current released version of NVD3 viz' doesn't work due to the import referencing the `ts` files (the linter forced me to add the suffix). I'm not really sure we should have that check here, as it appears to be causing broken releases.
@kristw @rusackas @ktmud
> fix: Remove .ts suffix from NVD3 imports

- package.json
- packages/superset-ui-chart/README.md
- scripts/commitlint.js
🏆 Enhancements
🏠 Internal
Since disabled commit-lint in #363, people who didn't install [Refined GitHub ](https://github.com/sindresorhus/refined-github) had been merging PRs without conventional commits.
This re-applies commit-lint to the first commit in branches that are not `master`, so to make sure we will always have conventional commits in master.
Also fixes prettier check in `pre-commit`, as it was unnecessarily slowed down by checking all files.
> chore: enforce commit-lint on first commit in branch

- plugins/legacy-preset-chart-nvd3/package.json
- plugins/legacy-preset-chart-nvd3/src/Area/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/Area/index.js
- plugins/legacy-preset-chart-nvd3/src/Bar/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/Bar/index.js
- plugins/legacy-preset-chart-nvd3/src/Bubble/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/Bubble/index.js
- plugins/legacy-preset-chart-nvd3/src/Bullet/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/Bullet/index.js
- plugins/legacy-preset-chart-nvd3/src/Compare/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/Compare/index.js
- plugins/legacy-preset-chart-nvd3/src/DistBar/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/DistBar/index.js
- plugins/legacy-preset-chart-nvd3/src/DualLine/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/DualLine/index.js
- plugins/legacy-preset-chart-nvd3/src/Line/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/Line/index.js
- plugins/legacy-preset-chart-nvd3/src/LineMulti/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/LineMulti/index.js
- plugins/legacy-preset-chart-nvd3/src/Pie/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/Pie/index.js
- plugins/legacy-preset-chart-nvd3/src/TimePivot/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/TimePivot/index.js
All the ones that are actually used in superset, anyway
> feat(legacy-plugin-chart-nvd3): add control panels

- codecov.yml
React modules don't have to have 100% unit-test coverages.
🏆 Enhancements
🏠 Internal
> test: be more lenient on jsx/tsx test coverage

- plugins/legacy-plugin-chart-markup/package.json
- plugins/legacy-plugin-chart-markup/src/controlPanel.js
- plugins/legacy-plugin-chart-markup/src/index.js
🏆 Enhancements
Add controls to markup chart plugin.
🐛 Bug Fix
🏠 Internal
> feat(legacy-plugin-chart-markup): add controls to markup chart

- packages/superset-ui-control-utils/package.json
- packages/superset-ui-control-utils/src/ColumnOption.tsx
- packages/superset-ui-control-utils/src/ColumnTypeLabel.tsx
- packages/superset-ui-control-utils/src/constants.ts
- packages/superset-ui-control-utils/src/index.ts
- packages/superset-ui-control-utils/src/mainMetric.ts
- packages/superset-ui-control-utils/src/shared-controls.tsx
- packages/superset-ui-control-utils/test/ColumnOption.test.tsx
- packages/superset-ui-control-utils/test/ColumnTypeLabel.test.tsx
- packages/superset-ui-control-utils/test/mainMetric.test.ts
🏆 Enhancements
Brought in the remaining shared controls from incubator-superset. This is a prerequisite for moving many of the controlPanels into the chart plugins.
When typing the `shared-controls` module, I did my best but had to use `unknown` in several places. I propose merging the types as-is, and putting together a set of properly fleshed-out types for the controls system separately, since that will be very useful for plugin writers/maintainers. I don't feel well-equipped to do that myself.
There are many subtle changes to these files due to differences in typescript/linter requirements between projects. Looking at the diff between these files and their originals in incubator-superset might be the best way to review.
I know this brings test coverage down, but I don't have the …
> feat(control-utils): add shared controls + dependencies, convert to typescript

- codecov.yml
🏆 Enhancements
Follow up on #468 .  `packages/**/*.js` does not exclude `.jsx`. We need to specifically exclude it.
> test: codecov ignore tsx/jsx

- package.json
- packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-calendar/Stories.tsx
- plugins/legacy-plugin-chart-sunburst/src/index.js
- plugins/legacy-preset-chart-nvd3/src/Area/index.js
- plugins/legacy-preset-chart-nvd3/src/Bar/index.js
- plugins/legacy-preset-chart-nvd3/src/Bubble/index.js
- plugins/legacy-preset-chart-nvd3/src/Bullet/index.js
- plugins/legacy-preset-chart-nvd3/src/Compare/index.js
- plugins/legacy-preset-chart-nvd3/src/DistBar/index.js
- plugins/legacy-preset-chart-nvd3/src/DualLine/index.js
- plugins/legacy-preset-chart-nvd3/src/Line/index.js
- plugins/legacy-preset-chart-nvd3/src/LineMulti/index.js
- plugins/legacy-preset-chart-nvd3/src/Pie/index.js
- plugins/legacy-preset-chart-nvd3/src/TimePivot/index.js
- plugins/legacy-preset-chart-nvd3/src/transformProps.js
- plugins/legacy-preset-chart-nvd3/test/utils/tokenize.test.js
🐛 Bug Fix
The `import/extensions` rule makes it impossible to correctly import ts from js.
> fix(legacy-plugin-chart-nvd3): disable bad linting rule

- packages/superset-ui-query/src/convertMetric.ts
- packages/superset-ui-query/test/convertMetric.test.ts
🏆 Enhancements
When working on another PR I noticed this redundant metric label mutation logic. For some time now, the Superset backend has supported arbitrary column/metric names, despite restrictions in the database. Check https://github.com/apache/incubator-superset/pull/5827 for more context.
> feat(query): remove redundant metric label truncation

- packages/superset-ui-time-format/src/factories/getTimeFormatterForGranularity.ts
- packages/superset-ui-time-format/test/factories/getTimeFormatterForGranularity.test.ts
🐛 Bug Fix
Most databases, including [ISO standards](https://en.wikipedia.org/wiki/ISO_8601#Durations), actually uses Monday as the first day of a week. The default week time grain in Superset (`P1W`) should translate to Monday-based weeks, too.
> fix(time-format): remove week number

- plugins/legacy-plugin-chart-map-box/package.json
- plugins/legacy-plugin-chart-map-box/src/controlPanel.js
- plugins/legacy-plugin-chart-map-box/src/index.js
> feat(legacy-plugin-chart-map-box): control panel

- plugins/legacy-plugin-chart-parallel-coordinates/src/index.js
🏆 Enhancements
🐛 Bug Fix
Remove .ts ext from import in para. causing error in superset.
🏠 Internal
> fix(legacy-plugin-chart-parallel-coordinates): remove .ts ext from import in para

- packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-table/birthNames.json
This property for `AdhocMetric` has been removed by apache/incubator-superset#9628
🏠 Internal
> chore(legacy-plugin-chart-table): cleanup fromFormData

- plugins/legacy-plugin-chart-table/src/transformProps.ts
- plugins/legacy-plugin-chart-table/test/ReactDataTable.test.tsx
- plugins/legacy-plugin-chart-table/test/testData.ts
🐛 Bug Fix
Pagination for table chart had stopped working because `pageLength` param somehow is not string any more.
This fix makes `transformProps` handle both numeric and string values and added unit tests.
> fix(legacy-plugin-chart-table): parse numeric pageLength

- plugins/legacy-preset-chart-nvd3/src/NVD3Vis.css
🐛 Bug Fix
It looks like a long time ago, the `sourceType` field for annotations was migrated from being `table` to `NATIVE`. This broke the tooltip for annotations. Since I'm quite unfamiliar with this code, and for backwards compatibility, I've left the old selector in but also added the new one which should resolve the issue.
New class name in superset:
to: @ktmud @graceguo-supercat @kristw
> fix: nvd3 annotation tooltip

- docs/debugging.md
- docs/storybook.md
The `npm link` process has been greatly simplified. Update the docs to reflect that.
> docs: simplified npm link for dev debugging

- packages/superset-ui-color/package.json
- packages/superset-ui-color/src/SequentialScheme.ts
- packages/superset-ui-color/test/SequentialScheme.test.ts
🏆 Enhancements
* add `modifyRange` option to `createLinearScale(domain, modifyRange = false)`. This extends the original behavior that always modify `domain` if needed.
```
* Return a linear scale with a new domain interpolated from the input domain
* to match the number of elements in the color scheme
* because D3 continuous scale uses piecewise mapping between domain and range.
* This is a common use-case when the domain is [min, max]
* and the palette has more than two colors.
*
* @param domain domain of the scale
* @param modifyRange Set this to true if you don't want to modify the domain and
* want to interpolate range to have the same number of elements with domain instead.
```
* add `extent` option for `.getColors(numColors, extent)` to reduce the range of the color scheme, …
> feat(color): support better color interpolation for sequential schemes

- packages/superset-ui-connection/src/SupersetClient.ts
🏆  Enhancements
In the existing implementation, `SupersetClient.getInstance()` will always throw error unless you also pass a `SupersetClient` instance as an argument. Then it will just return what you pass in as an argument back. 
I believe the original intention was to force developer to call `SupersetClient.configure()` before calling `.getInstance()` but even after calling `.configure()`. The `.getInstance()` itself is still not useful by itself. Calling it without argument, hoping to obtained the configured `SupersetClient` results in an `Error`. (I want to get the host name from the already configured singleton) and if I already have the `SupersetClient` instance, I would not bother calling this function.
This PR modifies the code to preserve the original intention, but allow …
> feat: allow developer to get supersetclient instance

- packages/superset-ui-demo/.storybook/themeDecorator.js
- packages/superset-ui-style/README.md
- packages/superset-ui-style/package.json
- packages/superset-ui-style/src/index.ts
- plugins/plugin-chart-word-cloud/package.json
- plugins/plugin-chart-word-cloud/src/chart/WordCloud.tsx
Export `ThemeProvider`, `useTheme` and `withTheme` from `emotion-theming` in `@superset-ui/style`, since they are almost always used together with `supersetTheme`.
This makes importing and package dependencies in Superset app (and dependent plugins) a little easier.
🏆 Enhancements
> feat(superset-ui-style): export ThemeProvider and useTheme

- CONTRIBUTING.md
- README.md
- package.json
- scripts/build.js
- scripts/copyAssets.js
🏆 Enhancements
The script used for building one package (`scirpts/build.js`) is broken. This PR fixes it and adds it to `yarn build`.
> build: allow building only one (or more) package

- packages/superset-ui-control-utils/src/ColumnOption.tsx
- packages/superset-ui-control-utils/src/ColumnTypeLabel.tsx
- packages/superset-ui-control-utils/src/InfoTooltipWithTrigger.tsx
- packages/superset-ui-control-utils/src/index.ts
- packages/superset-ui-control-utils/src/shared-controls.tsx
- packages/superset-ui-control-utils/test/ColumnOption.test.tsx
- packages/superset-ui-control-utils/test/ColumnTypeLabel.test.tsx
🐛 Bug Fix
🏠 Internal
`export { xxx as }` [throws a "type not found" warning](https://github.com/babel/babel/issues/8639) in babel.
```
WARNING in ./node_modules/@superset-ui/control-utils/src/index.ts 11:0-104
"export 'Column' (reexported as 'ColumnOptionColumn') was not found in './ColumnOption'
WARNING in ./node_modules/@superset-ui/control-utils/src/index.ts 13:0-50
"export 'Metric' was not found in './mainMetric'
WARNING in ./node_modules/@superset-ui/control-utils/src/index.ts 11:0-104
"export 'Props' (reexported as 'ColumnOptionProps') was not found in './ColumnOption'
WARNING in ./node_modules/@superset-ui/control-utils/src/index.ts 12:0-83
"export 'Props' (reexported as 'ColumnTypeLabelProps') was not found in './ColumnTypeLabel'
```
We should probably avoid reexporting with …
> style(control-utils): fix type reexport warning in babel

- plugins/legacy-preset-chart-nvd3/src/PropTypes.js
🐛 Bug Fix
The PropType for `annotationLayerType.value` is missing `string` type required for formulas, causing warnings:
> fix: annotation PropType for formula annotations

- package.json
- scripts/build.js
🐛 Bug Fix
Sometimes build a single package via `yarn build "*package-name"` does not update rebuild the type declaration files. This PR fixes it by cleaning the existing built files first.
> build: fix typing rebuild for single packages

- packages/superset-ui-demo/.storybook/main.js
- Only print minimal webpack stats when in development mode
- Separate type checking and build, so failed typing does not block `yarn storybook` watch rebuild
- Add source map for storybook built code
- Rearrange addon loading order so knobs can appear as the first tab
🏆 Enhancements
🏠 Internal
> build: optimize storybook config

- package.json
🏆 Enhancements
🏠 Internal
Clean up `package-lock.json` before `lerna` release commands to increase chances of success.
> build: clean package-lock.json before release

- packages/superset-ui-color/src/colorSchemes/categorical/superset.ts
> fix: got one color wrong when copy pasting

- packages/superset-ui-chart-controls/package.json
- packages/superset-ui-chart-controls/src/components/RadioButtonControl.tsx
- packages/superset-ui-chart-controls/src/index.ts
- packages/superset-ui-chart-controls/src/shared-controls/components.tsx
- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
- packages/superset-ui-chart-controls/src/types.ts
- packages/superset-ui-chart-controls/src/utils/expandControlConfig.tsx
- packages/superset-ui-chart-controls/src/utils/selectOptions.ts
- packages/superset-ui-chart-controls/test/utils/expandControlConfig.test.tsx
- plugins/legacy-plugin-chart-table/package.json
- plugins/legacy-plugin-chart-table/src/RadioButtonControl.tsx
- plugins/legacy-plugin-chart-table/src/controlPanel.tsx
- plugins/plugin-chart-table/src/controlPanel.tsx
- plugins/plugin-chart-table/src/transformProps.ts
🏆 Enhancements
Rearrange form controls for Table chart, replace GROUP BY and NOT GROUP BY with a "Query Mode" switch.
Added to both the legacy table and [the new table chart](https://github.com/apache-superset/superset-ui/pull/584).
Superset app also need to be updated to accept the frontend passing in both `all_columns` and `metrics`.
Related: https://github.com/apache/incubator-superset/pull/10113
> feat(legacy-table-chart): add query mode switch

- plugins/legacy-plugin-chart-country-map/package.json
🏠 Internal
Move `@superset-ui/chart-controls` to `peerDependencies` as `lerna create-patch-version` will always used fixed versions and would cause duplicate installations when a parent app updates `@superset-ui/chart-controls` but forgot to update `legacy-plugin-chart-country-map`.
cc @rusackas @pkdotson
> chore(legacy-plugin-chart-country-map): use peerDependencies

- plugins/plugin-chart-table/package.json
- yarn.lock
🏠 Internal
This is what Superset app will install anyway (when installing `@superset-ui/plugin-chart-table @ ^0.14.2`).
> chore: upgrade react-table to v7.2.1

- plugins/plugin-chart-table/src/controlPanel.tsx
🐛 Bug Fix
Change default query mode for table chart from `aggregate` to `null` so it can fallback to `getQueryMode` to have better backward compatibility. Currently existing tables in NOT GROUP BY mode will not open the "Raw" tab by default.
Also change `getQueryMode` to use `raw` when `all_columns` is present, to be consistent with the backend.
Will add a Cypress test in Superset
cc @etr2460 @kristw
> fix(plugin-chart-table): change default queryMode to null

- packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/birthNames.json
- plugins/plugin-chart-table/src/utils/formatValue.ts
🐛 Bug Fix
Re-enable table chart to create anchor element with link.
Storybook
> fix(plugin-chart-table): anchor should keep href

- packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/TableStories.tsx
- packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/testData.ts
- plugins/plugin-chart-table/src/transformProps.ts
- plugins/plugin-chart-table/src/types.ts
- yarn.lock
🐛 Bug Fix
Non-numeric metrics shouldn't be passed to the numeric filter or "adaptive dates" time formatter.
- Added storybook
- Tested in Superset
- Added Cypress tests in Superset: https://github.com/apache-superset/superset-ui/pull/663/files
> fix(plugin-chart-table): formatting non-numeric metrics

- package.json
- packages/superset-ui-chart/src/clients/ChartClient.ts
- packages/superset-ui-connection/src/SupersetClientClass.ts
- packages/superset-ui-connection/src/callApi/callApi.ts
- packages/superset-ui-connection/src/types.ts
- packages/superset-ui-connection/test/callApi/callApi.test.ts
- packages/superset-ui-connection/test/callApi/callApiAndParseWithTimeout.test.ts
- packages/superset-ui-demo/storybook/shared/components/VerifyCORS.tsx
- packages/superset-ui-demo/storybook/stories/superset-ui-connection/ConnectionStories.tsx
- packages/superset-ui-query/src/api/types.ts
- packages/superset-ui-query/src/api/v1/postChartData.ts
🏆 Enhancements
Provide an easier API to send JSON requests. So instead of
```js
await SupersetClient.post({
url: '/api/v1/chart/data',
headers: { 'Content-Type': 'application/json' },
body: JSON.stringify({
query_context: ...
}),
});
```
users can just do
```js
await SupersetClient.post({
url: '/api/v1/chart/data',
jsonPayload: {
query_context: ...
},
});
```
Also make `postPayload` (and `jsonPayload`) accept strings, which will be automatically parsed as a JSON object.
- Test locally with storybook
- Added an additional unit test
> feat(connection): easier API for json payload

- plugins/plugin-chart-table/src/Styles.tsx
- plugins/plugin-chart-table/src/transformProps.ts
- plugins/plugin-chart-table/src/utils/DateWithFormatter.ts
- plugins/plugin-chart-table/test/TableChart.test.tsx
- yarn.lock
🐛 Bug Fix
1. Fix `getTime` undefined error when sorting a time column in table chart. Also refactors how datetime is handled for `react-table` search, sort and render methods.
2. Fix spacing issue for table pagination in dashboards
**Before:**
**After:**
Unit test in superset-ui and E2E test in superset-frontend.
cc @serenajiang @kristw
> fix(plugin-chart-table): sort and search time column

- plugins/legacy-plugin-chart-calendar/src/controlPanel.js
- plugins/legacy-plugin-chart-event-flow/src/controlPanel.jsx
- plugins/legacy-plugin-chart-paired-t-test/src/controlPanel.ts
- plugins/legacy-plugin-chart-rose/src/controlPanel.jsx
- plugins/legacy-preset-chart-nvd3/src/Area/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/Bar/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/Bullet/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/Compare/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/DualLine/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/Line/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/LineMulti/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/TimePivot/controlPanel.ts
🏆 Enhancements
This property doesn't seem to be needed, or indeed used anywhere. Clearing it out! 🗑
See also: https://github.com/apache/incubator-superset/pull/10259
🐛 Bug Fix
🏠 Internal
> chore: requiresTime not required

- plugins/legacy-plugin-chart-treemap/src/Treemap.js
🐛 Bug Fix
The string literal on the legacy Treemap viz was missing a `$` sign, causing the expression to be written literally.
> fix(legacy-plugin-chart-treemap): incorrect template literal

- plugins/legacy-plugin-chart-rose/src/controlPanel.jsx
🏆 Enhancements
Add time grain to Rose Chart.
> feat(legacy-plugin-chart-rose): add time grain

- plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
🐛 Bug Fix
Currently pivot table tries to numerically format all metric values, irrespective of their format. This is because we're checking if the cell value is not NaN by calling `Number.isNaN()` on the cell value, which will always be false:
```javascript
> Number.isNaN('1.1')
false
> Number.isNaN('1')
false
> Number.isNaN('abc')
false
```
Instead we should first try to parse the value to float:
```javascript
> Number.isNaN(parseFloat('1.1'))
false
> Number.isNaN(parseFloat('1'))
false
> Number.isNaN(parseFloat('abc'))
true
```
This also makes the rest of the if-clause irrelevant:
```javascript
> Number.isNaN(parseFloat(''))
true
> Number.isNaN(parseFloat('null'))
true
```
In the example below, the metric `MAX(party)` is non-numeric, while `SUM(voter)` is numeric.
> fix(legacy-plugin-chart-pivot-table): formatting non-numeric values

- packages/superset-ui-query/src/buildQueryObject.ts
- packages/superset-ui-query/src/extractExtras.ts
- packages/superset-ui-query/src/processFilters.ts
- packages/superset-ui-query/src/types/Operator.ts
- packages/superset-ui-query/src/types/QueryFormData.ts
- packages/superset-ui-query/test/convertFilter.test.ts
- packages/superset-ui-query/test/extractExtras.test.ts
- packages/superset-ui-query/test/processFilters.test.ts
- packages/superset-ui-query/test/types/Filter.test.ts
🐛 Bug Fix
This fixes three bugs:
1) The equals filter operator was incorrectly a single equals sign. The correct format is double equals signs. This holds true both for simple filters and adhoc filters. Tests updated accordingly.
2) regular (non-reserved) filters from `extra_filters` were being doubly populated in `processFilters`. Bug fixed + test added.
3) `time_range_endpoints` weren't being passed through to `extras`.
A screenshot of an ad-hoc filter's metadata with the equals-operator:
A screenshot of the filter operators that the backend expects filters to comply with (`superset/utils/core.py`):
A screenshot of how `viz.py` populates extras in `query_obj` from `form_data`:
`TimeRangeEndpoints` enum expected in backend:
> fix(query): equals operator, duplicate filters and time range endpoints

- plugins/legacy-plugin-chart-world-map/src/WorldMap.js
- plugins/legacy-plugin-chart-world-map/src/transformProps.js
- plugins/plugin-chart-table/src/DataTable/hooks/useSticky.tsx
🐛 Bug Fix
Some charts rely on the dimension of mounted chart containers (`container.clientWidth` and `container.clientHeight`), but both values are zero when Bootstrap tabs are still animating. The unfortunate timing leads to some charts unable to re-render when switching tabs after applying filters (see apache/incubator-superset#10349 ).
Ideally we should fix the [Tabs](https://github.com/apache/incubator-superset/blob/221f38099b1a1a93cd0a3fd6b717f9fdce0b4e18/superset-frontend/src/dashboard/components/gridComponents/Tabs.jsx#L239) component and only re-render charts when animation finishes but I was not able to find a clean way to do that, so fixing the known broken charts instead.
Manual testing
> fix: charts rerender with zero-height during tab switch

- plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
- plugins/legacy-preset-chart-nvd3/src/Pie/controlPanel.ts
🏆 Enhancements
add a new label type that can display key value and percent
Signed-off-by: Stuart Hu <shijiehu@improbable.io>
> feat(legacy-preset-chart-nvd3): add a new label type to pie chart

- plugins/legacy-plugin-chart-sunburst/src/Sunburst.js
- plugins/legacy-plugin-chart-sunburst/src/controlPanel.ts
- plugins/legacy-plugin-chart-sunburst/src/transformProps.js
🏆 Enhancements
Currently sunburst chart uses a linear color scheme when using a secondary metric that can't be customized. This adds a linear color control and uses that when the secondary metric is defined.
> feat(legacy-plugin-chart-sunburst): add linear color scheme

- packages/superset-ui-connection/src/callApi/rejectAfterTimeout.ts
- packages/superset-ui-connection/test/callApi/callApiAndParseWithTimeout.test.ts
🐛 Bug Fix
We're accidentally hardcoding the timeout value in Superset proper, this provides us a way to get the timeout easily, instead of needing to fetch it from one of many possible redux stores.
to: @ktmud @kristw
> fix: add timeout value to error details in rejectAfterTimeout

- packages/superset-ui-style/src/index.ts
🏆 Enhancements
Seemed like in general, we should be using `css` from this superset package, rather than from `emotion` directly. That means we have a better pivot point, if we ever have the need to migrate to `styled-components` or some other thing down the road.
🐛 Bug Fix
🏠 Internal
> feat: style pkg exports emotion's css module

- .github/workflows/ci.yml
🏠 Internal
Codecov uploads [have been failing](https://github.com/apache-superset/superset-ui/pull/711/checks?check_run_id=942885439) <strike>for no reason</strike> (because of missing GITHUB_ACTION env variables).
Trying to fix it by:
1. Fix to build on `ubuntu-18.04`
2. Manually add `GITHUB_ACTION` and `CODECOV_TOKEN` env variables.
> build: upgrade codecov-action and disable failing_ci_if_error

- plugins/legacy-plugin-chart-world-map/package.json
- plugins/legacy-plugin-chart-world-map/src/WorldMap.js
- plugins/legacy-plugin-chart-world-map/src/controlPanel.js
- plugins/legacy-plugin-chart-world-map/src/transformProps.js
> feat: improve world map colors

- packages/superset-ui-core/src/utils/logging.ts
- packages/superset-ui-core/test/utils/logging.test.ts
🏆 Enhancements
Supports console.table safely :)
🐛 Bug Fix
🏠 Internal
> feat: logger supports console.table, with console.log fallback

- plugins/legacy-plugin-chart-pivot-table/package.json
- plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
- plugins/legacy-plugin-chart-pivot-table/src/controlPanel.js
- plugins/legacy-plugin-chart-pivot-table/src/transformProps.js
🏆 Enhancements
This adds support for formatted dates on `pivot-table`. This is done by prefixing date values with `__timestamp:`, after which they can be identified and parsed into formattable date objects. In addition sorting is done based on the epoch value, meaning that the format won't affect the sorting order. Other changes:
- Add date format
- Move visual options to own tab (currently on `Query` pane)
- use time grain for formatting if smart formatting is selected
- make sorting of numeric values based on the parsed float value, not the text value
> feat(legacy-plugin-chart-pivot-table): add support for timestamp format

- package.json
- packages/superset-ui-demo/.storybook/preview.js
- packages/superset-ui-demo/package.json
- plugins/plugin-chart-choropleth-map/package.json
- plugins/plugin-chart-choropleth-map/src/configureEncodable.ts
- plugins/plugin-chart-choropleth-map/src/index.ts
- plugins/plugin-chart-word-cloud/package.json
- plugins/plugin-chart-word-cloud/src/configureEncodable.ts
- plugins/plugin-chart-word-cloud/src/index.ts
- plugins/preset-chart-xy/package.json
- plugins/preset-chart-xy/src/configureEncodable.ts
- plugins/preset-chart-xy/src/index.ts
- yarn.lock
🏠 Internal
* Bump `encodable` to latest version which no longer has nested dependency to `@superset-ui/color`, `@superset-ui/number-format` and `@superset-ui/time-format`.
* By default `encodable` ships with its own color and formatter registries. This PR include shims to point to the same registries that `@superset-ui` is using, so the specified formats and colorScheme from control panel can be correctly used. Have to call this shim function in the setup.
* There are multiple copies of the same shim in each package at the moment. It could be extracted to a new package, but seems like an overkill for this first pass.
* I may also refactor `@superset-ui/colors,number-format,time-format` later to use the same underlying registries so the shim won't be necessary.
scatter plot working
word …
> build: update encodable dependency

- packages/superset-ui-chart-controls/src/components/CertifiedIconWithTooltip.tsx
- packages/superset-ui-chart-controls/src/components/MetricOption.tsx
🏆 Enhancements
Builds from https://github.com/apache/incubator-superset/pull/10630 to add the certification icon into the MetricOption component. Unfortunately there's some code duplication here as the main Icon component is in incubator-superset. In the future we'll want to move icons into superset-ui I think.
Test Plan:
`npm link` to incubator-superset, test with a certified metric and an uncertified metric
to: @ktmud @graceguo-supercat
> feat: add certification icon to metrics

- packages/superset-ui-chart-controls/src/components/MetricOption.tsx
🏆 Enhancements
🐛 Bug Fix
Explore had a bunch of console warnings going on since various implementations of <MetricOption> did not provide all the props that the TS definition had listed as mandatory. This loosens up the typing so the console is less painful to look at :)
🏠 Internal
> chore: silencing console errors by making MetricOption props optional

- packages/superset-ui-chart-controls/src/components/MetricOption.tsx
- packages/superset-ui-chart-controls/src/index.ts
- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
- packages/superset-ui-chart-controls/src/types.ts
- packages/superset-ui-chart-controls/src/utils/mainMetric.ts
- packages/superset-ui-translation/src/Translator.ts
- plugins/legacy-plugin-chart-time-table/src/TimeTable.tsx
- plugins/legacy-plugin-chart-time-table/src/transformProps.ts
- yarn.lock
🏠 Internal
Clean up a couple of TypeScript warnings and @ts-ignore directives.
cc @pkdotson @etr2460 @kristw
> chore: clean up a couple of TypeScript warnings

- packages/superset-ui-color/src/colorSchemes/categorical/echarts.ts
- packages/superset-ui-color/src/colorSchemes/sequential/common.ts
- packages/superset-ui-color/test/colorSchemes.test.ts
- packages/superset-ui-demo/storybook/stories/superset-ui-color/ColorPallettesStories.jsx
🏆 Enhancements
Add ECharts 4.x and 5.x official color schemes.
4.x: https://github.com/apache/incubator-echarts/blob/eb396f27137af1d74b42b1b28752f204a34dbecf/src/model/globalDefault.js#L36-L41
5.x: https://github.com/apache/incubator-echarts/blob/4c916f527f211a34c8dd5555c23870db25a78b05/src/model/globalDefault.ts#L42-L55
Categorical:
Sequential:
Ping @Ovilia
> feat(color): add official ECharts color schemes

- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
🏆 Enhancements
add `tooltip.confine = true`
https://echarts.apache.org/en/option.html#tooltip.confine
(cc @villebro @ktmud)
BEFORE:
AFTER:
> fix: add Echarts tooltip confine

- plugins/legacy-preset-chart-nvd3/src/Area/controlPanel.ts
🐛 Bug Fix
For some reason the color scheme was set to `renderTrigger: false`, causing the whole "Chart Options" section to be moved to the front pane an require refetching data from the backend.
> fix(legacy-preset-chart-nvd3): remove unnecessary control override

- packages/superset-ui-chart-controls/src/components/MetricOption.tsx
🏠 Internal
Make `url` optional to suppress a `propTypes` check warning.
> chore: url prop for MetricOption should be optional

- packages/superset-ui-chart-controls/package.json
- packages/superset-ui-core/package.json
- packages/superset-ui-demo/package.json
- plugins/legacy-plugin-chart-time-table/package.json
- plugins/plugin-chart-choropleth-map/package.json
- plugins/plugin-chart-table/package.json
- plugins/plugin-chart-word-cloud/package.json
- yarn.lock
🏠 Internal
move @types/react to peerDependencies otherwise `npm link` will install `@types/react` in both ``superset-frontend/node_modules/@types/react` and `superset-frontned/@node_modules/@superset-ui/xxxx/node_modules/@types/react`. TSC (`npm run dev-server`) may throw errors with duplicate `@types/react` installations.
> chore: move @types/react to peerDependencies

- package.json
- plugins/legacy-plugin-chart-calendar/tsconfig.json
- plugins/legacy-plugin-chart-chord/tsconfig.json
- plugins/legacy-plugin-chart-country-map/tsconfig.json
- plugins/legacy-plugin-chart-event-flow/tsconfig.json
- plugins/legacy-plugin-chart-force-directed/tsconfig.json
- plugins/legacy-plugin-chart-heatmap/tsconfig.json
- plugins/legacy-plugin-chart-histogram/tsconfig.json
- plugins/legacy-plugin-chart-horizon/tsconfig.json
- plugins/legacy-plugin-chart-map-box/tsconfig.json
- plugins/legacy-plugin-chart-paired-t-test/tsconfig.json
- plugins/legacy-plugin-chart-parallel-coordinates/tsconfig.json
- plugins/legacy-plugin-chart-partition/tsconfig.json
- plugins/legacy-plugin-chart-pivot-table/tsconfig.json
- plugins/legacy-plugin-chart-rose/tsconfig.json
- plugins/legacy-plugin-chart-sankey-loop/tsconfig.json
- plugins/legacy-plugin-chart-sankey/tsconfig.json
- plugins/legacy-plugin-chart-sunburst/tsconfig.json
- plugins/legacy-plugin-chart-time-table/tsconfig.json
- plugins/legacy-plugin-chart-treemap/tsconfig.json
- plugins/legacy-plugin-chart-world-map/tsconfig.json
- plugins/legacy-preset-chart-big-number/tsconfig.json
- plugins/legacy-preset-chart-nvd3/tsconfig.json
- plugins/plugin-chart-choropleth-map/tsconfig.json
- plugins/plugin-chart-echarts/tsconfig.json
- plugins/plugin-chart-table/tsconfig.json
- plugins/plugin-chart-word-cloud/tsconfig.json
- plugins/preset-chart-xy/tsconfig.json
- scripts/build.js
- tsconfig.options.json
🏆 Enhancements
🏠 Internal
From TypeScript [handbook](https://www.typescriptlang.org/docs/handbook/compiler-options.html):
```
--skipLibCheck       Skip type checking of all declaration files (*.d.ts).
```
This cuts build-time for `tsc` in half. Most TS errors can still be captured by ESLint.
Also limit `typeRoots` to `./node_modules` in the root folder so to reduce chances of type conflicts from `packages/*` and `plugins/*`.
> build: enable skipLibCheck for tsc

- packages/superset-ui-chart-controls/src/utils/columnChoices.ts
- packages/superset-ui-core/src/chart/types/QueryResponse.ts
- plugins/legacy-plugin-chart-event-flow/src/EventFlow.tsx
- plugins/legacy-plugin-chart-event-flow/src/controlPanel.tsx
- plugins/legacy-plugin-chart-event-flow/src/index.ts
- plugins/legacy-plugin-chart-event-flow/src/transformProps.ts
- plugins/legacy-plugin-chart-event-flow/src/types/external.d.ts
- plugins/plugin-chart-echarts/src/Timeseries/types.ts
- plugins/plugin-chart-echarts/src/utils/prophet.ts
- plugins/plugin-chart-echarts/src/utils/series.ts
Found some bad imports that were not captured by CI, neither ESLint nor tsc, decided to convert the whole package to TypeScript so we will have less such errors in the future.
> refactor: convert legacy-plugin-chart-event-flow to typescript

- plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
🐛 Bug Fix
nvd3 css was deleted by accident in #768
> fix: add back nvd3 missing css

- plugins/legacy-plugin-chart-calendar/package.json
- plugins/legacy-plugin-chart-event-flow/package.json
- plugins/legacy-plugin-chart-rose/package.json
- plugins/plugin-chart-echarts/package.json
🏠 Internal
Move all superset-ui/core deps out of peerDependencies so that `lerna` can update the dep versions automatically, avoiding "unmet peerDependency" errors in `incubator-superset`.
> chore: move all superset-ui/core deps out of peerDependencies

- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
🏆 Enhancements
Removes the 50 ms wait on the Timeseries chart tooltip.
> feat(plugin-chart-echarts): remove loading from timeseries tooltip

- packages/superset-ui-chart-controls/src/types.ts
🏆 Enhancements
More typing optimization for DatasourceMeta in chart-controls. We needed `datasource.id` for our internal Superset. But I decided to add more fields.
Fields are verified existent by examining component using React Dev Tools.
> chore: add more props to DatasourceMeta for chart-controls

- plugins/plugin-chart-word-cloud/src/chart/WordCloud.tsx
- plugins/plugin-chart-word-cloud/src/plugin/index.ts
- plugins/preset-chart-xy/src/BoxPlot/index.ts
🐛 Bug Fix
Currently the selected color scheme isn't being respected. This is probably a regression from #768.
> fix(plugin-chart-word-cloud): make colors schemes work

- plugins/plugin-chart-echarts/src/Pie/transformProps.ts
- plugins/plugin-chart-echarts/src/constants.ts
- plugins/plugin-chart-echarts/src/utils/series.ts
- plugins/plugin-chart-echarts/test/utils/series.test.ts
🏆 Enhancements
Adds proper support for non-string labels to ECharts Pie chart, especially for numeric, temporal and `NULL` types.
> feat(plugin-chart-echarts): add more robust formatting for series

- plugins/legacy-plugin-chart-sankey-loop/src/controlPanel.js
🏆 Enhancements
🐛 Bug Fix
Some folks pointed out the Sankey Loop plugin wasn't working... welp, it has no controls! This copies the control panel over from the regular Sankey plugin. Calling this a Draft PR until I (or anyone) can confirm this actually works.
🏠 Internal
> fix: copying controls from Sankey to Sankey Loop

- plugins/plugin-chart-echarts/src/Timeseries/buildQuery.ts
- plugins/plugin-chart-echarts/src/Timeseries/controlPanel.ts
- plugins/plugin-chart-echarts/test/Timeseries/buildQuery.test.ts
- plugins/plugin-chart-echarts/test/Timeseries/transformProps.test.ts
🐛 Bug Fix
Fix a regression caused by party contradictory naming in controls/buildQuery.
> fix(plugin-chart-echarts): fix incorrect groupby in buildQuery

- plugins/plugin-chart-echarts/src/BoxPlot/buildQuery.ts
- plugins/plugin-chart-echarts/src/BoxPlot/types.ts
🏠 Internal
Rename `type` to `whisker_type` on BoxPlot post processing op.
> chore(plugin-chart-echarts): rename boxplot type to whisker_type

- plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
🐛 Bug Fix
Currently it's not possible to change the number formatting for when "contribution" is checked or using percentage comparison in line charts.
Let's allow that.
1. Go to a line chart in Superset
2. Check contribution or select a percentage comparison
3. Change y axis format in "Customize"
The format should apply. If there is not format selected or is using the default "Adaptive Formatting", the format should be 1 decimal percentages.
> fix(legacy-preset-chart-nvd3): custom yAxisFormat for contribution

- packages/superset-ui-core/src/query/extractExtras.ts
- packages/superset-ui-core/src/query/types/Query.ts
- packages/superset-ui-core/src/query/types/Time.ts
- packages/superset-ui-core/test/query/extractExtras.test.ts
🏆 Enhancements
Add `applied_time_extras` to `QueryObject` to be able to identify which filters have been set/overridden by `extra_filters`. Please see https://github.com/apache/incubator-superset/pull/11325 for additional context.
> feat(core): add applied_time_extras to QueryObject

- plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
🐛 Bug Fix
The default `yAxisBounds` are currently set to `null`, which evaluate to zero when passed to the `Number` function: (`Number(null) === 0`). The defaults were copied from the NVD3 control panel, but apparently there evaluating to zero isn't a problem.
> fix(plugin-chart-echarts): fix default y axis bounds

- packages/superset-ui-core/src/query/buildQueryObject.ts
- packages/superset-ui-core/src/query/index.ts
- packages/superset-ui-core/src/query/types/AnnotationLayer.ts
- packages/superset-ui-core/src/query/types/Query.ts
- packages/superset-ui-core/src/query/types/QueryFormData.ts
- packages/superset-ui-core/test/query/buildQueryObject.test.ts
- packages/superset-ui-core/test/query/types/AnnotationFilter.test.ts
Add support for `url_params` and `annotation_layers` to `QueryFormData` and `QueryObject`. The `AnnotationLayer` schema corresponds to that generated by `AnnotationLayerControl` in `superset-ui`.
> feat(core): add support for annotations and url params

- plugins/plugin-chart-echarts/src/Pie/transformProps.ts
🏆 Enhancements
Disable animation in Pie Chart.
> fix(plugin-chart-echarts): disable pie chart animation

- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/utils/controls.ts
- plugins/plugin-chart-echarts/test/utils/controls.test.ts
🐛 Bug Fix
Currently the `YAxisBoundsControl` will initialize with `null` values despite being passed `undefined`, causing trouble when setting the y axis bounds. This improves the parsing of said values prior to using them so Y-axis bounds are always either undefined or valid values.
> fix(plugin-chart-echarts): improve yAxisBounds parsing

- plugins/legacy-plugin-chart-sankey/src/controlPanel.ts
🏆 Enhancements
Adding a "Sort by metric" checkbox control for Sankey chart. If selected, the query results will be sorted by metric in descending order. This is useful when there are many rows of data but it's not easy to regroup source and targets via custom SQL queries (e.g. when working with a datasource that does not support arbitrary SQL queries).
Also added a caveat warning for row limit:
> feat(legacy-plugin-chart-sankey): allow sort by metric

- plugins/legacy-preset-chart-nvd3/package.json
- plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
- plugins/plugin-chart-echarts/package.json
- yarn.lock
Bump `mathjs` to the latest version (`8.0.1`) and make required code changes. Verified to work locally.
> chore: bump mathjs to latest version on all plugins

- plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
🐛 Bug Fix
Currently null values are displayed as `null` in the table. This changes the label to empty, and treats the null value as `Number.NEGATIVE_INFINITY` on sort.
> fix(legacy-plugin-chart-pivot-table): remove nulls from table

- packages/superset-ui-core/src/chart/components/SuperChart.tsx
- packages/superset-ui-core/src/chart/models/ChartProps.ts
- packages/superset-ui-core/test/chart/components/SuperChart.test.tsx
🏆 Enhancements
Gives opportunity to get multi queries response results from incubator:
See PR: https://github.com/apache/incubator-superset/pull/11880/files
> feat: support multi queries request

- packages/superset-ui-demo/storybook/stories/plugins/legacy-preset-chart-nvd3/Compare/Stories.tsx
- packages/superset-ui-demo/storybook/stories/plugins/legacy-preset-chart-nvd3/Compare/stories/timeFormat.tsx
- plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
- plugins/legacy-preset-chart-nvd3/src/utils.js
- yarn.lock
🐛 Bug Fix
Fix #795 and #799 
For the `compare` chart in Superset or the `cumulativeLineChart` (from nvd3), the time is passed to the tooltip as a formatted time string. There is no way to customize the format unlike other chart types. Trying to apply a time format function on a string resulting in `0NaN`. 
This fix will at least make the tooltip has same format with the x-axis, better than `0NaN`.
Also add storybook example for verification
The stacked area chart has 3 stacked style, the `expand` style pass data to tooltip slightly differently from the other two. It does not include a total row. This PR fix the total number calculation for `expand` case.
> fix(legacy-preset-chart-nvd3): time compare and stacked area tooltips

- packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Pie/Stories.tsx
- plugins/plugin-chart-echarts/package.json
- plugins/plugin-chart-echarts/src/Pie/controlPanel.ts
- plugins/plugin-chart-echarts/src/Pie/transformProps.ts
- plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
- plugins/plugin-chart-echarts/src/components/Echart.tsx
- yarn.lock
🏆 Enhancements
Bump ECharts to 5.0.0. Changes:
- Pie: Increase default outer radius from 50 % to 80 %, as it handles resizing much better.
- Pie: Remove show label threshold prop, as labels that don't fit are automatically dropped.
- Pie: activate label line by default and only render lines if labels are set to be outside.
- Timeseries: Minor refactor to marker props.
Pie:
Boxplot:
Timeseries:
> feat(plugin-chart-echarts): bump to version 5.0

- .github/workflows/chromatic.yml
🏆 Enhancements
now that https://github.com/apache-superset/superset-ui/pull/849 has merged and the actions code is in master, we can rely on `pull_request_target` for any changes. `pull_request` will fail for any PR that comes from a fork as it will not have access to secrets needed to upload the chromatic output. 
more info on `pull_request_target` here https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks
> ci: remove `pull_request` trigger

- plugins/legacy-preset-chart-nvd3/src/LineMulti/LineMulti.jsx
🐛 Bug Fix
Fixes https://github.com/apache/incubator-superset/issues/11889. State of `LineMulti` was passed through props to another component and modified there, which caused an infinite loop if re-renders. Now we pass a deep copy of state instead of the original object.
Before: see gif in https://github.com/apache/incubator-superset/issues/11889
After: the chart is stable after rendering
@rusackas Can you please take a look?
> fix(legacy-preset-chart-nvd3): make deep copy of queryData

- packages/superset-ui-core/src/connection/SupersetClientClass.ts
🐛 Bug Fix
Following the thread 
https://github.com/apache-superset/superset-ui/issues/866#issuecomment-745503482
I propose this PR to use the default fetchRetryOptions in the SupersetClientClass.
Thanks
Mario
> fix: add fetchRetryOptions in SupersetClientClass.request method

- plugins/plugin-chart-word-cloud/src/chart/WordCloud.tsx
While resizing chart sometimes top results were filtered out because their sizes were too big. This
solution makes sure that top 10% of results will always be displayed by gradually scaling down the
chart if needed.
fix apache/incubator-superset#11784
🐛 Bug Fix
Before:
After:
Issues associated with this bug were reported in D3 library and not completely solved yet.
[- most important words (highest counts) missing if they don't fit](https://github.com/jasondavies/d3-cloud/issues/36)
[- missing words in final layout](https://github.com/jasondavies/d3-cloud/issues/159)
The cost of my workaround solution may be slower pace of displaying the chart while resizing.
cc @villebro
> fix(plugin-chart-word-cloud): ensure top results are always displayed

- plugins/plugin-chart-echarts/src/BoxPlot/buildQuery.ts
- plugins/plugin-chart-echarts/test/BoxPlot/buildQuery.test.ts
🐛 Bug Fix
Make sure `columns` property isn't defined in `formData`, as it is a reserved parameter with a specific meaning in `QueryObject`.
> fix(plugin-chart-echarts): remove columns from formData

- plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
Remove chart margin-left to fit last label
BEFORE
AFTER
@ktmud @villebro @rusackas 
Fix: https://github.com/apache/superset/issues/12513
> fix: subject Remove margin to fit last label

- plugins/legacy-preset-chart-nvd3/src/DualLine/controlPanel.ts
- plugins/legacy-preset-chart-nvd3/src/NVD3Controls.tsx
- plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
Add legend options for nvd3 with default false, The only chart that misses the legend option is Dual Line
related to: https://github.com/apache-superset/superset-roadmap/issues/92
> feat(legacy-preset-chart-nvd3): subject Add legend option to dual line chart

- packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Pie/Stories.tsx
- plugins/plugin-chart-echarts/src/Pie/controlPanel.tsx
- plugins/plugin-chart-echarts/src/Pie/transformProps.ts
- plugins/plugin-chart-echarts/src/Pie/types.ts
- plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/Timeseries/types.ts
- plugins/plugin-chart-echarts/src/controls.ts
- plugins/plugin-chart-echarts/src/defaults.ts
- plugins/plugin-chart-echarts/src/types.ts
- plugins/plugin-chart-echarts/src/utils/series.ts
- plugins/plugin-chart-echarts/test/Pie/transformProps.test.ts
- plugins/plugin-chart-echarts/test/utils/series.test.ts
🏆 Enhancements
Currently ECharts has limited functionality for automatically resizing the chart area based on the legend, causing overflowing. This PR adds the possibility to
- Enable/disable legend on Timeseries chart (default: disabled)
- Change legend type (scroll, plain) (default: scroll)
- Change orientation of legend (top, bottom, left, right) on Pie and Timeseries (default: top)
- Define custom legend padding (default: 20 for top/bottom, 170 for left/right)
The custom padding option will be removed once automatic component resizing is implemented in ECharts. Also cleans up default props for ECharts Pie (should really be in a separate PR, apologies for that).
Currently there's no way of disabling the legend
Now the legend is disabled by default
When enabled, it defaults to scroll …
> feat(plugin-chart-echarts): add legend customization options

- plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
- plugins/legacy-preset-chart-nvd3/src/utils.js
🐛 Bug Fix
This fixes an issue where the rich tooltip text will overflow outside of the tooltip box in Superset.
Before:
After:
This fixes Superset issue 12688 https://github.com/apache/superset/issues/12688
> fix: remove max-width from tooltip div

- packages/superset-ui-core/src/query/buildQueryObject.ts
- packages/superset-ui-core/src/query/extractQueryFields.ts
- packages/superset-ui-core/src/query/types/Query.ts
- packages/superset-ui-core/src/query/types/QueryFormData.ts
- packages/superset-ui-core/test/query/extractQueryFields.test.ts
- plugins/plugin-chart-table/src/buildQuery.ts
- plugins/plugin-chart-table/src/controlPanel.tsx
🏆 Enhancements
🐛 Bug Fix
Add `orderby` to `extractQueryFields`, which consolidates query options related to generating actual SQL queries. 
This should also fix sorting options in table chart. Previously each plugin has to do the `order_by_choices` parsing themselves (e.g. in [the now deprecated old new table chart](https://github.com/apache-superset/superset-ui/blob/master/temporary-plugins/hold-potentially-deprecate/superset-ui-plugin-chart-table/src/buildQuery.ts#L12-L22)), I figure it'd be useful to make this global, in case we want to support query mode switch for other viz types.
Related: #889 https://github.com/apache/superset/pull/10270
> feat(core): add orderby to extractQueryFields

- packages/superset-ui-chart-controls/package.json
- packages/superset-ui-chart-controls/src/components/ColumnOption.tsx
- packages/superset-ui-chart-controls/src/components/InfoTooltipWithTrigger.tsx
- packages/superset-ui-chart-controls/src/components/Tooltip.tsx
- packages/superset-ui-chart-controls/test/components/InfoTooltipWithTrigger.test.tsx
Replace RB Tooltips with Antd in `InfoTooltipWithTrigger` to unify UI, wrap metric name in a tooltip.
Change in `InfoTooltipWithTrigger` may affect multiple components in Explore
CC: @villebro
> fix(chart-controls): add a tooltip to span in ColumnOption, refactor RB Tooltips to Antd

- plugins/plugin-chart-table/src/buildQuery.ts
- plugins/plugin-chart-table/test/buildQuery.test.ts
🐛 Bug Fix
Table chart should not send `post_processing` when in raw records mode.
Closes https://github.com/apache/superset/issues/12853
Added new unit tests
To test in Superset, go to the "Games" sample chart:
Which has a Raw Records query, the `global_sales` should display the same value as in the data samples.
> fix(plugin-chart-table): unnecessary post_processing in raw records mode

- plugins/plugin-chart-table/src/buildQuery.ts
- plugins/plugin-chart-table/src/types.ts
- plugins/plugin-chart-table/src/utils/extractOrderby.ts
- plugins/plugin-chart-table/test/utils.test.ts
🐛 Bug Fix
Previously table chart would by default order by the first metric if no sort order was specified. This replicates the logic from the old `viz.py` implementation and also fixes a few minor issues in the current code:
- Infer `queryMode` from `formData` contents; if it's undefined and `metrics` is not empty, assume `QueryMode.aggregate`. This is the case in some old metadata, e.g. the World Bank example dashboard.
- `timeseries_limit_metric` is `[]` when the control is unset, and `QueryFormMetric` when set. The type is updated and a util is added for normalizing to `QueryFormMetric[]` + relevant tests.
- Added a missing license header.
> fix(plugin-chart-table): refine ordering logic

- packages/superset-ui-core/src/query/buildQueryObject.ts
- packages/superset-ui-core/src/utils/ensureIsArray.ts
- packages/superset-ui-core/src/utils/index.ts
- packages/superset-ui-core/test/query/buildQueryObject.test.ts
- packages/superset-ui-core/test/utils/ensureIsArray.test.ts
- plugins/plugin-chart-table/src/buildQuery.ts
- plugins/plugin-chart-table/src/controlPanel.tsx
🐛 Bug Fix
Follow up for #930 . When there is not "Sort by" metric specified, [the original logic](https://github.com/apache/superset/blob/32f2c45f93693156f1cf88c2c5223684c31d3f20/superset/viz.py#L746) pre [the API migration](https://github.com/apache-superset/superset-ui/pull/889) is to always sort by the first metric in descending order, regardless if "Sort descending" is set.
Did some refactoring on table chart's `buildQuery`:
- Introduce a more general `ensureIsArray` utils, as replacement for `extractTimeseriesLimitMetric`
- Change `queryMode` inference logic to be the same as in the control panel configs.
I'm also slipping a small refactor on `buildQueryObject` where `null` values are fell back to `undefined` so that `null`s are not sent to the backend. Even thought the backend has …
> fix(plugin-chart-table): always sort descending by first metric

- plugins/plugin-chart-table/src/buildQuery.ts
- plugins/plugin-chart-table/src/transformProps.ts
- plugins/plugin-chart-table/src/types.ts
🐛 Bug Fix
Display temporal columns more smartly. I.e. when in "Adaptive formatting":
1. if the backend returns them as string, display as is
2. if they are numbers, then assume they are timestamps and display as full UTC timestamps
Also fixes a bug where wrong query is generated when "Include time" is selected then switch to run raw records queries.
Tested with this virtual dataset in PostgreSQL:
```
SELECT TIMESTAMP '2021-01-01T11:12:33.113' as ts, '2021-01-01T11:12:33' AS ts_str, 'aa' as text, 10000000 as num
UNION
SELECT TIMESTAMP '2021-01-01T00:00:00', '2021-01-09T10:11:22', 'ccc', 11.114491
UNION
SELECT TIMESTAMP '2021-01-09T11:10:33', '2021-01-09T10:11:22', 'ccc', 11.114491
UNION
SELECT TIMESTAMP '2021-01-09T11:10:00', '2021-01-09T10:11:22', 'abc', 11.114491
UNION
SELECT TIMESTAMP …
```
> fix(plugin-chart-table): better rendering for temporal columns

- plugins/plugin-chart-echarts/package.json
- plugins/plugin-chart-echarts/src/Pie/controlPanel.tsx
- yarn.lock
🐛 Bug Fix
Bump ECharts to 5.0.2 to fix hover bug (https://github.com/apache/echarts/pull/14108) and label type bug. Also clean up control panel so that all customization fields are on a single row.
> fix(plugin-chart-echarts): label type and hover bugs

- plugins/legacy-preset-chart-nvd3/src/DistBar/controlPanel.ts
Add control for sort by "asc" or "desc"
Associated with: https://github.com/apache/superset/pull/13049
https://user-images.githubusercontent.com/8277264/107492589-50831880-6b95-11eb-8042-c94c3b21500e.mp4
> feat(legacy-preset-chart-nvd3): subject NVD3 Bar chart sort by

- plugins/legacy-plugin-chart-chord/src/controlPanel.ts
- plugins/legacy-plugin-chart-force-directed/src/controlPanel.ts
- plugins/legacy-plugin-chart-heatmap/src/controlPanel.ts
- plugins/legacy-plugin-chart-sunburst/src/controlPanel.ts
- plugins/legacy-plugin-chart-world-map/src/controlPanel.ts
Add single metric sort for charts:
> feat: Single metric sort

- plugins/plugin-chart-table/src/TableChart.tsx
Change header column tooltip text to notify the user about multi sorting
Related to: https://github.com/apache/superset/issues/10730
> feat(plugin-chart-table): add tooltip about multiple sort

- plugins/legacy-plugin-chart-parallel-coordinates/src/controlPanel.ts
- plugins/legacy-plugin-chart-pivot-table/src/controlPanel.ts
- plugins/legacy-plugin-chart-treemap/src/controlPanel.ts
Add sort by metric charts with multiple metrics
Associated with: https://github.com/apache/superset/pull/13057
> feat: add sort by metric for charts with multiple metrics

- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
Add format tooltip title as x axis
Close: https://github.com/apache/superset/issues/13019
> fix(plugin-chart-echarts): fix Timeseries tooltip title

- packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-pivot-table/Stories.tsx
- plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
- plugins/legacy-plugin-chart-pivot-table/src/utils/formatCells.ts
- plugins/legacy-plugin-chart-pivot-table/test/PivotTable.test.ts
- yarn.lock
🐛 Bug Fix
fixes https://github.com/apache/superset/issues/12681
This ensures text content of cell is only updated if its not empty,as it also overrides innerHtml property of element.
> fix(legacy-plugin-chart-pivot-table): fix displaying image inside rows

- plugins/plugin-chart-table/src/TableChart.tsx
- plugins/plugin-chart-table/src/transformProps.ts
- plugins/plugin-chart-table/src/types.ts
- yarn.lock
🏆 Enhancements
Hide table chart cell bars for group by fields, as normally they could be considered categorical and not numeric metrics.
For raw records, we could theoretically use the "IS DIMENSION" flag, but it seems to be set to True by default, even for numeric columns:
So I'm not changing the behavior for raw records mode.
> fix(plugin-chart-table): hide cell bar for group by fields

- plugins/legacy-plugin-chart-paired-t-test/package.json
- plugins/legacy-plugin-chart-paired-t-test/src/PairedTTest.jsx
- plugins/legacy-plugin-chart-paired-t-test/src/TTestTable.jsx
- plugins/legacy-plugin-chart-paired-t-test/src/controlPanel.ts
- plugins/legacy-plugin-chart-paired-t-test/src/transformProps.js
This PR fixes several bugs that were breaking Paired t-test table chart.
1. Chart was using a metric name as a to transform data, which worked only with saved metrics, since backend returns a saved metric as a string. If an adhoc metric was used, chart was still trying to use it as a key, even though it's an object, which led to an 'undefined' error.
2. `reactable-arc` was not rendering table body. I replaced it with the latest version of `reactable`.
3. CSS for scrollable table content was buggy, caused chart to have 0px height. 
What is left to decide is how to handle a case when no group by column was specified. The chart does render when group by is not specified, but it doesn't make much sense. What we can do is either display an error message (see video) or leave it as it is (see …
> fix(legacy-plugin-chart-paired-t-test): fix paired t-test table chart

- plugins/legacy-plugin-chart-map-box/src/MapBox.jsx
Fixes downloading MapBox chart as image. Part of https://github.com/apache/superset/pull/13181
CC: @villebro @junlincc
> fix(legacy-plugin-chart-map-box): fix downloading map as image

- plugins/legacy-plugin-chart-map-box/src/MapBox.jsx
Closes: https://github.com/apache/superset/issues/10843
Increase area with 0.05 to include all points.
> feat(legacy-plugin-chart-map-box): show all points in mapbox chart

- packages/superset-ui-chart-controls/src/components/InfoTooltipWithTrigger.tsx
- packages/superset-ui-chart-controls/src/components/MetricOption.tsx
- packages/superset-ui-chart-controls/src/components/Tooltip.tsx
- packages/superset-ui-chart-controls/src/index.ts
- packages/superset-ui-chart-controls/src/shared-controls/components/RadioButtonControl.tsx
- packages/superset-ui-chart-controls/src/shared-controls/components/index.tsx
- packages/superset-ui-chart-controls/src/types.ts
- packages/superset-ui-chart-controls/test/utils/expandControlConfig.test.tsx
- packages/superset-ui-core/src/chart/index.ts
- packages/superset-ui-core/src/chart/types/Base.ts
- packages/superset-ui-core/src/chart/types/QueryResponse.ts
- packages/superset-ui-core/src/chart/types/TransformFunction.ts
- packages/superset-ui-core/src/connection/index.ts
- packages/superset-ui-core/src/connection/types.ts
- packages/superset-ui-core/src/dimension/index.ts
- packages/superset-ui-core/src/dimension/types.ts
- packages/superset-ui-core/src/query/api/legacy/index.ts
- packages/superset-ui-core/src/query/api/legacy/types.ts
- packages/superset-ui-core/src/query/types/Column.ts
- packages/superset-ui-core/src/query/types/Datasource.ts
- packages/superset-ui-core/src/query/types/Metric.ts
- packages/superset-ui-core/src/query/types/Query.ts
- packages/superset-ui-core/src/query/types/QueryFormData.ts
- packages/superset-ui-core/src/query/types/QueryResponse.ts
- packages/superset-ui-core/src/query/types/Time.ts
- packages/superset-ui-core/src/query/types/index.ts
- packages/superset-ui-core/src/translation/index.ts
- packages/superset-ui-core/src/translation/types/index.ts
- packages/superset-ui-core/src/translation/types/jed.ts
- plugins/legacy-plugin-chart-time-table/src/TimeTable.tsx
🏆 Enhancements
🏠 Internal
Improve typing and file organization for shared controls.
1. Reuse `Metric` definition in `superset-ui/core`.
2. Move the React components for shared controls to its own folder (prepare for adding more custom controls).
3. Export empty objects in pure typing files to fix build errors with `npm link`:
> refactor(chart-controls): improve typing and file organization

- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
🏠 Internal
Expose current `datasource` to the state of `adhoc_filters` and `time_range` control and clean up the `provideFormDataToProps` option. We should just be explicit what prop to expose in `mapStateToProps` so controls don't get unnecessarily re-rendered because of form data updates from other unrelated controls.
`superset-frontend` has some related changes: https://github.com/apache/superset/pull/13221
Manual verification in Superset via npm link:
- Make sure both controls still work
- Make sure changing dataset will reset time filter to default value ("Last week")
> fix(chart-controls): expose datasource for some controls

- packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
- packages/superset-ui-chart-controls/src/types.ts
🏆 Enhancements
POC of Explore drag and drop query panel. scope - Groupby control only.
link to: https://github.com/apache/superset/pull/13210
> feat: add dropGroupByControl

- plugins/legacy-plugin-chart-paired-t-test/src/controlPanel.ts
🐛 Bug Fix
Fixes Group By field being duplicated (see https://github.com/apache-superset/superset-ui/pull/961#issuecomment-786424421)
CC: @junlincc
> fix: remove duplicated group by field

- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
- packages/superset-ui-core/src/utils/featureFlags.ts
- packages/superset-ui-core/test/utils/featureFlag.test.ts
🏆 Enhancements
This copies over the feature flag functionality from `apache/superset` to make it easier to conditionally enable features in `superset-ui`.
> feat(core): copy feature flags from main repo

- packages/superset-ui-core/src/connection/SupersetClientClass.ts
- packages/superset-ui-core/test/chart/clients/ChartClient.test.ts
- packages/superset-ui-core/test/chart/fixtures/constants.ts
- packages/superset-ui-core/test/connection/SupersetClient.test.ts
- packages/superset-ui-core/test/connection/SupersetClientClass.test.ts
- packages/superset-ui-core/test/connection/callApi/callApi.test.ts
- packages/superset-ui-core/test/connection/callApi/callApiAndParseWithTimeout.test.ts
- packages/superset-ui-core/test/connection/callApi/parseResponse.test.ts
- packages/superset-ui-core/test/connection/fixtures/constants.ts
- packages/superset-ui-core/test/query/api/setupClientForTest.ts
corresponding `SupersetClient` change for: https://github.com/apache/superset/pull/13212
> refactor(SupersetClient): use new /api/v1/security/csrf_token/ endpoint

- packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
- packages/superset-ui-chart-controls/src/types.ts
Rename `dndGroupByControl` type from `DndColumnSelectControl` to `DndColumnSelect` so that it matches component name in Superset after refactor (https://github.com/apache/superset/pull/13340)
.
> fix: rename DnD types to match component names in Superset

- packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-heatmap/Stories.tsx
- plugins/legacy-plugin-chart-heatmap/src/Heatmap.css
- plugins/legacy-plugin-chart-heatmap/src/Heatmap.js
Add min and height for the heatmap. Hide Y labels and X label when you reach the minimum
https://user-images.githubusercontent.com/8277264/109931482-941efd00-7cd1-11eb-88e9-1c919922d098.mov
https://user-images.githubusercontent.com/8277264/109931517-a13bec00-7cd1-11eb-8f87-e67eb93efcce.mov
https://user-images.githubusercontent.com/8277264/109935662-7bfdac80-7cd6-11eb-90b7-3c2e35e0d604.mov
> feat: responsive heatmap

- plugins/plugin-chart-table/src/buildQuery.ts
- plugins/plugin-chart-table/src/index.ts
- plugins/plugin-chart-table/test/buildQuery.test.ts
🐛 Bug Fix
Silently ignore duplicate percent metrics.
Currently we do this for metrics, but adding percent metrics with the same name may still cause an error. This fixes it.
> fix(plugin-chart-table): ignore duplicate percent metrics

- packages/superset-ui-core/src/query/buildQueryObject.ts
- packages/superset-ui-core/src/query/extractExtras.ts
- packages/superset-ui-core/src/query/processExtraFormData.ts
- packages/superset-ui-core/src/query/processFilters.ts
- packages/superset-ui-core/src/query/types/Query.ts
- packages/superset-ui-core/test/query/buildQueryObject.test.ts
- packages/superset-ui-core/test/query/extractExtras.test.ts
- packages/superset-ui-core/test/query/processExtraFormData.test.ts
🏆 Enhancements
List of changes:
- add placeholder props `time_grain` and `time_column` fields to `QueryFormData` to get ready to streamline `granularity`, `granularity_sqla` and `time_grain_sqla`.
- fix appending of filters and adhoc filters + add tests
- remove `appendExtraFormData`, as we should only enable appending filters (are handled by `processFilters.ts` now to centralize filter handling in `buildQueryObject`)
- add new override props + add tests
- fix a few typos in `buildQueryContext.ts`
> feat(core): add extra form data fields for native filters

- plugins/plugin-chart-echarts/src/Graph/controlPanel.tsx
fix graph viz crash when dnd FF enable
> fix(plugin-chart-echarts): fix GraphViz crash when DnD FF enable

- packages/superset-ui-chart-controls/src/components/ColumnTypeLabel.tsx
🐛 Bug Fix
minor fix, show question mark icon when can not infer data type in datasource panel
> fix: show question mark icon when can not infer datatype

- packages/superset-ui-chart-controls/src/types.ts
- plugins/plugin-chart-table/src/controlPanel.tsx
🏠 Internal
Optimize typing for chart controls. So they can be more easily referenced in various util functions in `superset-frontend`.
See: https://github.com/apache/superset/pull/13520/files
- `yarn type` should not throw error
- In `superset-frontend`, `npm run type` should not throw error with changes in https://github.com/apache/superset/pull/13520/files
> refactor(chart-controls): optimize typing

- packages/superset-ui-chart-controls/src/constants.ts
- packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
- packages/superset-ui-chart-controls/src/types.ts
- packages/superset-ui-core/src/query/extractQueryFields.ts
- packages/superset-ui-core/src/query/getMetricLabel.ts
- packages/superset-ui-core/src/query/types/Metric.ts
- packages/superset-ui-core/src/query/types/QueryFormData.ts
- packages/superset-ui-core/test/fixtures.ts
- packages/superset-ui-core/test/query/extractQueryFields.test.ts
- packages/superset-ui-core/test/query/getMetricLabel.test.ts
- plugins/plugin-chart-echarts/src/BoxPlot/buildQuery.ts
- plugins/plugin-chart-echarts/src/Timeseries/buildQuery.ts
- plugins/plugin-chart-table/src/buildQuery.ts
🏆 Enhancements
🐛 Bug Fix
Don't set `metrics` in QueryObject is it is in raw records mode. Then we can assume it is an aggregation query as long as `metrics` is defined, even if it's just empty array.
This allows a clean deprecation of the `groupby` field.
See discussions in https://github.com/apache/superset/pull/13434 for details.
> fix(core): don't add metrics to query object when in raw records mode

- packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
- packages/superset-ui-chart-controls/src/types.ts
🏆 Enhancements
If `ENABLE_EXPLORE_DRAG_AND_DROP` is set, enables drag and drop feature for metrics control.
CC @villebro @junlincc
> feat: implement Metrics dnd

- plugins/plugin-chart-table/src/buildQuery.ts
- plugins/plugin-chart-table/test/buildQuery.test.ts
🐛 Bug Fix
Metrics should be `undefined` when table chart is in raw records mode.
I changed the logic of `buildQuery` in `@superset-ui/core`, but failed to update the one in table chart itself.
Related to https://github.com/apache-superset/superset-ui/pull/995
> fix(plugin-chart-table): metrics should be undefined

- plugins/legacy-plugin-chart-histogram/src/Histogram.jsx
🏆 Enhancements
Per a community request, I added the `t()` wrapper around a couple stubborn strings in the Histogram chart. 
🐛 Bug Fix
🏠 Internal
> chore: translation strings in histogram

- packages/superset-ui-chart-controls/src/components/MetricOption.tsx
- packages/superset-ui-core/package.json
- packages/superset-ui-core/src/components/SafeMarkdown.tsx
- packages/superset-ui-core/src/components/index.ts
- packages/superset-ui-core/src/index.ts
- packages/superset-ui-core/src/query/types/Metric.ts
- yarn.lock
🏆 Enhancements
Precursor to https://github.com/apache/superset/pull/13606, supports both warning_text and warning_markdown side by side in the metric option component.
Tested by npm linking to superset:
> feat: support warning_markdown on metrics

- packages/superset-ui-core/test/time-format/factories/createD3TimeFormatter.test.ts
🐛 Bug Fix
this test failed locally because we were comparing a timezone offset in the past to the current one. They passed in CI since they're in UTC time without DST, but they fail locally
to: @ktmud @kristw
> fix: time formatter test

- plugins/plugin-chart-echarts/src/BoxPlot/EchartsBoxPlot.tsx
- plugins/plugin-chart-echarts/src/BoxPlot/controlPanel.ts
- plugins/plugin-chart-echarts/src/BoxPlot/index.ts
- plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
- plugins/plugin-chart-echarts/src/BoxPlot/types.ts
- plugins/plugin-chart-echarts/src/Pie/EchartsPie.tsx
- plugins/plugin-chart-echarts/src/Pie/controlPanel.tsx
- plugins/plugin-chart-echarts/src/Pie/index.ts
- plugins/plugin-chart-echarts/src/Pie/transformProps.ts
- plugins/plugin-chart-echarts/src/Pie/types.ts
- plugins/plugin-chart-echarts/src/components/Echart.tsx
- plugins/plugin-chart-echarts/src/types.ts
Add checkbox control to disable/enable the emitting filter for the pie chart
https://user-images.githubusercontent.com/8277264/111298654-a85ee480-8657-11eb-9bca-1472fd980cc1.mov
https://user-images.githubusercontent.com/8277264/111616332-72059e80-87ea-11eb-8f62-6f9eaf2cde18.mov
> feat(plugin-chart-echarts): Emit cross filters for pie and boxplot

- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/utils/series.ts
- plugins/plugin-chart-echarts/test/index.test.ts
- plugins/plugin-chart-echarts/test/utils/series.test.ts
🐛 Bug Fix
Fill missing values that are next to non-null values with 0 when stacking is enabled to avoid gaps. Avoids imputing all missing values with zero to avoid overlapping lines (empirically observed that the lines became blurry due to many overlapping lines).
> fix(plugin-chart-echarts): fill missing values when stacked chart

- packages/generator-superset/generators/plugin-chart/templates/package.erb
- packages/generator-superset/generators/plugin-chart/templates/src/plugin/buildQuery.erb
- packages/generator-superset/generators/plugin-chart/templates/src/plugin/controlPanel.erb
🐛 Bug Fix
When doing some viz plugin work I noticed there were some changes during the migration from `superset-ui` 0.15->0.17 that hadn't made it into the templates.
Tested locally building both regular and timeseries chart and both worked as expected.
> fix(generator-superset): update plugin template to 0.17 standards

- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
🏆 Enhancements
Makes the change recommended in https://github.com/apache/superset/pull/13802 to help protect performance when grouping by high cardinality dimensions in the default case
Test Plan:
CI
to: @ktmud @michael-s-molina
> feat: add default series_limit

- packages/superset-ui-chart-controls/src/components/InfoTooltipWithTrigger.tsx
- packages/superset-ui-chart-controls/src/components/Select.tsx
- packages/superset-ui-chart-controls/src/shared-controls/components/ColumnConfigControl/constants.tsx
- packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/TableStories.tsx
- packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/testData.ts
- plugins/plugin-chart-table/src/TableChart.tsx
- plugins/plugin-chart-table/src/utils/DateWithFormatter.ts
- plugins/plugin-chart-table/src/utils/formatValue.ts
🐛 Bug Fix
Realized I didn't commit the changes about small number formatter before merging... https://github.com/apache-superset/superset-ui/pull/1019
> feat(plugin-chart-table): add small number formatter

- packages/superset-ui-chart-controls/src/constants.ts
- packages/superset-ui-core/src/query/buildQueryObject.ts
- packages/superset-ui-core/src/query/constants.ts
- packages/superset-ui-core/src/query/extractQueryFields.ts
- packages/superset-ui-core/test/query/extractQueryFields.test.ts
- temporary-plugins/hold-potentially-deprecate/superset-ui-plugin-chart-table/src/processColumns.ts
- temporary-plugins/hold-potentially-deprecate/superset-ui-plugin-chart-table/src/transformProps.ts
🐛 Bug Fix
Fixes a bad import introduced by https://github.com/apache-superset/superset-ui/pull/1019
See https://github.com/apache-superset/superset-ui/pull/1034#discussion_r603935519 for details
> fix(chart-controls): export/import DTTM_ALIAS properly

- babel.config.js
- jest.config.js
- package.json
- packages/superset-ui-chart-controls/src/components/ControlForm/index.tsx
- packages/superset-ui-core/package.json
- scripts/build.js
- yarn.lock
🐛 Bug Fix
Emotion's [css prop](https://emotion.sh/docs/css-prop#babel-preset) must be transpiled to use emotion's `jsx` function. Not doing this is will result in missing styles when the built React components (`plugin/lib/../Component.js`) are used in `superset-frontend`. This affect only production builds, and not `npm link` because `npm link` uses `plugin/src/../Components.tsx`, which can be picked up by `superset-frontend`'s Babel emotion plugin.
Tested by temporarily disable `src` replacement logic in `superset-frontend`'s `webpack.config.js`.
Related: https://github.com/apache/superset/pull/13758#issuecomment-810604105
> fix(chart-controls): transform emotion css prop

- plugins/plugin-chart-table/src/TableChart.tsx
🐛 Bug Fix
Let table header also follow the text align configs. Note this also changes the behavior for the table headers of metric columns when column format config is not set---it will align to the right, like the metric values themselves, instead of to the left.
> fix(plugin-chart-table): add text align to table header

- packages/superset-ui-core/src/chart/models/ChartProps.ts
- packages/superset-ui-core/src/chart/types/Base.ts
🏆 Enhancements
Add `AppSection` metadata to support functionality in https://github.com/apache/superset/pull/13726#pullrequestreview-620185791
Changes:
1. Added AppSection type that specify place of chart on the screen (it's parent component)
> feat(native-filters): add AppSection type

- plugins/plugin-chart-table/src/Styles.tsx
- plugins/plugin-chart-table/src/TableChart.tsx
- plugins/plugin-chart-table/src/controlPanel.tsx
- plugins/plugin-chart-table/src/index.ts
- plugins/plugin-chart-table/src/transformProps.ts
This PR enables emitting cross-filters from Table chart.
To enable the feature, set the feature flag `DASHBOARD_CROSS_FILTERS` in `superset/config.py` and select "ENABLE EMITTING FILTERS" checkbox in Customize tab.
To select filter values, click on cells in groupby columns. Selecting a value emits a filter with an `IN` operator.
https://user-images.githubusercontent.com/15073128/113731815-5c084100-96f9-11eb-92c5-bdfb969ae9e9.mov
CC @junlincc @villebro @ktmud
> feat(plugin-chart-table): enable emitting cross-filters

- plugins/plugin-chart-table/src/buildQuery.ts
🐛 Bug Fix
The totals query should not be added if there are no metrics present. The check needs to verify that 1) `metrics` is not `undefined`/`null` and 2) it's `length` is truthy.
> fix(plugin-chart-table): fix empty metrics

- plugins/plugin-chart-echarts/src/components/Echart.tsx
🐛 Bug Fix
This removes flicker in the ECharts charts introduced in #1010 caused by calling `clear()` on the ECharts instance. This was previously done to clear old highlighted values, as old highlights have to be explicitly "downplayed". This PR removes the `clear()` call, and to downplay non-selected values, the previous selection is compared to the current selection; if a previously selected value is no longer present, it is"downplayed".
Previously, the chart would rerender every time the `useEffect` hook was called:
After the PR, no flashing occurs:
> fix(plugin-chart-echarts): fix unnecessary chart clearing

- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/utils/series.ts
- plugins/plugin-chart-echarts/test/utils/series.test.ts
🐛 Bug Fix
If an annotation layer has a series name that already exists in the chart, the chart raises an error. This PR adds series name deduplication to ensure the chart can be drawn.
> fix(plugin-chart-echarts): add series deduplication

- plugins/legacy-preset-chart-nvd3/src/utils/tokenize.ts
- plugins/legacy-preset-chart-nvd3/test/utils/tokenize.test.js
🐛 Bug Fix
In the bullet chart, the value for ranges can be undefined, causing the chart to break if no ranges are specified.
> fix(legacy-preset-chart-nvd3): fix tokenizer input type

- plugins/plugin-chart-echarts/src/components/Echart.tsx
🐛 Bug Fix
Currently, `Timeseries` chart highlighted by default.
This will fix it.
> fix(plugin-chart-echarts): fix unnecessary highlight

- plugins/plugin-chart-table/src/utils/formatValue.ts
🏆 Enhancements
Add `muted` attribute of `video` tag to whitelist.
The `muted` is very useful because `autoplay` attribute will not work if not added `muted` on Chrome.
Default: https://github.com/leizongmin/js-xss/blob/master/lib/default.js#L75
```js
video: ["autoplay", "controls", "loop", "preload", "src", "height", "width"]
```
> chore(plugin-chart-table): Add muted attribute of video tag to whitelist

- packages/superset-ui-core/src/chart/types/Base.ts
- packages/superset-ui-core/src/query/buildQueryContext.ts
- packages/superset-ui-core/src/query/buildQueryObject.ts
- packages/superset-ui-core/src/query/constants.ts
- packages/superset-ui-core/src/query/processExtraFormData.ts
- packages/superset-ui-core/src/query/types/Query.ts
- packages/superset-ui-core/src/query/types/QueryFormData.ts
- packages/superset-ui-core/test/query/buildQueryContext.test.ts
- packages/superset-ui-core/test/query/buildQueryObject.test.ts
- packages/superset-ui-core/test/query/processExtraFormData.test.ts
- plugins/plugin-chart-echarts/src/BoxPlot/EchartsBoxPlot.tsx
- plugins/plugin-chart-echarts/src/BoxPlot/buildQuery.ts
- plugins/plugin-chart-echarts/src/BoxPlot/index.ts
- plugins/plugin-chart-echarts/src/Pie/EchartsPie.tsx
- plugins/plugin-chart-echarts/src/Pie/index.ts
- plugins/plugin-chart-table/src/TableChart.tsx
- plugins/plugin-chart-table/src/index.ts
This is a follow-up to #1040 to further simplify the data mask hook and related types.
Before the `ExtraFormData` contained three properties
```
extraFormData = {
append_form_data: {
adhoc_filters: [],
filters: [],
},
override_form_data: {
time_range: '',
},
custom_form_data: {},
}
```
After this change, `append_form_data`, `override_form_data` and `custom_form_data`  are all in the same object, with the implicit assumption that filters and `custom_form_data` are appended to fields with the same name in `QueryFormData`/`QueryObject`, and the rest (mostly temporal filters, like time column, time range, time grain etc) are overridden. Example:
```
extraFormData = {
adhoc_filters: [],
filters: [],
time_range: '',
custom_form_data: {},
}
```
In addition, …
> chore(core): simplify ExtraFormData

- packages/superset-ui-chart-controls/src/components/MetricOption.tsx
- packages/superset-ui-chart-controls/test/components/MetricOption.test.tsx
🏆 Enhancements
Adds a tooltip to the metric name so that if it overflows the container we can still read it.
Test plan:
CI. new unit test, test in superset
to: @pkdotson @ktmud @graceguo-supercat
> feat: add tooltip for full metric names

- plugins/plugin-chart-echarts/package.json
- plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
- yarn.lock
🏆 Enhancements
Bump ECharts to 5.1.0 to pull in general fixes/improvements. See changelog for details: https://github.com/apache/echarts/releases/tag/5.1.0
> chore(plugin-chart-echarts): bump echarts to 5.1.0

- plugins/plugin-chart-echarts/src/Pie/transformProps.ts
🐛 Bug Fix
When `showLabelsThreshold` is set, the label lines are shown despite the labels being missing. This PR removes the hack to make labels empty strings when the threshold is not met and implements the `minShowLabelAngle` (set to `3.6 * showLabelsThreshold` as 100 % == 360 degrees) property that provides native support for removal of thin slices.
As can be seen in the screenshot, the top slices show a line despite no labels being shown:
After the fix, no label lines are shown for the slices that don't exceed the threshold:
> fix(plugin-chart-echarts): remove label line if below threshold

- plugins/plugin-chart-table/src/buildQuery.ts
🐛 Bug Fix
1. Add support for group by filter in server side pagination case in table
2. Add support only for aggregate mode
> fix(native-filters): support group by feature for server side pagination in table

- plugins/plugin-chart-echarts/package.json
- plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
- yarn.lock
Bump ECharts from 5.1.0 to 5.1.1 to pull in the following fixes:
https://dist.apache.org/repos/dist/dev/echarts/5.1.1-rc.1/RELEASE_NOTE.txt
> chore(plugin-chart-echarts): bump echarts 5.1.1

- packages/superset-ui-core/package.json
- packages/superset-ui-core/src/style/index.ts
🏆 Enhancements
We're now exporting cache features to namespace classes and such. We're also continuing this habit of exporting all things Emotion from Superset-UI Core to avoid multiple instantiated versions in Superset, which causes hard-to-diagnose bugs. 
🐛 Bug Fix
🏠 Internal
> chore: adds Emotion's CacheProvider and createCache as exports from Core package

- plugins/plugin-chart-table/src/controlPanel.tsx
🐛 Bug Fix
Show totals adds an additional SQL query to the request, which slows things down. Since it's not a critical feature, we shouldn't enable it by default.
> feat(plugin-chart-table): disable show_totals by default

- packages/superset-ui-chart-controls/src/shared-controls/components/ColumnConfigControl/constants.tsx
- plugins/plugin-chart-table/src/DataTable/DataTable.tsx
- plugins/plugin-chart-table/src/DataTable/types/react-table.d.ts
- plugins/plugin-chart-table/src/TableChart.tsx
- plugins/plugin-chart-table/src/i18n.ts
- plugins/plugin-chart-table/src/transformProps.ts
- plugins/plugin-chart-table/src/types.ts
- plugins/plugin-chart-table/src/utils/formatValue.ts
🐛 Bug Fix
Fixes two bugs:
1. Text align was not applied to totals.
2. Resizing window does not rereize the table chart.
Also updates the tooltip for the column width control to be more reflective of what it really is.
> fix(plugin-chart-table): resize and totals formatting bug

- packages/superset-ui-chart-controls/src/shared-controls/components/ColumnConfigControl/ColumnConfigControl.tsx
🐛 Bug Fix
Hide column config control when chart data returns no columns. This can happen when there is a backend error.
> fix(plugin-chart-table): hide column configs when no columns

- plugins/plugin-chart-pivot-table/package.json
- plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
- plugins/plugin-chart-pivot-table/src/plugin/controlPanel.ts
- plugins/plugin-chart-pivot-table/src/plugin/index.ts
- plugins/plugin-chart-pivot-table/src/plugin/transformProps.ts
- plugins/plugin-chart-pivot-table/src/types.ts
- plugins/plugin-chart-pivot-table/test/plugin/transformProps.test.ts
- yarn.lock
Enable cross filtering in pivot table chart.
Clicking on any header cell that represents selected rows and columns emits a filter `group_name IN ('value1', 'value2', ...)`.
https://user-images.githubusercontent.com/15073128/116720817-e97b4000-a9dc-11eb-800e-9003538d0031.mov
CC @villebro @junlincc
> feat(plugin-chart-pivot-table): enable cross filtering

- plugins/legacy-plugin-chart-sankey/src/Sankey.js
🐛 Bug Fix
Sankey tooltips sometimes overflow off the chart, which causes problems in Superset because tooltips are sometimes not readable by users. This PR tweaks the positioning of the tooltip so that the tooltip always appears within the chart boundaries.
See: https://github.com/apache/superset/issues/14437
BEFORE:
https://user-images.githubusercontent.com/14146019/117058244-3f006700-acd3-11eb-9436-0a2a10dba646.mov
AFTER:
https://user-images.githubusercontent.com/14146019/117057970-f052cd00-acd2-11eb-8d03-b072b37c0e5c.mov
> fix(legacy-plugin-chart-sankey): ensure tooltip position is within chart

- plugins/plugin-chart-table/src/controlPanel.tsx
🐛 Bug Fix
When checking for visibility of server side related controls, make sure the control value is set before reading the control value.
> fix(plugin-chart-table): check if control values are set

- plugins/plugin-chart-echarts/src/BoxPlot/EchartsBoxPlot.tsx
- plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
- plugins/plugin-chart-echarts/src/BoxPlot/types.ts
- plugins/plugin-chart-echarts/src/Funnel/EchartsFunnel.tsx
- plugins/plugin-chart-echarts/src/Funnel/transformProps.ts
- plugins/plugin-chart-echarts/src/Pie/EchartsPie.tsx
- plugins/plugin-chart-echarts/src/Pie/transformProps.ts
- plugins/plugin-chart-echarts/src/Radar/EchartsRadar.tsx
- plugins/plugin-chart-echarts/src/Radar/transformProps.ts
- plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
🐛 Bug Fix
Using `ownState` will retrigger a new query, which is unnecessary in the majority of cross filtering cases. This moves the selected labels in the ECharts plugin into `filterState`, thus avoiding the need to set `ownState`.
Notice how clicking on a box causes the chart to trigger a query:
After moving the selection state to `filterState`, the chart no longer needs to trigger a query when clicking a box:
> fix: avoid unnecessary requeries caused by ownState

- packages/superset-ui-core/src/query/extractTimegrain.ts
- packages/superset-ui-core/src/query/index.ts
- packages/superset-ui-core/src/query/types/AnnotationLayer.ts
- packages/superset-ui-core/src/query/types/Query.ts
- packages/superset-ui-core/test/query/extractTimegrain.test.ts
- plugins/legacy-preset-chart-big-number/src/BigNumber/transformProps.ts
- plugins/legacy-preset-chart-big-number/test/transformProps.test.ts
- plugins/plugin-chart-table/src/transformProps.ts
- plugins/plugin-chart-table/src/utils/isEqualColumns.ts
🐛 Bug Fix
Currently the following plugins don't apply the proper time grain formatter when the time grain has been overridden by either a Filter Box or Native Filter:
- Legacy Pivot Table
- Table Chart
- Big Number
This PR adds a util to `@superset-ui/core` for extracting the time grain from the raw form data and implements said function in all charts that support time grain formatting. After the change both Filter Box and Native Filter timegrains will be properly reflected in the time formatter.
Currently overriding the time grain on the dashboard isn't reflected in the time formatter if it's set to timegrain (see time grain `Week` on the Filter Box):
After the change all charts that use the time grain formatter will properly pick up the time grain even on the dashboard:
> fix: use proper time grain when using native filters or filter box

- packages/superset-ui-chart-controls/src/components/ColumnOption.tsx
- packages/superset-ui-chart-controls/src/components/ColumnTypeLabel.tsx
- packages/superset-ui-chart-controls/src/constants.ts
- packages/superset-ui-chart-controls/src/types.ts
- packages/superset-ui-chart-controls/test/components/ColumnOption.test.tsx
- packages/superset-ui-chart-controls/test/components/ColumnTypeLabel.test.tsx
- packages/superset-ui-core/src/query/types/Column.ts
- packages/superset-ui-core/test/fixtures.ts
- packages/superset-ui-core/test/query/getMetricLabel.test.ts
🐛 Bug Fix
Since the backend now does a better job at inferring generic datatypes, it makes sense to remove some of the old logic that looks at raw datatypes coming back from the backend. Dependent on the following PR: https://github.com/apache/superset/pull/14547
> feat(core): clean up datatype logic

- plugins/plugin-chart-echarts/src/Pie/controlPanel.tsx
SORT BY METRIC checkbox check by default in Pie chart. so the query is:
<pre>
SELECT value AS value,
SUM(value) AS sum__value
FROM energy_usage
GROUP BY value
ORDER BY sum__value DESC
LIMIT 10000;
</pre>
> feat(plugin-chart-echarts): set up orderby by default on Pie chart

- plugins/plugin-chart-echarts/src/Funnel/controlPanel.tsx
- plugins/plugin-chart-echarts/src/Funnel/transformProps.ts
> fix(plugin-chart-echarts): funnel chart improvements

- packages/superset-ui-core/src/chart/components/SuperChart.tsx
- packages/superset-ui-core/src/chart/models/ChartMetadata.ts
- packages/superset-ui-core/src/chart/models/ChartProps.ts
- packages/superset-ui-core/test/chart/models/ChartProps.test.ts
🏆 Enhancements
Add support for empty datasets without rendering the "No Results" placeholder text and an flag to notify the chart that it's refreshing data without being forced to use the default spinner. Needed to be able to add support for "Search all filter options" feature in Select Filter.
See below an example of the native select filter with the feature turned on (the chart loading times have been exaggerated by placing a sleep on the backend): 
https://user-images.githubusercontent.com/33317356/118638272-5402ed00-b7df-11eb-9a2c-a9e78b297c63.mp4
> feat(core): add support for empty results and refresh indicator

- packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
🏆 Enhancements
Add a new shared control "orderby" for non-timeseries chart.
related PR: https://github.com/apache-superset/superset-ui/pull/1112
> feat(core): add orderyby shared control

- plugins/plugin-chart-echarts/src/Radar/buildQuery.ts
- plugins/plugin-chart-echarts/src/Radar/controlPanel.tsx
add SORT BY metrics to Radar chart to avoid random values.
> feat(plugin-chart-echarts): add orderby on Radar chart

- packages/superset-ui-core/src/query/types/Operator.ts
🏆 Enhancements
Adds support for the `ILIKE` binary operator: https://docs.sqlalchemy.org/en/13/core/sqlelement.html#sqlalchemy.sql.operators.ColumnOperators.ilike
> feat(core): add support for case insensitive LIKE operator

- plugins/plugin-chart-pivot-table/package.json
- plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
- plugins/plugin-chart-pivot-table/src/plugin/transformProps.ts
- plugins/plugin-chart-pivot-table/src/types.ts
- plugins/plugin-chart-pivot-table/test/plugin/transformProps.test.ts
Fixes https://github.com/apache/superset/issues/14716
In order to test this PR, link `plugin-chart-pivot-table` to Superset and create a Pivot Table chart with rows and columns which have labels assigned in dataset
Before:
After:
CC: @junlincc
> fix(plugin-chart-pivot-table): fix displaying column names when labels are available

- packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
- plugins/plugin-chart-table/src/controlPanel.tsx
Changes default Time Range from "Last week" to "No filter"
Changes using "COUNT(*)" or other saved metric as a default metric to empty metrics control.
In the case of Table chart, removing default metric was a bit more complex. We use Groupby, Metrics and Percentage Metrics there, and at least one of them must have a value to construct a correct query. However, we can only write control validator that use values of its own control - for instance, we can't create a validator for groupby that checks if metrics or percentage_metrics are empty or not. We also couldn't simply mark all 3 controls as required, as only 1 is really required. The result was that upon creating a table chart, an incorrect request to backend was sent and we displayed an `Empty query?` error. It was quite a bad user …
> feat(core): remove defaults for time range filter and Metrics

- plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
🐛 Bug Fix
Currently the Mixed Timeseries chart doesn't consider the secondary axis formatter when rendering the tooltip.
Despite "girls" referencing the secondary axis (right) that applies a different formatter than the primary axis (left), the secondary axis format isn't applied in the tooltip (now displays "658k", should be "657586"):
Now the tooltip format is set based on the format defined for the axis.
Fixes https://github.com/apache/superset/issues/14943
> fix(plugin-chart-echarts): fix tooltip format in mixed ts chart

- plugins/plugin-chart-echarts/src/MixedTimeseries/buildQuery.ts
- plugins/plugin-chart-echarts/src/Timeseries/buildQuery.ts
- plugins/plugin-chart-echarts/test/Timeseries/buildQuery.test.ts
🐛 Bug Fix
Order by timeseries limit metric if no orderby is provided (for parity with NVD3 Timeseries viz'):
Added tests to ensure that ordering is correct both when `orderby` is specified/unspecified combined with timeseries limit metric.
> fix(plugin-chart-echarts): order by timeseries limit metric

- plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
🐛 Bug Fix
Tooltips on nvd3 charts are buggy on dashboards, because if you hover over a chart before the rest of them load, the tooltips that have already been hovered on before disappear. This was because the migration to emotion added an extra div in between the chart container and the nvd3 chart, so we couldn't properly manage that chart's tooltips.
This fixes the bug by searching for the chart container all the way up the dom to get the proper chart id.
Test Plan:
Sync code to superset, load a dashboard with nvd3 charts, hover over a chart to see the tooltip, force refresh a different nvd3 chart, see the first tooltip again after the second chart reloads.
to: @ktmud @pkdotson
> fix: tooltips on nvd3 charts

- plugins/plugin-chart-echarts/package.json
- plugins/plugin-chart-echarts/src/Tree/controlPanel.tsx
- plugins/plugin-chart-echarts/src/Treemap/EchartsTreemap.tsx
- plugins/plugin-chart-echarts/src/components/Echart.tsx
🏆 Enhancements
Bump ECharts to version 5.1.2. See the changelog for details: https://github.com/apache/echarts/releases/tag/5.1.2 . Two minor tweaks/cleanups:
- Remove the `forceClear` prop from the `Echart` component as it should no longer be needed: https://github.com/apache/echarts/pull/14930 . Ping @stephenLYZ 
- Change `root_node_id` to `renderTrigger: true` thanks to this fix: https://github.com/apache/echarts/pull/14905 . Ping @mayurnewase
> chore(plugin-chart-echarts): bump echarts to 5.1.2

- plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
- plugins/plugin-chart-pivot-table/src/plugin/controlPanel.ts
- plugins/plugin-chart-pivot-table/src/plugin/transformProps.ts
- plugins/plugin-chart-pivot-table/src/types.ts
- plugins/plugin-chart-pivot-table/test/plugin/transformProps.test.ts
Adds a radio button to control panel to switch applying metrics to columns (default) or to rows in Pivot Table v2 chart.
https://user-images.githubusercontent.com/15073128/121909044-d8d51e00-cd2d-11eb-800a-314e9a8d4698.mov
CC: @rusackas @villebro @junlincc
> feat(plugin-chart-pivot-table): enable metrics to be used as row groups

- packages/superset-ui-core/src/chart/components/SuperChart.tsx
🐛 Bug Fix
When rendering a `SuperChart` with percentage width/height, the `SuperChartCore` component can sometimes get unmounted and remounted due to the initial width and height being zero before `ParentSize` provides non-zero values, causing major side-effects such as new queries being sent to the backend. This PR removes this check, making the logic for dynamic widths/heights more in-line with that of its non-dynamic counterpart.
Rejected alternative: In an earlier iteration of this PR, we introduced the state `hasBeenRendered`, which is `false` by default, but gets set to `true` at the first render. This way we could avoid rendering until width and height are greater than zero for the first time, while avoiding unmounting if they become zero at a later stage. Since this logic is not …
> fix(core): remove height and width requirement on SuperChart

- packages/superset-ui-core/src/chart/models/ChartMetadata.ts
🏆 Enhancements
Added new metadata for the viz picker modal. The `categories` -> `category` change isn't breaking because nothing uses the field yet.
🐛 Bug Fix
🏠 Internal
> chore(core): adjustments to chart metadata

- plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
🐛 Bug Fix
Unchecking rich tooltip will force marker to be shown, and marker control is not working. This is to support item-based tooltips. But I'd almost prefer to use only marker checkbox to control. The only side effect is that we need to check the marker after unchecking rich tooltip. But it can guarantee a single responsibility.
Or we can check the marker control when unchecking rich tooltip. It may be better implemented in dynamic control.
related to https://github.com/apache/superset/issues/15189
https://user-images.githubusercontent.com/81597121/122186275-bd0f6c00-ce42-11eb-8886-448806d93993.mov
https://user-images.githubusercontent.com/11830681/123062153-d6b24400-d43e-11eb-98ee-3d51a2885699.mov
> fix(plugin-chart-echarts): [time-series][mixed timeseries] marker control does not work

- packages/superset-ui-core/src/models/Registry.ts
- packages/superset-ui-core/test/models/Registry.test.ts
🏆 Enhancements
Adds a listener interface to registries. This will make it easier to use registries from React, specifically wrt dynamic plugins because we can do things like make hooks that re-render components when the registry changes.
Cleaned up some types while I was in there.
🐛 Bug Fix
🏠 Internal
> feat(core): Registry listeners

- plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
- plugins/plugin-chart-echarts/src/Funnel/transformProps.ts
- plugins/plugin-chart-echarts/src/Graph/transformProps.ts
- plugins/plugin-chart-echarts/src/Pie/transformProps.ts
- plugins/plugin-chart-echarts/src/utils/prophet.ts
- plugins/plugin-chart-echarts/src/utils/series.ts
- plugins/plugin-chart-echarts/test/utils/series.test.ts
🐛 Bug Fix
Remove html tags from series names in tooltip.
Currently a series names that could be html tags don't show correctly on the tooltip(the series name `<NULL>` which can be seen on the legend does not show):
After they show correctly (legend omitted in screenshot):
> fix(plugin-chart-echarts): sanitize series from html tags

- plugins/plugin-chart-echarts/src/Treemap/transformProps.ts
🐛 Bug Fix
Due to a bug present in ECharts 5.1.2, Treemap doesn't properly rerender when the option changes when animation is disabled (see https://github.com/apache/echarts/issues/15282 for details). Until the fix https://github.com/apache/echarts/pull/15283 is merged and released, we should enable animations to work around the bug. I also consider the animation pretty nice, so I wouldn't mind leaving animations enabled.
In addition, the color scheme is changed to reference the group name, aligning it with colors in other charts in the dashboard.
https://user-images.githubusercontent.com/33317356/124273810-2b457580-db49-11eb-8444-10ace0a7a9d4.mp4
https://user-images.githubusercontent.com/33317356/124270761-4b733580-db45-11eb-9400-0363cda128f9.mp4
> fix(plugin-chart-echarts): enable animation to clear old nodes

- plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/Timeseries/types.ts
🐛 Bug Fix
https://github.com/apache/superset/issues/15042
https://github.com/apache/superset/issues/15042#issuecomment-856947476
* the reason is https://github.com/apache/superset/issues/15042#issuecomment-858616822
* the solution is https://github.com/apache-superset/superset-ui/pull/1161#issuecomment-873357465
> fix(plugin-chart-echarts): fix time-series chart xAxisShowMin(Max)Label default value

- packages/superset-ui-core/src/query/index.ts
- packages/superset-ui-core/src/query/normalizeOrderBy.ts
- packages/superset-ui-core/test/query/normalizeOrderBy.test.ts
- plugins/plugin-chart-echarts/src/MixedTimeseries/buildQuery.ts
🏆 Enhancements
This PR makes a normalized orderby object in QueryObject instead of `timeseries_limit_metric` and `order_desc`,
also fixed `mixed timeseries chart` unable to sort by. related issue: https://github.com/apache/superset/issues/15345
> feat: Normalize orderby clause

- plugins/plugin-chart-echarts/src/Pie/EchartsPie.tsx
- plugins/plugin-chart-echarts/src/Pie/transformProps.ts
🏆 Enhancements
single select by default for pie chart and set highlighting effect when applying x-filtering. 
https://user-images.githubusercontent.com/11830681/124380570-ec055900-dcef-11eb-83cb-1d36f62dd810.mov
https://user-images.githubusercontent.com/11830681/124380602-1d7e2480-dcf0-11eb-8579-8367169d2a21.mov
> feat(plugin-chart-echarts): single select by default for pie chart

- plugins/plugin-chart-echarts/src/Funnel/EchartsFunnel.tsx
- plugins/plugin-chart-echarts/src/Funnel/transformProps.ts
add cross-filter for funnel
in `Video Game Sales` dashbord.
> feat(plugin-chart-echarts): crossfilter with single selection in the funnel chart

- packages/superset-ui-chart-controls/src/utils/getColorFormatters.ts
- packages/superset-ui-chart-controls/test/utils/getColorFormatters.test.ts
Improves code coverage of `getColorFormatters` to 100%
> chore(chart-controls): improve test coverage

- plugins/plugin-chart-table/src/TableChart.tsx
- plugins/plugin-chart-table/src/controlPanel.tsx
- plugins/plugin-chart-table/src/transformProps.ts
- plugins/plugin-chart-table/src/types.ts
Adds conditional formatting to Table chart.
Conditional formatting feature is described in https://github.com/apache/superset/pull/15651
In the case of Table chart, if conditional formatting is defined (at least 1 formatter has been added), cell bars are disabled and replaced with formatter's colors.
https://user-images.githubusercontent.com/15073128/125609934-3a04ff76-c8a2-48f3-916e-23c5ca567fd0.mov
CC @junlincc @rusackas @michael-s-molina
> feat(plugin-chart-table): implement conditional formatting

- packages/superset-ui-chart-controls/package.json
- packages/superset-ui-chart-controls/src/shared-controls/components/ColumnConfigControl/constants.tsx
- packages/superset-ui-demo/package.json
- plugins/plugin-chart-table/package.json
- plugins/plugin-chart-table/src/TableChart.tsx
- yarn.lock
🏆 Enhancements
This should allow us to tree-shake and only pull in the icons that we actually use from react-icons. see here: https://github.com/react-icons/react-icons#installation-for-meteorjs-gatsbyjs-etc
This should help us reduce the bundle size in superset proper (see the massive react-icons/fa chunk here): 
Test plan:
Load up the storybook, and see icons in the table still render
to: @ktmud @kgabryje
> fix: Reduce bundle sizes from react-icons

- plugins/legacy-plugin-chart-world-map/src/index.js
- plugins/legacy-preset-chart-big-number/src/BigNumber/index.ts
- plugins/legacy-preset-chart-big-number/src/BigNumberTotal/index.ts
- plugins/legacy-preset-chart-nvd3/src/Area/index.js
- plugins/legacy-preset-chart-nvd3/src/DistBar/index.js
- plugins/plugin-chart-echarts/src/Pie/index.ts
- plugins/plugin-chart-echarts/src/Timeseries/index.ts
- plugins/plugin-chart-pivot-table/src/plugin/index.ts
- plugins/plugin-chart-table/src/index.ts
🏆 Enhancements
Change “Popular” to “Highly-used”  and  for the most popular charts https://github.com/apache/superset/projects/30#card-64852582
> chore: change popular to Highly-used

- packages/superset-ui-chart-controls/src/types.ts
- plugins/plugin-chart-table/src/controlPanel.tsx
Change `mapStateToProps.controlState` type from `this & ExtraControlProps` to `ControlState`
> chore(chart-controls): improve typing for mapStateToProps

- plugins/legacy-plugin-chart-country-map/src/index.js
- plugins/legacy-plugin-chart-paired-t-test/src/index.js
- plugins/legacy-plugin-chart-parallel-coordinates/src/index.js
- plugins/legacy-plugin-chart-rose/src/index.js
- plugins/legacy-plugin-chart-time-table/src/index.ts
- plugins/legacy-preset-chart-big-number/src/BigNumber/index.ts
- plugins/legacy-preset-chart-big-number/src/BigNumberTotal/index.ts
- plugins/legacy-preset-chart-nvd3/src/Compare/index.js
- plugins/legacy-preset-chart-nvd3/src/LineMulti/index.js
- plugins/plugin-chart-echarts/src/MixedTimeseries/index.ts
- plugins/plugin-chart-table/src/index.ts
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
> chore: add tags and description metadata

- plugins/plugin-chart-echarts/src/Pie/transformProps.ts
🐛 Bug Fix
Currently unselected slices are fully transparent. This changes the opacity of filtered slices to `SemiTransparent` (=0.3) instead of `Transparent` (0).
Closes https://github.com/apache/superset/issues/15832
> fix(plugin-chart-echarts): make filtered pie slices semi-transparent

- plugins/plugin-chart-pivot-table/src/plugin/buildQuery.ts
- plugins/plugin-chart-pivot-table/src/plugin/controlPanel.ts
- plugins/plugin-chart-pivot-table/src/types.ts
- plugins/plugin-chart-pivot-table/test/plugin/buildQuery.test.ts
- plugins/plugin-chart-pivot-table/test/plugin/transformProps.test.ts
Implement sorting query results by metric, descending (default) or ascending. If no sort by metric is specified, query results will be sorted by the first adhoc metric, descending (the same behaviour as in Table chart for consistency).
Testing instructions:
1. Create a pivot table chart
2. Use a saved metric or adhoc metric in "Sort by" control. I also suggest setting a low row limit (e.g. 10) to see the effect of sort by clearly.
https://user-images.githubusercontent.com/15073128/126995425-95ccfeb6-05be-4139-93e7-883eab3f59ff.mov
CC: @junlincc 
closes https://github.com/apache/superset/issues/15883#issuecomment-885968829
> feat(plugin-chart-pivot-table): sort by metric

- packages/superset-ui-core/package.json
- packages/superset-ui-demo/package.json
Move `@emotion/cache` and `@emotion/react` from dependencies to peer dependencies in order to fix build errors when linking superset-ui-core to superset locally
> chore(core): move emotion deps to peer deps

- plugins/plugin-chart-table/src/controlPanel.tsx
🏆 Enhancements
🐛 Bug Fix
This Pr fixes an issue where server pagination is enable in table chart but without feature flags native filter or dashboard cross filters not enabled. Feature flags cross filters or native filters must be enabled to use table pagination.
🏠 Internal
> fix: add feature flags for pagination control in table chart

- plugins/legacy-plugin-chart-pivot-table/src/index.js
- plugins/legacy-plugin-chart-treemap/src/index.js
- plugins/plugin-chart-echarts/src/Treemap/index.ts
- plugins/plugin-chart-pivot-table/src/plugin/index.ts
As noted by Airbnb, the V2 pivot table has not yet achieved feature parity with the original. Changing the names was too eager of a move. We should consult with the community before making this kind of change.
> chore: Revert "chore: remove V2 and add Deprecated"

- plugins/plugin-chart-echarts/src/MixedTimeseries/EchartsMixedTimeseries.tsx
- plugins/plugin-chart-echarts/src/MixedTimeseries/controlPanel.tsx
- plugins/plugin-chart-echarts/src/MixedTimeseries/index.ts
- plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/MixedTimeseries/types.ts
🏆 Enhancements
Add cross filter highlighting to MixdTimeSeries chart.
Both series support setting cross filter separately.
https://user-images.githubusercontent.com/11830681/127747100-889620ec-7ece-43f8-b9c1-6577a6e1ccf1.mov
> feat(plugin-chart-echarts): implement cross filter in mixd-timeseries chart

- packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
- plugins/legacy-preset-chart-nvd3/src/DualLine/controlPanel.ts
1 of the controls in Dual Line chart was still using the old UI, even with DND feature flag on. This PR fixes it.
I also moved some controls to separate rows to avoid ugly overflow.
Before: https://github.com/apache/superset/issues/16018
After:
CC: @jinghua-qa @junlincc
> fix(legacy-preset-chart-nvd3): dual line dnd control missing

- plugins/plugin-chart-echarts/src/Tree/controlPanel.tsx
Metric control in Tree chart was using the old UI even with DnD flag enabled. This PR fixes it.
Before: https://github.com/apache/superset/issues/16021
After:
CC @jinghua-qa @junlincc
> fix(plugin-chart-echarts): missing dnd control in tree chart

- plugins/plugin-chart-pivot-table/src/plugin/controlPanel.ts
Before there was no way to disable date formatting to see the original value of temporal column in pivot table. This PR enables clearing the select button value.
https://user-images.githubusercontent.com/15073128/127890757-204a2287-be36-4b89-9815-5b2d7479108b.mov
Fixes https://github.com/apache/superset/issues/15947
CC @junlincc @jinghua-qa
> fix(plugin-chart-pivot-table): make date formatting clearable

- packages/superset-ui-chart-controls/src/types.ts
- packages/superset-ui-chart-controls/src/utils/getColorFormatters.ts
- packages/superset-ui-chart-controls/test/utils/getColorFormatters.test.ts
- yarn.lock
🏆 Enhancements
Add a new conditional formatting operator to enable automatic formatting. This is a non-breaking change, as it only adds support for a new option.
> feat(plugin-chart-pivot-table): add automatic conditional formatter

- plugins/legacy-plugin-chart-sunburst/src/controlPanel.ts
🐛 Bug Fix
Move Sunburst chart color scheme controls to separate rows.
> fix(legacy-plugin-chart-sunburst): move color scheme controls to own row

- plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
Before, we were displaying nulls as zeros when using "Sum" aggregate function. Now we filter out the nulls before passing them to the pivot table, so they are not included in the calculations.
Before: see https://github.com/apache/superset/issues/15938
After:
CC @junlincc @jinghua-qa
> fix(plugin-chart-pivot-table): dont display nulls as 0

- plugins/plugin-chart-pivot-table/package.json
- plugins/plugin-chart-pivot-table/src/plugin/controlPanel.ts
This PR excludes subtotals from conditional formatting coloring to match the old Heatmap table feature
> fix(plugin-chart-pivot-table): dont apply colors to subtotals

- plugins/plugin-chart-echarts/src/Funnel/transformProps.ts
- plugins/plugin-chart-echarts/src/Pie/transformProps.ts
- plugins/plugin-chart-echarts/test/Funnel/transformProps.test.ts
- plugins/plugin-chart-echarts/test/Pie/transformProps.test.ts
🐛 Bug Fix
Remove label escaping in Pie and Funnel charts that were causing hml escaping where it wasn't needed. Closes https://github.com/apache/superset/issues/16057
> fix(plugin-chart-echarts): fix null labels on pie and funnel charts

- packages/superset-ui-chart-controls/src/components/ColumnOption.tsx
- packages/superset-ui-chart-controls/src/components/MetricOption.tsx
This PR allows showing the tooltip conditionally as well as passing down the ref.
Required to be merged first to enable PR https://github.com/apache/superset/pull/16060
> chore: Show tooltip conditionally and pass ref down

- plugins/legacy-preset-chart-nvd3/src/DistBar/controlPanel.ts
Bar chart doesn't allow "Series" and "Breakdown" controls to overlap. If user adds the same column to those controls, we get "Unexpected error". This PR disallows adding a column to "Breakdown" if it's already in "Series" (and the other way around too) when drag and drop is enabled.
Requires https://github.com/apache/superset/pull/16090 to work
Fixes https://github.com/apache/superset/issues/16071
https://user-images.githubusercontent.com/15073128/128378703-bbebd2ae-a948-4fce-a0bf-bd61cf7c8b1a.mov
CC @junlincc @jinghua-qa
> fix(legacy-preset-chart-nvd3): bar chart unexpected error

- packages/superset-ui-core/src/query/types/Filter.ts
- packages/superset-ui-core/src/query/types/Query.ts
- plugins/plugin-chart-table/src/TableChart.tsx
- plugins/plugin-chart-table/src/transformProps.ts
- plugins/plugin-chart-table/src/types.ts
- plugins/plugin-chart-table/src/utils/DateWithFormatter.ts
🏆 Enhancements
🐛 Bug Fix
Add support for emitting temporal time filters with time grain. Also add missing `isExtra` property to `BaseSimpleAdhocFilter` and `QueryObjectFilterClause` signatures.
https://user-images.githubusercontent.com/33317356/128667009-3999c26b-5e9a-466e-96af-616f2f39fb87.mp4
https://user-images.githubusercontent.com/33317356/128667541-475dfdab-b86b-4deb-a891-46096b0341ad.mp4
> feat(plugin-chart-table): add support for temporal x-filter

- packages/superset-ui-chart-controls/src/utils/getColorFormatters.ts
- packages/superset-ui-chart-controls/test/utils/getColorFormatters.test.ts
Before, the minimal opacity for values coloured with conditional formatting was 0.3. That value turned out to be too large, as the low values were not contrasting with the high values. This PR changes minimal opacity to 0 for "None" operator and 0.05 for other operators
Before:
After:
Fixes https://github.com/apache/superset/issues/16099
CC @graceguo-supercat @junlincc
> fix(chart-controls): lower minOpacity in conditional formatting

- plugins/legacy-plugin-chart-world-map/src/index.js
- plugins/legacy-preset-chart-big-number/src/BigNumber/index.ts
- plugins/legacy-preset-chart-big-number/src/BigNumberTotal/index.ts
- plugins/legacy-preset-chart-nvd3/src/DistBar/index.js
- plugins/plugin-chart-echarts/src/Pie/index.ts
- plugins/plugin-chart-echarts/src/Timeseries/Area/index.ts
- plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/index.ts
- plugins/plugin-chart-echarts/src/Timeseries/Regular/Line/index.ts
- plugins/plugin-chart-echarts/src/Timeseries/Regular/Scatter/index.ts
- plugins/plugin-chart-pivot-table/src/plugin/index.ts
🏆 Enhancements
Addressing requests to change "Highly Used" tag to "Popular" as was originally implemented. The version bump for these packages will need to coincide with a similar change on the Superset side.
🐛 Bug Fix
🏠 Internal
> chore: change Highly-used back to Popular

- plugins/legacy-plugin-chart-sankey-loop/src/SankeyLoop.js
🐛 Bug Fix
Otherwise every (re)render adds a new svg to the element. This is essentially the same as the fix that was applied to legacy-plugin-chart-sankey back in apache/superset#254
> fix(legacy-plugin-chart-sankey-loop): clear element before redrawing

- plugins/legacy-plugin-chart-heatmap/src/controlPanel.ts
🏆 Enhancements
Stacks and sorts Heatmap controls to a better UI/UX. The proposed change targets a more uniform display of the information for the user and gives the controls more space to present the UI elements. The idea is also to avoid, as much as we can, the expansion of the controls section, preserving the available space for displaying the charts.
Before:
https://user-images.githubusercontent.com/70410625/128224568-28aee072-f59a-45d1-857c-95def7ef4b76.mov
After:
https://user-images.githubusercontent.com/70410625/128225226-a005d21b-c359-48ce-a4d3-a976526c8e8e.mov
> chore: stacks and sorts Heatmap controls

- packages/superset-ui-chart-controls/package.json
- packages/superset-ui-chart-controls/src/components/Tooltip.tsx
This PR implements a small hack to prevent Safari from showing its default tooltip when a text is truncated and a custom Antdesign tooltip is already present.
https://github.com/apache/superset/pull/16145
> fix: Hide Safari default tooltip

- plugins/plugin-chart-echarts/src/Radar/transformProps.ts
🐛 Bug Fix
closes: https://github.com/apache/superset/issues/16120
- Select `cleaned_sales_data` dataset
- Open explore page and switch to Radar Chart
- Add sum(sales), avg(sales) and sum(0) metrics into Chart
- Run query, the sum(0) metric at the center of polar coordinates.
> fix: 0 indicator on radar viz

- plugins/plugin-chart-pivot-table/package.json
Bump react-pivottable version.
Changes:
font size (12px), border colors (#e0e0e0) and line height (1.4) matching Table chart.
This PR replaces https://github.com/apache-superset/superset-ui/pull/1277
> chore(plugin-chart-pivot-table): change fontsize and border colors

- plugins/legacy-plugin-chart-time-table/src/index.ts
- plugins/plugin-chart-echarts/src/MixedTimeseries/index.ts
🏆 Enhancements
Removing the `Advanced Analytics` label from these charts since... well... they don't have Advanced Analytics.
🐛 Bug Fix
🏠 Internal
> chore: removing errant label from two charts that don't have AA (but should)

- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
🐛 Bug Fix
https://github.com/apache/superset/issues/16070
this is hack to make timeseries line chart clickable when tooltip trigger is 'item' (see https://echarts.apache.org/en/option.html#tooltip.trigger),  so that the chart can emit cross-filtering.
https://user-images.githubusercontent.com/11830681/129067504-1ef36ba3-2a2e-49bf-b2a7-05e6b95ee4cd.mov
> fix(plugin-chart-echarts): fix Time-series line x-filtering not working when not rich tooltip

- plugins/plugin-chart-pivot-table/src/plugin/transformProps.ts
- plugins/plugin-chart-table/src/transformProps.ts
Before, proper date formatting based on selected timegrain was applied only when column's name was `__timestamp`. This PR changes that behaviour in Table and Pivot Table v2 charts so that if granularity and adaptive formatting are selected, the date formatter proper for the time grain is used.
Before: see https://github.com/apache/superset/issues/16283
After: 
Fixes https://github.com/apache/superset/issues/16283
A PR with the change on backend is in progress (made by @villebro)
CC: @junlincc
> fix(plugin-chart-table): apply correct date formatting for time grain

- packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
If `ENABLE_DND_WITH_CLICK_UX` feature flag is enabled, change the Time Column placeholder from "Drop temporal column here" to "Drop a temporal column here or click"
Fixes https://github.com/apache/superset/issues/16307
> fix(chart-controls): temporal col placeholder for hybrid dnd

- plugins/legacy-preset-chart-big-number/src/BigNumber/controlPanel.tsx
🐛 Bug Fix
https://github.com/apache-superset/superset-ui/pull/1278 introduced the ability to show a timestamp for the value of big number, but as a result it overrode the default time format for the tooltip in big number trendline charts to a somewhat obscure (for americans) `%d-%m-%Y %H:%M:%S` format. This PR:
- makes the time formatter always visible (so that the big number trendline chart can always set it)
- Defaults to a format that's used globally, `'%Y-%m-%d %H:%M:%S'`
to: @krsnik93 @villebro @ktmud
> fix: Improve big number time format UX

- plugins/plugin-chart-echarts/src/Timeseries/Area/controlPanel.tsx
- plugins/plugin-chart-echarts/src/Timeseries/Regular/controlPanel.tsx
- plugins/plugin-chart-echarts/src/Timeseries/Step/controlPanel.tsx
- plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
- plugins/plugin-chart-echarts/src/Timeseries/types.ts
- plugins/plugin-chart-echarts/src/controls.tsx
🏆 Enhancements
releated to https://github.com/apache-superset/superset-ui/pull/1279
closes https://github.com/apache/superset/issues/16063
> feat(plugin-chart-echarts): add only_total control to ts chart

- plugins/plugin-chart-echarts/src/Timeseries/Area/controlPanel.tsx
- plugins/plugin-chart-echarts/src/Timeseries/Regular/controlPanel.tsx
- plugins/plugin-chart-echarts/src/Timeseries/Step/controlPanel.tsx
- plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
🏆 Enhancements
related to https://github.com/apache/superset/issues/16343#event-5184581121
set marker size to 0-20 for time-series echart.
> fix(plugin-chart-echarts): improve marksize range

- plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
This PR only solves an issue with the scrollbar not appearing in the table container but at the far right. Read [this comment](https://github.com/apache/superset/issues/15935#issuecomment-897699534) for context 
https://user-images.githubusercontent.com/60598000/129375411-4e61d037-2a27-4762-a6f7-13848813e763.mp4
https://user-images.githubusercontent.com/60598000/129585796-2fe468b7-1dfa-4367-9459-34a3f3fb5c5b.mp4
1. Open Explore with a Pivot Table V2 viz
2. Observe the table and scroll
3. Make sure the scrollbar appears within the table container
> fix: Make the scrollbar appear inside the table  

- packages/superset-ui-core/src/color/ColorScheme.ts
🏆 Enhancements
Adds new `isDefault` flag to the color schemes. To be used for setting a custom scheme in the config as default.
🐛 Bug Fix
🏠 Internal
> chore: color schemes can be default theoretically

- plugins/legacy-preset-chart-big-number/src/BigNumber/BigNumber.tsx
- plugins/legacy-preset-chart-big-number/src/BigNumber/transformProps.ts
- plugins/legacy-preset-chart-big-number/src/BigNumberTotal/controlPanel.ts
- plugins/legacy-preset-chart-big-number/test/transformProps.test.ts
🏆 Enhancements
closes: https://github.com/apache/superset/issues/16221
Support timestamp format in BigNumber viz
Test instruction:
1. Select birth_names dataset
2. Switch to Big Number viz
3. Select Max(ds) as Metric
4. Select TimeStamp format checkbox
> fix: bignumber format by time formatter

- plugins/plugin-chart-echarts/src/Gauge/index.ts
🐛 Bug Fix
refer to https://github.com/apache/superset/issues/16255
https://user-images.githubusercontent.com/11830681/130360633-85e8284b-ba5a-435e-a5f3-e3a9e612ebbf.mov
> fix(plugin-chart-echarts): [gauge chart] filter indicator not be shown

- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/utils/prophet.ts
🐛 Bug Fix
This PR fixes the problem that custom metric label in the legend cannot show correctly.
refer to https://github.com/apache/superset/issues/16332
> fix(plugin-chart-echarts): [feature-parity] display custom metric label

- plugins/plugin-chart-echarts/package.json
- plugins/plugin-chart-echarts/src/Gauge/transformProps.ts
🏆 Enhancements
Upgrade to latest version of ECharts. Includes many new features and bugfixes, and addresses one cosmetic issue related to gauge chart.
Now Gauge chart defaults to showing the pointer below the text:
Previously the text fell below the pointer:
> chore(plugin-chart-echarts): bump to ECharts 5.2.0

- plugins/legacy-plugin-chart-pivot-table/package.json
- plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
It uses the Data Tables jquery plugin and is deprecated, so don't want to try to remove jquery from it. Instead will make it an explicit dependency so that jquery can be removed from the rest of superset.
> chore: isolate the one actual jquery dependency

- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
- packages/superset-ui-core/src/query/buildQueryObject.ts
- packages/superset-ui-core/src/query/types/Query.ts
- packages/superset-ui-core/src/query/types/QueryFormData.ts
- plugins/plugin-chart-echarts/src/BoxPlot/buildQuery.ts
- plugins/plugin-chart-echarts/src/BoxPlot/controlPanel.ts
- plugins/plugin-chart-echarts/test/BoxPlot/buildQuery.test.ts
🏆 Enhancements
Currently it is impossible to restrict the number of series in non-temporal charts. This adds three new `QueryForm` and `QueryObject` properties, along with relevant shared controls for them:
- `series_columns`: the columns to group by when limiting series (previously always assumed to be all groupby columns except the temporal column). This can be left `undefined`/`[]`, in which case series limiting won't happen.
- `series_limit`: to replace `timeseries_limit`
- `series_limit_metric`: to replace `timeseries_limit_metric`
As a POC, this functionality is implemented on the BoxPlot chart where this functionality was mostly broken (only working if distribution was across temporal column).
Related PR on `apache/superset`: https://github.com/apache/superset/pull/16660
Here we've …
> feat(core): add support for non-temporal series limit

- plugins/legacy-preset-chart-nvd3/package.json
- plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
- plugins/plugin-chart-echarts/package.json
- plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
- plugins/plugin-chart-echarts/src/utils/annotation.ts
- plugins/plugin-chart-echarts/test/utils/annotation.test.ts
- yarn.lock
🏠 Internal
Replace `mathjs` (11 Mb bundle) with `math-expression-evaluator` (71 kb) as done on https://github.com/apache/superset/pull/16701.
Checklist:
- added unit tests to `plugins-chart-echart` for formula evaluation
- ensure formula annotations work on both NVD3 and ECharts plugin:
NVD3 plugin after migration:
ECharts plugin after migration:
Also fix z-index of formula to make sure it is displayed above other charts:
> chore: replace mathjs with mexp

- packages/superset-ui-chart-controls/src/operators/boxplotOperator.ts
- packages/superset-ui-chart-controls/src/operators/contributionOperator.ts
- packages/superset-ui-chart-controls/src/operators/prophetOperator.ts
- packages/superset-ui-chart-controls/test/utils/operators/boxplotOperator.test.ts
- packages/superset-ui-chart-controls/test/utils/operators/contributionOperator.test.ts
- packages/superset-ui-chart-controls/test/utils/operators/pivotOperator.test.ts
- packages/superset-ui-chart-controls/test/utils/operators/prophetOperator.test.ts
- packages/superset-ui-chart-controls/test/utils/operators/resampleOperator.test.ts
- packages/superset-ui-chart-controls/test/utils/operators/rollingWindowOperator.test.ts
- packages/superset-ui-chart-controls/test/utils/operators/sortOperator.test.ts
- packages/superset-ui-chart-controls/test/utils/operators/timeCompareOperator.test.ts
- plugins/plugin-chart-echarts/src/BoxPlot/buildQuery.ts
- plugins/plugin-chart-echarts/src/BoxPlot/types.ts
- plugins/plugin-chart-echarts/src/Timeseries/buildQuery.ts
🏆 Enhancements
No functional changes, some refactor for postprocessing. Added boxplotOperator, contributionOperator and prophetOperator.
> refactor: improve code smell for postprocessing

- plugins/plugin-chart-echarts/package.json
- plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
- plugins/plugin-chart-echarts/src/BoxPlot/types.ts
- plugins/plugin-chart-echarts/src/Funnel/transformProps.ts
- plugins/plugin-chart-echarts/src/Funnel/types.ts
- plugins/plugin-chart-echarts/src/Gauge/transformProps.ts
- plugins/plugin-chart-echarts/src/Graph/transformProps.ts
- plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/MixedTimeseries/types.ts
- plugins/plugin-chart-echarts/src/Pie/transformProps.ts
- plugins/plugin-chart-echarts/src/Pie/types.ts
- plugins/plugin-chart-echarts/src/Radar/transformProps.ts
- plugins/plugin-chart-echarts/src/Radar/types.ts
- plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx
- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
- plugins/plugin-chart-echarts/src/Tree/transformProps.ts
- plugins/plugin-chart-echarts/src/Treemap/transformProps.ts
- plugins/plugin-chart-echarts/src/Treemap/types.ts
- plugins/plugin-chart-echarts/src/types.ts
- yarn.lock
🐛 Bug Fix
Bump to latest version of ECharts. Also set `axisLabel.hideOverlap` to `true` to get rid of overlapping x-axis labels. See https://github.com/apache/echarts/pull/15712 and https://github.com/apache/echarts/pull/15583 for details.
> chore(plugin-chart-echarts): bump to ECharts 5.2.1

- plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
- plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
- plugins/plugin-chart-pivot-table/src/types.ts
💔 Breaking Changes: None
🏆 Enhancements: Pivot table now at 100% width
📜 Documentation: N/A
🐛 Bug Fix: Reports screenshots are too small for charts
🏠 Internal: N/A
📸 Screenshots of the fix:
> fix: Pivot table now at 100% width

- plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx
- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/components/Echart.tsx
- plugins/plugin-chart-echarts/src/types.ts
🏆 Enhancements
This PR supports two features: 
1. when user double click on the legend-> select single series, no change on ad hoc filter field -> click again to show all series.
2. when user double click on a single series(in place filtering) -> display the correlative legend only -> no change on ad hoc filter field -> double click again to show all series
related to: 
- https://github.com/apache/superset/issues/16354. 
- https://github.com/apache/superset/issues/16364
https://user-images.githubusercontent.com/11830681/132133087-c5e573af-bd15-462f-b2e3-291237f167b7.mov
https://user-images.githubusercontent.com/11830681/132133090-129bd28c-3b02-466b-8e23-8e678196a870.mov
https://user-images.githubusercontent.com/11830681/132132829-e5970dc6-6860-4765-8a58-26de9f0b63f2.mov …
> feat(plugin-chart-echarts): [feature-parity] support double clicking legend and series to view single selected series

- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
- packages/superset-ui-chart-controls/src/shared-controls/legacySortBy.tsx
- packages/superset-ui-core/src/query/normalizeOrderBy.ts
- packages/superset-ui-core/test/query/normalizeOrderBy.test.ts
- plugins/plugin-chart-pivot-table/src/plugin/buildQuery.ts
- plugins/plugin-chart-pivot-table/src/plugin/controlPanel.ts
- plugins/plugin-chart-pivot-table/src/types.ts
- plugins/plugin-chart-pivot-table/test/plugin/buildQuery.test.ts
- plugins/plugin-chart-pivot-table/test/plugin/transformProps.test.ts
🏆 Enhancements
backend changes at: https://github.com/apache/superset/pull/16849
currently, Superset use `timeseries_limit_metric` control for main query orderby. While this is actually prepared for the inner query when viz is timeseries-like.
To fix the original incorrect use, so this PR introduce a `legacy_order_by` control.
This PR only migrate `pivot table v2`.
> refactor: migrate timeseries_limit_metric to legacy_order_by

- plugins/legacy-plugin-chart-partition/src/controlPanel.tsx
- plugins/legacy-plugin-chart-rose/src/controlPanel.tsx
- plugins/legacy-preset-chart-nvd3/src/NVD3Controls.tsx
🐛 Bug Fix
replace `absolute difference` with `difference` in legacy charts
related issue: https://github.com/apache/superset/issues/16766
> fix: replace absolute difference with difference in legacy charts

- packages/superset-ui-chart-controls/src/sections/advancedAnalytics.tsx
- packages/superset-ui-chart-controls/test/utils/operators/rollingWindowOperator.test.ts
- packages/superset-ui-chart-controls/test/utils/operators/timeCompareOperator.test.ts
- packages/superset-ui-core/src/query/types/AdvancedAnalytics.ts
🐛 Bug Fix
Currently, incorrect type of calculation in `time comparsion`, should replace absolute difference with difference.
backend codes at: https://github.com/apache/superset/pull/16930
related issue: https://github.com/apache/superset/issues/16766
> fix: replace absolute difference with difference in echart

- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
- plugins/plugin-chart-echarts/src/utils/prophet.ts
- plugins/plugin-chart-echarts/test/utils/prophet.test.ts
🏆 Enhancements
The need to be able to create custom forecasts (without Prophet) has come up. In order to make this possible, we will assume that a forecast is present if there is a series with the forecast suffix (`__yhat`, `__yhat_lower` or `__yhat_upper`).
This is an intermediate step to decouple forecasts from Prophet - ultimately we should refactor the code in the following ways:
- move the relevant utilities/types from `plugin-chart-echarts` to `superset-ui/core`
- add support for other suffixes to make it possible to do similar inference from time offset series etc. Example: `my_metric` could be accompanied by `my_metric__offset(PT1D)` which could then be shown in the legend (with translations) as "my metric (1 day time offset)" or similar.
- Add documentation for how these can be …
> feat(plugin-chart-echarts): add support for custom forecasts

- packages/superset-ui-chart-controls/src/operators/rollingWindowOperator.ts
- packages/superset-ui-chart-controls/test/utils/operators/rollingWindowOperator.test.ts
- packages/superset-ui-core/src/query/types/PostProcessing.ts
- plugins/plugin-chart-echarts/src/Timeseries/buildQuery.ts
🐛 Bug Fix
Currently, Rolling Window calculation results are incorrect on multiple series. 
Backendcode at: https://github.com/apache/superset/pull/16945
> fix: rolling and cum operator in multiple series chart

- packages/superset-ui-chart-controls/src/sections/advancedAnalytics.tsx
🏆 Enhancements
hide `periods` and `min periods` when unselect rolling function or cumsum
> chore: hide rolling_periods and min_periods

- package-lock.json
- plugins/plugin-chart-echarts/package.json
- plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx
- plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
🐛 Bug Fix
Bump ECharts to 5.2.2 (changelog: https://dist.apache.org/repos/dist/dev/echarts/5.2.2-rc.1/RELEASE_NOTE.txt) which adds mouseover functionality to line/area charts. See how hovering now triggers the `mouseover` event, where previously only the marker triggered it. This will make the tooltip highlighting and cross-filtering more intuitive.
https://user-images.githubusercontent.com/33317356/139024390-9b396b97-9490-4aaa-be7e-644c40294842.mp4
https://user-images.githubusercontent.com/33317356/139025543-6aba15a3-397f-4662-9b38-b31a197b6aa9.mp4
> chore(plugin-chart-echarts): bump echarts to 5.2.2

- plugins/plugin-chart-echarts/src/MixedTimeseries/EchartsMixedTimeseries.tsx
- plugins/plugin-chart-echarts/src/MixedTimeseries/controlPanel.tsx
- plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/MixedTimeseries/types.ts
- plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
- plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
- plugins/plugin-chart-echarts/src/Timeseries/types.ts
🐛 Bug Fix
Fixes multiple issues on the Mixed Timeseries chart:
- Tooltip x-axis value shows `0NaN` when rich tooltip is disabled and the value is a decimal.
- On the case of a mixed line+bar chart, the bars below the line won't show in the tooltip.
- Remove bogus min and max x-axis values (these have been deprecated from the main Timeseries chart some time ago).
Tooltip correctly shows the x-axis value when the y-value is a decimal:
The erroneous min and max x-axis values are removed, and hovering on a bar underneath a line works as intended:
https://user-images.githubusercontent.com/33317356/139655494-8ab0257a-2ece-4821-a41e-727437cd8490.mp4
Tooltip shows `0NaN` when the metric value is a decimal value:
The x-axis shows incorrect min and max values, and hovering on a bar underneath a …
> fix(plugin-chart-echarts): fix tick labels and tooltip

- packages/superset-ui-chart-controls/src/operators/boxplotOperator.ts
- packages/superset-ui-core/src/query/types/PostProcessing.ts
- packages/superset-ui-core/test/query/types/PostProcessing.test.ts
- plugins/plugin-chart-echarts/src/BoxPlot/buildQuery.ts
- plugins/plugin-chart-echarts/test/BoxPlot/buildQuery.test.ts
🐛 Bug Fix
The post processing operation didn't include the groupby columns, resulting in NULL values on the x-axis. This PR fixes the bug, adds tests and adds type guards for all post processing rules.
Closes https://github.com/apache/superset/issues/16951 , closes https://github.com/apache/superset/issues/16985
> fix(plugin-chart-echarts): boxplot groupby incorrect

- packages/superset-ui-core/src/query/types/AnnotationLayer.ts
- plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
🏆 Enhancements
supports annotation showLabel field. related to https://github.com/apache/superset/pull/17307
> feat(plugin-chart-echarts): support show annotation label [ID-8]

- packages/superset-ui-core/src/color/index.ts
- packages/superset-ui-core/src/color/utils.ts
- packages/superset-ui-core/test/color/utils.test.ts
- plugins/legacy-plugin-chart-calendar/src/vendor/cal-heatmap.css
- plugins/legacy-plugin-chart-calendar/src/vendor/cal-heatmap.js
🏆 Enhancements
The algorithm is to decide label color in white or black depending on background color (refer to https://stackoverflow.com/questions/3942878/how-to-decide-font-color-in-white-or-black-depending-on-background-color)
> feat(legacy-plugin-chart-calendar): increase the contrast of calendar heatmap color and label

- plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/controlPanel.tsx
- plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/index.ts
- plugins/plugin-chart-echarts/src/Timeseries/types.ts
remove the default Y-axis truncate check box to “unchecked” and add a tooltip next to the checkbox saying “It’s not recommended to truncate y-axis in Bar chart”
> feat:  remove the default Y-axis truncate in bar chart

- .esprintrc
- jest.config.js
- packages/superset-ui-core/test/translation/Translator.test.ts
- packages/superset-ui-core/test/utils/logging.test.ts
- test/__mocks__/mockExportObject.js
- test/__mocks__/mockExportString.js
- test/__mocks__/svgrMock.tsx
🏠 Internal
coordinate superset-ui unittest with main repository
1. Jest use source code for module import
2. remove dependence: `@airbnb/config-jest`
3. remove `@airbnb/config-jest` related "setup" before unit test
4. refactor some unittest
5. clean up
> chore: coordinate superset-ui unittest with main repository

- plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
🐛 Bug Fix
#1447 introduced a regression to area charts which broke both area and confidence bands. The reason for the original change was to remove area if it's not needed (a 0 opacity made it impossible to hover series underneath the series).
> fix(plugin-chart-echarts): fix opacity on area chart

- packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
🏠 Internal
See https://github.com/apache/superset/pull/17383.
> fix: update chart sorting control labels/descriptions

- plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
Cross filtering in PivotTable v2 didn't work properly when applied to an adhoc column (new feature). This PR fixes the issue.
> fix(plugin-chart-pivot-table): cross filtering by adhoc column

- packages/superset-ui-chart-controls/src/shared-controls/index.tsx
This PR is a dependency for the PR https://github.com/apache/superset/pull/17422. It passes the `dashboardId` to the `ColorSchemeControl`
See https://github.com/apache/superset/pull/17422 for more information
> chore: Pass dashboardId to ColorSchemeControl
